.travis.yml

Implement push to heroku when travis build passes

Travis 2 heroku

---

.travis.yml

added code climate token

---

app/views/layouts/application.html.slim

and a div surrounding the yield

Added flash messages to layout

---

app/controllers/users_controller.rb
app/models/user.rb
spec/views/layouts/_toolbar.html.slim_spec.rb
spec/views/offices/index.html.slim_spec.rb

Improved scope for users and rendering in specs

Minor updates

---

.travis.yml
lib/tasks/rubocop.rake

Allows users (and travis) to check ruby style guide compliance

Rubocop rake

---

spec/features/perform_benefit_check_spec.rb

This should improve code climate coverage

added feature test for dwp check

---

app/controllers/users_controller.rb
app/views/users/edit.html.slim
spec/controllers/users_controller_spec.rb

Implemented a user edit function and improved test coverage of the user_controller

improved handling of user tests and editing

---

app/controllers/users/invitations_controller.rb
app/models/user.rb
app/views/users/index.html.slim
app/views/users/invitations/new.html.slim
app/views/users/mailer/invitation_instructions.html.slim
config/initializers/devise.rb
config/locales/devise_invitable.en.yml
db/migrate/20150313151421_add_name_to_user.rb
db/schema.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/features/user_invite_spec.rb
spec/models/user_spec.rb

So that we can send properly addressed emails

Add name for User for email and display

---

config/locales/devise_invitable.en.yml

Inline with @leigh changes on https://www.pivotaltracker.com/story/show/87797096

Updated wording of email

---

README.md
lib/tasks/user.rake

After making name mandatory, it must be in task

updated user rake task

---

app/assets/stylesheets/navigation.scss
app/controllers/users_controller.rb
app/views/layouts/_toolbar.html.slim
app/views/layouts/application.html.slim
app/views/users/index.html.slim
app/views/users/sessions/new.html.slim
app/views/users/shared/_links.html.slim
spec/views/layouts/_toolbar.html.slim_spec.rb

Minor changes to appearance and styles

Style updates

---

Gemfile
Gemfile.lock
app/controllers/dwp_checks_controller.rb
app/models/dwp_check.rb
app/views/dwp_checks/show.html.slim
db/migrate/20150326131421_add_dwp_fields_to_dwp_check.rb
db/schema.rb
spec/controllers/dwp_checks_controller_spec.rb
spec/features/perform_benefit_check_spec.rb
spec/models/dwp_check_spec.rb
spec/spec_helper.rb

Initial version that connects to Proxy API

Talk to api

---

config/environments/production.rb
config/initializers/secret_token.rb
config/secrets.yml
config/settings.yml

Configure email for use with send grid and domain

Email setup

---

.gitignore
.rubocop.yml
Gemfile
Gemfile.lock
config/environments/production.rb
lib/log_stuff.rb

Enable and configure the production logging

Configure logging

---

config/database.yml

* removed comments
* switched to env_vars for production
* increased pool count in production

Update database connection

---

app/controllers/users/invitations_controller.rb
app/views/users/invitations/edit.html.slim
spec/features/user_can_accept_invite_spec.rb
spec/features/user_invite_spec.rb

Added exclusion for accept invitation (edit)

Allow user sign-in

---

Gemfile
Gemfile.lock
app/views/home/index.html.slim
app/views/layouts/application.html.slim

Admin dashboard

---

Dockerfile

Hi @colinbruce could you please check and merge the ruby upgrade thanks

upgrade ruby to the latest 2 version

---

app/views/home/index.html.slim

The google chart API was generating strange tick marks
e.g. 0-2-3-5-6
This forces 0-10 until we can determine why

Force graph into 1..10

---

Dockerfile

Our build process compiles the assets in the container, then exports them and uploads to S3 during deployment.

Build assets in container

---

app/controllers/home_controller.rb
app/models/dwp_check.rb
app/views/home/index.html.slim
spec/controllers/home_controller_spec.rb
spec/models/dwp_check_spec.rb

With the changes introduced, graphs will be displayed per office rather
than across the whole service, for the week gone.

Implemented graphs per office

---

Vagrantfile
config/database.yml
config/pg_hba.conf
db/seeds.rb
run.sh

To make it easier for people to pickup this project I have added postgres to the vagrant box.
Something else that would be good is to add some seed data for an admin user so that people can login.
@colinbruce can we add that seed data? Is it easy to make sure it doesn't run in production?

(WIP) Vagrant with postgres

---

.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/income_calculator.coffee
app/controllers/calculator_controller.rb
app/models/r2_calculator.rb
app/views/calculator/income.html.slim
spec/controllers/calculator_controller_spec.rb
spec/features/perform_an_income_check_spec.rb
spec/models/r2_calculator_spec.rb

Working CoffeeScipt calculator 
Test coverage of rendering the view, the on page JS and saving the 
result to the database via ajax

R2 calculator update

---

app/assets/javascripts/income_calculator.coffee

A rogue JS alert box was missed

Removed debug alert box

---

app/assets/javascripts/income_calculator.coffee

* moved calculations out of conditional block
* and placed parsed json on page in case of error

Fix for r2 calc

---

app/helpers/common_scopes.rb
app/helpers/home_helper.rb
app/models/dwp_check.rb
app/models/r2_calculator.rb

Re-factored to remove duplication
* Moved checks_by_day into a module 
* Called it from DwpCheck and R2Calculator

Refactor shared scope

---

app/assets/stylesheets/_colours.scss
app/assets/stylesheets/base.scss
app/views/calculator/income.html.slim
app/views/dwp_checks/new.html.slim
app/views/offices/_form.html.slim
app/views/users/edit.html.slim
app/views/users/invitations/edit.html.slim
app/views/users/invitations/new.html.slim
app/views/users/passwords/new.html.slim
app/views/users/sessions/new.html.slim

Style updates to comply with pivotal story
https://www.pivotaltracker.com/story/show/91284174

Style update/91284174

---

app/controllers/users/invitations_controller.rb
app/views/users/index.html.slim
app/views/users/invitations/new.html.slim
app/views/users/show.html.slim
spec/controllers/offices_controller_spec.rb
spec/factories/users.rb
spec/features/user_invite_spec.rb

* pass office_id to controller
* Display users' office on index and details view
* improved tests to ensure data sent to controller

Update user invite controller

---

config/locales/devise.en.yml

See https://www.pivotaltracker.com/story/show/93690194

Removed sign in/out alerts

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/errors.scss
app/models/dwp_check.rb
app/views/dwp_checks/new.html.slim
app/views/dwp_checks/show.html.slim
config/locales/en.yml
spec/features/perform_benefit_check_spec.rb
spec/views/dwp_checks/new.html.slim_spec.rb

* Set text to use en locale file as per content doc
* Display errors as per design
* Updated tests to reference changes and use locale file

Style error messages

---

app/views/feedback/new.html.slim
config/settings.yml
lib/settings.rb

Created new mail_feedback item
* added to settings
* updated feedback view

Implemented feedback mail

---

app/views/users/mailer/invitation_instructions.html.slim
config/locales/devise_invitable.en.yml

See [ticket 94074196](https://www.pivotaltracker.com/story/show/94074196)

Updated invite email

---

app/assets/stylesheets/base.scss
app/views/calculator/income.html.slim
app/views/dwp_checks/new.html.slim
app/views/layouts/application.html.slim
app/views/users/sessions/new.html.slim

Fix for [Pivotal](https://www.pivotaltracker.com/story/show/93655870)

Fix for sign in copy

---

app/controllers/dwp_checks_controller.rb
app/models/dwp_check.rb
app/services/process_dwp_service.rb
db/migrate/20150508131347_add_fields_to_dwp_check.rb
db/schema.rb
spec/controllers/dwp_checks_controller_spec.rb
spec/factories/dwp_checks.rb
spec/models/dwp_check_spec.rb
spec/services/process_dwp_service_spec.rb

Store our API key before sending to proxy
* store DWP unique key on return
* test generation and storage of both
* script data migration on adding office_id field
[finishes #92022094]

API data update

---

app/assets/stylesheets/navigation.scss

Fixed width of sub-nav bar

---

app/views/users/passwords/new.html.slim
app/views/users/shared/_links.html.slim
config/locales/devise_invitable.en.yml
config/locales/en.yml

Updates view for forgotten password

Update forgot password copy

---

app/views/users/invitations/edit.html.slim
app/views/users/passwords/edit.html.slim
config/locales/en.yml

See pivotal [ticket](https://www.pivotaltracker.com/story/show/93973236)

Update password error message

---

app/controllers/feedback_controller.rb
app/views/feedback/index.html.slim
config/routes.rb
spec/controllers/feedback_controller_spec.rb
spec/routing/feedback_routing_spec.rb

[ticket]
(https://www.pivotaltracker.com/story/show/93356556)
Allows admins to see lists of feedback on /feedback/display

Feedback display for admins

---

app/assets/stylesheets/base.scss
app/views/feedback/_form.html.slim

* decrease textarea height
* decrease radio button widths
* increase space above submit button

Style feedback form

---

app/assets/stylesheets/base.scss
app/views/home/index.html.slim

Increase space above logged out message

---

app/models/dwp_check.rb
app/views/dwp_checks/new.html.slim
config/locales/en.yml
spec/models/dwp_check_spec.rb
spec/views/dwp_checks/new.html.slim_spec.rb

Added the hint text for date field inputs
Updated date validation for Date to check
* moved all messages into locale file
* Migrated to date_validator gem
* Removed un-needed manual validators

Date field handling update

---

config/locales/en.yml

Total monthly income label had gained a suffix of s.
Removed.

Updated label

---

app/assets/stylesheets/_sizes.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/dwp_checks.scss
app/assets/stylesheets/foundation_and_overrides.scss
app/assets/stylesheets/navigation.scss
app/views/dwp_checks/show.html.slim
spec/features/perform_benefit_check_spec.rb

Set styling of the benefit checker

Update Benefit check styling

---

spec/controllers/ping_controller_spec.rb

Enhancing code coverage of the ping controller

Created tests for Ping controller

---

app/views/users/passwords/edit.html.slim
app/views/users/passwords/new.html.slim
app/views/users/sessions/new.html.slim

Turn off autocomplete for password forms

---

app/assets/stylesheets/base.scss

Replaced  the I-bar with a pointer

Updated display of details summary

---

app/assets/stylesheets/_measurements.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/buttons.scss
app/assets/stylesheets/design_patterns/_conditionals.scss
app/assets/stylesheets/design_patterns/_css3.scss
app/assets/stylesheets/design_patterns/_govuk_buttons.scss
app/assets/stylesheets/design_patterns/_shims.scss
app/assets/stylesheets/feedback.scss
app/assets/stylesheets/foundation_and_overrides.scss
app/assets/stylesheets/navigation.scss
app/views/calculator/income.html.slim
app/views/dwp_checks/new.html.slim
app/views/feedback/_form.html.slim

Update global styles

---

app/controllers/home_controller.rb
app/models/office.rb
app/views/home/index.html.slim

Admins see R1 graphs for each office
Updated controller logic to build hash with office name and 
dwp_check count by type data for each, non-digital, office.
[finishes #94093060]

Admin graph update 

---

app/models/office.rb

Update Office non_digital scope
to use ActiveRecord .not syntax

Updated Office

---

app/views/guide/index.html.md

Added Javascript to select the 
sub nav button when viewing page

Update staff guide

---

README.md

@PaulWyborn    Test master build on Jenkins

Test-master-build

---

db/migrate/20150609145418_add_user_role_constraint.rb
db/schema.rb

There is a validation in place already, but just to be thorough, I've
added the constrain in the database schema.

Added a constraint for the User role

---

app/views/home/_admin.html.slim

The new graph would resize on render.
Removed tabbed display to prevent

Admin graph update

---

.rubocop.yml
app/helpers/application_helper.rb
config/initializers/markdown_handler.rb
config/initializers/redcarpet.rb
spec/helpers/application_helper_spec.rb

- remove erb string inject method
- replace with ruby object builder

Update markdown handler

---

app/assets/stylesheets/base.scss

Fixed the css style for alert box close buttons

Updated styles

---

app/services/health_status.rb
spec/controllers/health_status_controller_spec.rb
spec/services/health_status_spec.rb

Added DWP API status to  **/healtcheck**
In the process I've tightened up the **HealthCheck** service.

95871446 dwp api healthcheck

---

README.md

@PWyborn Test of merging to master with Git_Commit in tag (Sha)

Test of master deploy with git commit in tag

---

app/views/guide/index.html.md

* changes to the markdown renderer had renamed the link targets

Updated TOC links

---

.rubocop.yml
config/initializers/redcarpet.rb

* re-introduced tables
* removed superfluous rubocop exception

Updated markdown handler

---

Gemfile
Gemfile.lock
app/models/jurisdiction.rb
db/migrate/20150616100546_create_jurisdictions.rb
db/schema.rb
db/seeds.rb
spec/factories/jurisdictions.rb
spec/models/jurisdiction_spec.rb

* include faker gem for factory data
* factory
* migration file
* basic validation and tests
* Add seed data

Create jurisdiction model

---

app/services/health_status.rb
spec/services/health_status_spec.rb

Instead of the generic SMTP service name

Name SendGrid as the service

---

app/models/user.rb
app/views/users/index.html.slim
app/views/users/show.html.slim
db/migrate/20150623135319_add_jurisdiction_id_to_user.rb
db/schema.rb
spec/factories/jurisdictions.rb
spec/models/office_spec.rb
spec/models/user_spec.rb

**Link user to jurisdiction**
Create a foreign key link from user to jurisdiction
* jurisdiction can be nil or a valid jurisdiction
* display the users' chosen jurisdiction on the index page
* display the users' chosen jurisdiction on the user/show view
* update the jurisdiction factory for invalid testing
Notes:
* No changes to the user/edit view as that will be done in 
the user profile ticket
* update the office tests to remove duplication of
the clear jurisdiction code

Link user to jurisdiction

---

app/models/office.rb
spec/models/office_spec.rb
spec/views/offices/index.html.slim_spec.rb

Ensure office names are unique

Make office name unique

---

app/models/ability.rb
app/views/layouts/_toolbar.html.slim
app/views/offices/_form.html.slim
app/views/offices/edit.html.slim
app/views/offices/show.html.slim
spec/controllers/offices_controller_spec.rb
spec/features/office_management_spec.rb
spec/views/layouts/_toolbar.html.slim_spec.rb
spec/views/offices/edit.html.slim_spec.rb
spec/views/offices/show.html.slim_spec.rb

* Managers will have a link to 'My office' on the toolbar
* Managers will not see links to the office list
* Update the new/edit form to match existing design
* Update the tests
[delivers #97512326]

Managers update office jurisdictions

---

app/views/guide/index.html.md

Updated guide with info about evidence no longer being needed for R1

Removal of R1 evidence

---

Dockerfile
app/controllers/static_controller.rb
app/views/static/400.html.slim
app/views/static/404.html.slim
app/views/static/500.html.slim
app/views/static/503.html.slim
config/routes.rb
lib/tasks/static_pages.rake
spec/controllers/static_controller_spec.rb

* Static view controller
* Error pages
* Rake task to export error pages
Alex: I've added the static controller examples for the page, just to prevent any regressions if anything is tweaked further down the line

Static error pages

---

lib/tasks/static_pages.rake

Fix mistake in output of static pages. Need to overwrite the pages in
/public.

Static pages output to public

---

app/views/guide/index.html.md

Heading text was changed, updated TOC to match

Fixed link in guide TOC

---

.travis.yml

Heroku security updated and invalidated API key
Refreshed and updated

updated API key

---

spec/controllers/users_controller/admin_user_spec.rb
spec/controllers/users_controller/manager_user_spec.rb
spec/controllers/users_controller/standard_user_spec.rb
spec/factories/jurisdictions.rb

Aiming to prevent intermittent test errors on names
* Update tests to ensure fake data with apostrophe
is escaped the same as the page
* Improve generation of fake data
* Delete stored faked data before certain suites to prevent
duplicate creation (belt and braces)

Update test suite

---

app/controllers/users_controller.rb
spec/controllers/users_controller/manager_user_spec.rb

* ensure that managers can access staff in their office

Update user controller

---

app/views/users/edit.html.slim
spec/controllers/users_controller/admin_user_spec.rb
spec/controllers/users_controller/manager_user_spec.rb

Update the styles of the edit user view
* Radio buttons should be used in preference to 
drop downs for small choices
* Field widths should be standardised across the
site

Update user style

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/models/dwp_check.rb
app/models/user.rb
app/views/users/show.html.slim
db/migrate/20150709131316_add_deleted_at_to_users.rb
db/schema.rb
spec/controllers/users_controller/admin_user_spec.rb
spec/models/dwp_check_spec.rb
spec/models/feedback_spec.rb
spec/models/office_spec.rb
spec/models/user_spec.rb

As per subject: 'soft delete' users, but don't remove them from the database.

Soft delete users

---

app/views/users/show.html.slim
spec/views/users/show.html.slim_spec.rb

Standard users should not see links to:
* delete their own account
* view the list of all users

Hide links from standard user

---

spec/factories/jurisdictions.rb

correctly apply number to name rather than class

Updated jurisdiction factory

---

app/views/users/edit.html.slim

* correctly align role
and jurisdiction checkboxes

Fix edit view

---

app/assets/stylesheets/result_tables.scss
app/views/calculator/_work_out.slim
app/views/offices/show.html.slim
app/views/users/show.html.slim

After the HR-fix from last week, there were some tables
that were not updated.
* fixed views
* updated style to match hide top that was used previously

Update table styles

---

db/seeds.rb

Feedback from Maia in 20-Jul-2015 demo

Update seed data

---

app/assets/javascripts/application.js
app/assets/javascripts/radio_buttons.coffee
app/assets/javascripts/show_hide_checkboxes.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/errors.scss
app/assets/stylesheets/summary.scss
app/controllers/applications/build_controller.rb
app/models/application.rb
app/views/applications/build/application_details.html.slim
app/views/applications/build/personal_information.html.slim
app/views/applications/build/summary.html.slim
config/initializers/date_time.rb
config/locales/en.yml
db/migrate/20150721114357_add_page2_fields_to_application.rb
db/schema.rb
spec/factories/applications.rb
spec/models/application_spec.rb

* add fields to schema and models
* update factory
* update controller

Application form page 2 handler

---

app/assets/javascripts/application.js
app/assets/javascripts/radio_buttons.coffee
app/assets/javascripts/show_hide_checkboxes.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/errors.scss
app/assets/stylesheets/summary.scss
app/controllers/applications/build_controller.rb
app/models/application.rb
app/views/applications/build/application_details.html.slim
app/views/applications/build/personal_information.html.slim
app/views/applications/build/summary.html.slim
config/initializers/date_time.rb
config/locales/en.yml
db/migrate/20150721114357_add_page2_fields_to_application.rb
db/schema.rb
spec/factories/applications.rb
spec/models/application_spec.rb

* expand the application model to validate fields
* create view to handle input
* create a summary page to display the entered data

Application form page 1 handler

---

app/views/static/400.html.slim
app/views/static/404.html.slim
app/views/static/500.html.slim
app/views/static/503.html.slim

Updated maintenance pages with the copy as done by Leigh:
https://www.pivotaltracker.com/story/show/97121512
The pages 400 & 404 are the same, but leaving them as 'duplicate' just
in case that they might change in the future.

The maintenance pages

---

app/controllers/applications/build_controller.rb
app/models/application.rb
app/views/applications/build/benefits.html.slim
config/locales/en.yml
db/migrate/20150730091719_add_benefits_column_to_application.rb
db/schema.rb
spec/controllers/applications/build_controller_spec.rb
spec/factories/applications.rb
spec/models/applications/step_4_spec.rb

Implemented the **Benefits** page.

Fourth page

---

app/assets/stylesheets/application_form.scss
app/views/applications/build/summary.html.slim
config/locales/en.yml

* added tick/cross to pass fail
* coloured the results
* refactored the display to remove ternary checks

Updated summary page

---

app/controllers/applications/build_controller.rb

Moved the params into paged arrays and flattened
in the call, to allow better legibility of the list.

Refactored application params

---

app/assets/stylesheets/base.scss
app/views/applications/build/benefits.html.slim
app/views/applications/build/personal_information.html.slim
config/locales/en.yml
spec/models/applications/step_1_spec.rb

en.yml structure clarified
* updated views stop use new structures
* added details/summary to benefits page
* tidied css for panel indent on benefit page

Updated locale file

---

app/views/applications/build/application_details.html.slim

* Added panel-indent to expandable sections
The indentation makes the top change look huge...
it really isn't

Updated page 2

---

app/views/layouts/application.html.slim

ensure consistent appearance with Sign out link

Update sign-in link css

---

app/assets/stylesheets/base.scss
app/views/applications/build/application_details.html.slim
app/views/calculator/_work_out.slim
app/views/dwp_checks/show.html.slim
app/views/offices/edit.html.slim
app/views/offices/show.html.slim
app/views/users/sessions/new.html.slim
app/views/users/show.html.slim

One of the css styles was spelled inconsistently
* update the style name
* add the style to one row
* update all views that referenced the old name

Update style name

---

app/views/applications/build/summary.html.slim

Update to apply correct locale label

Update summary page

---

Gemfile
Gemfile.lock
app/views/applications/build/application_details.html.slim
app/views/applications/build/savings_investments.html.slim
app/views/applications/build/summary.html.slim
config/application.rb
config/locales/devise.en.yml
config/locales/devise_invitable.en.yml
config/locales/en.yml

Locale was set to en.
This meant that currency was formatting as $, etc.
Set locale to en-GB and update views to show currency in UK format.

Locale change

---

app/views/users/edit.html.slim
app/views/users/invitations/new.html.slim
app/views/users/passwords/edit.html.slim
app/views/users/passwords/new.html.slim
app/views/users/registrations/edit.html.slim
app/views/users/shared/_change_password.html.slim

Update user views inline with new error styling.
These were created before the:
Label
Error
Input
pattern was implemented

Style update users

---

app/views/applications/build/application_details.html.slim

* resolve display error when fee empty

Minor application form fix

---

app/assets/javascripts/application.js
app/assets/javascripts/checkbox_module.coffee
app/assets/javascripts/radio_buttons_module.coffee
app/assets/javascripts/show_hide_checkboxes.coffee
spec/javascripts/checkbox_module_spec.coffee
spec/javascripts/r2_calculator_spec.coffee
spec/javascripts/radio_buttons_module_spec.coffee

Improved handling of checkbox and radio states
* apply selected class when selected(!)
* ensure that choices are displayed when page loads

Checkbox handling

---

app/models/user.rb
spec/models/user_spec.rb

Allow the invitation of users with hmcourts-service emails

Update email domain

---

app/assets/stylesheets/dwp_checks.scss
app/controllers/applications/build_controller.rb
app/models/application.rb
app/models/benefit_check.rb
app/services/benefit_check_service.rb
app/views/applications/build/benefits_result.html.slim
app/views/applications/build/summary.html.slim
app/views/applications/partials/_deceased.html.slim
app/views/applications/partials/_no.html.slim
app/views/applications/partials/_server_unavailable.slim
app/views/applications/partials/_superseded.html.slim
app/views/applications/partials/_undetermined.html.slim
app/views/applications/partials/_unspecified_error.html.slim
app/views/applications/partials/_yes.html.slim
app/views/applications/partials/base/_does_not_match.html.slim
app/views/applications/partials/base/_dwp_check.html.slim
app/views/applications/partials/base/_error.html.slim
config/locales/en.yml
db/migrate/20150805100242_create_benefit_check.rb
db/schema.rb
spec/controllers/applications/build_controller_spec.rb
spec/factories/applications.rb
spec/factories/benefit_checks.rb
spec/features/applications/benefit_results_are_rendered_spec.rb
spec/models/application_spec.rb
spec/models/applications/benefits_result_spec.rb
spec/models/applications/personal_information_spec.rb
spec/services/benefit_check_service_spec.rb

When all of the required fields are completed and the 
application is saved, it will : 
* check that all fields are valid
* check that the fields are different from any previous check
and then fire off a request to the DWP.
This should be held until the income calculator is complete

Add benefit checks and views to application form

---

app/views/home/index.html.slim
app/views/users/show.html.slim

A css style was renamed, these references needed to be updated

Update css references

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/unicorn.rb
run.sh

Because we use docker in prod it makes sense to log to stdout and ship
from there.

Point logs to STDOUT

---

app/assets/javascripts/income_calculator.coffee
app/views/dwp_checks/show.html.slim

In line with design - added ticks and crosses to 
dwp check and income calculator results

Updated result bars with ticks and crosses

---

app/views/applications/build/application_details.html.slim
app/views/applications/build/personal_information.html.slim
config/locales/en.yml

So that users can tell what fields are optional.

Add optional field to title

---

app/models/application.rb
app/views/applications/build/summary.html.slim
app/views/applications/partials/_deleted.html.slim
config/locales/en.yml
spec/controllers/applications/build_controller_spec.rb
spec/models/application_spec.rb
spec/models/applications/benefits_result_spec.rb
spec/models/applications/benefits_spec.rb

Improve handling of benefits choice
* route properly to summary if savings threshold exceeded
* Improve the summary page to properly display messages
* add a deleted view for when DWP result is deleted
* improve last_benefit_check to get most recently generated!

Improve benefits summary

---

app/views/users/edit.html.slim
app/views/users/index.html.slim
app/views/users/show.html.slim

* previously it would be lower cased
* now they are capitalised

Make sure role is displayed correctly

---

Gemfile
Gemfile.lock
app/builders/application_builder.rb
app/controllers/applications/build_controller.rb
app/controllers/offices_controller.rb
app/models/office.rb
app/models/reference.rb
app/views/offices/_form.html.slim
app/views/offices/show.html.slim
config/application.rb
db/migrate/20150824114515_create_references.rb
db/migrate/20150824134632_add_entity_code_to_office.rb
db/migrate/20150826083807_remove_secure_random_and_reference_hash_from_reference.rb
db/migrate/20150826083936_add_reference_to_reference.rb
db/schema.rb
db/seeds.rb
spec/builders/application_builder_spec.rb
spec/factories/offices.rb
spec/factories/references.rb
spec/features/office_management_spec.rb
spec/features/user_invite_spec.rb
spec/models/office_spec.rb
spec/models/reference_spec.rb

Implemented reference number creation for the application.
Pivotal tickets:
https://www.pivotaltracker.com/story/show/93435558

Reference number

---

app/controllers/applications/build_controller.rb
app/models/application.rb
app/views/applications/build/confirmation.html.slim
app/views/applications/build/summary.html.slim
spec/controllers/applications/build_controller_spec.rb
spec/factories/applications.rb
spec/features/applications/application_form_stories_spec.rb
spec/features/applications/confirmation_is_rendered_spec.rb
spec/models/applications/income_spec.rb

Add the confirmation page to the application form
* add the validation and tests to ensure correct function
* extend the existing tests to cover new functionality

Confirmation page

---

config/locales/en.yml

Copy changes as per Kellies design in:
https://www.pivotaltracker.com/story/show/103078866

Copy changes on the 'savings & investments' page

---

app/views/applications/build/savings_investments.html.slim
config/locales/en.yml

Copy changes done as per ticket:
https://www.pivotaltracker.com/story/show/103078866

Further copy changes on 'Savings & Investment'

---

app/models/application.rb
spec/features/applications/application_savings_and_investments_spec.rb
spec/features/applications/change_from_r1_to_r2_spec.rb

See [Defect : Application form processing changing from R2 to R1 shows incorrect result](https://www.pivotaltracker.com/story/show/102991658)
[delivers #102991658]

Fix for r2 to r1 application forms

---

app/models/application.rb
lib/fee_threshold.rb
spec/lib/fee_threshold_spec.rb

[Ticket:#103489954](https://www.pivotaltracker.com/story/show/103489954)

Fee threshold fix

---

app/views/applications/build/benefits_result.html.slim
app/views/applications/build/personal_information.html.slim
config/locales/en.yml
spec/features/applications/benefit_results_are_rendered_spec.rb

Improve benefit journey when ni missing

---

Gemfile
Gemfile.lock
app/controllers/health_status_controller.rb
config/routes.rb
spec/controllers/health_status_controller_spec.rb

Also add a raise exception method to test the capture.

Add sentry to capture exceptions.

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/offices_controller.rb
app/controllers/users_controller.rb
app/models/office.rb
app/services/manager_setup.rb
app/views/offices/_form.html.slim
config/locales/en.yml
spec/controllers/home_controller_spec.rb
spec/controllers/offices_controller_spec.rb
spec/controllers/users_controller/manager_user_spec.rb
spec/factories/office_jurisdictions.rb
spec/factories/offices.rb
spec/features/manager_out_of_the_box_experience_spec.rb
spec/models/office_spec.rb
spec/services/manager_setup_spec.rb

This implements a workflow for manager's first time login, when they have to setup their office and personal preferences.
It also makes jurisdictions required for an office, which has an impact on the UI and also internal structure.

Out of the box experience

---

app/controllers/applications/build_controller.rb
app/models/forms/income.rb
app/views/applications/build/income.html.slim
config/locales/en.yml
spec/models/forms/income_spec.rb

Refactor of **income** page into a form object, in order to get away from the monolithic **Application** model.

Income refactor

---

app/models/application.rb
app/models/forms/savings_investment.rb
app/services/partner_age_check.rb
app/views/applications/build/savings_investments.html.slim
config/locales/en.yml
db/migrate/20151002094114_rename_over61.rb
db/schema.rb
spec/controllers/applications/build_controller_spec.rb
spec/models/applications/savings_investments_spec.rb
spec/models/forms/savings_investment_spec.rb
spec/services/partner_age_check_spec.rb
spec/support/personae.rb

Rename application model's attribute **over_61** to **partner_over_61** as the new name reflects what value it holds

Rename over 61

---

app/assets/stylesheets/base.scss
app/views/applications/build/benefits.html.slim
app/views/applications/build/income_result.html.slim
app/views/applications/build/savings_investments.html.slim
app/views/applications/partials/base/_does_not_match.html.slim
app/views/applications/partials/base/_dwp_check.html.slim
app/views/calculator/_work_out.slim
app/views/dwp_checks/show.html.slim
app/views/home/_manager.html.slim
app/views/home/index.html.slim
app/views/users/sessions/new.html.slim

Updated style to reference a span inside the summary
updated the views to have the required span

Updated arrow display for firefox

---

app/assets/javascripts/applicants_partner_over_61.coffee
app/assets/javascripts/application.js
app/views/applications/build/savings_investments.html.slim
spec/features/applications/savings_and_investment_partner_over_61_checkbox_spec.rb

Removed JavaScript from the view on Savings and Investments page.
Just cleaning up...

Remove js from view

---

config/locales/en.yml

[Ticket #100305786](https://www.pivotaltracker.com/story/show/100305786) 
Edit office screen should display name of office

Display Name of office on edit screen

---

app/models/evidence/forms/evidence.rb
spec/models/evidence/forms/evidence_spec.rb

Created a model which will handle the evidence form values and their
validation.

Created Evidence form object

---

app/views/evidence/accuracy.html.slim
config/locales/en.yml
spec/features/evidence/evidence_check_flow_spec.rb

Moved to locale file for labels
Switched input to text-area
Updated foundation use for optional panel

Updated accuracy page

---

app/models/evidence/forms/income.rb
spec/models/evidence/forms/income_spec.rb

I'll use the form object implemented here for the page 4. in the prototype.

Evidence income form view

---

app/views/evidence/show.html.slim

Despite looking okay on screen the alignments were breaking
the DOM.  Pulled all sections back to the left margin to fix
the weird outdenting.

Updated summary view

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/evidence.scss
app/controllers/evidence_controller.rb
app/views/evidence/_confirmation_none_remission.html.slim
app/views/evidence/_confirmation_part_remission.html.slim
app/views/evidence/confirmation.html.slim
config/locales/en.yml
config/routes.rb
spec/controllers/evidence_controller_spec.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/routing/evidence_routing_spec.rb

Still not polished, as it doesn't have the view object for passing in the data for the views cleanly.
But apart from that, mostly done.

Evidence confirmation

---

app/views/layouts/application.html.slim

Bug fix, as per Leigh's ticket:
https://www.pivotaltracker.com/story/show/105323540

Renamed the app from the old to the new name

---

app/views/users/index.html.slim
spec/features/list_users_with_email_spec.rb

List email addresses of the users so that it's easier for Jiten to
search for users based on their email address.

Added email addresses to User#index view

---

config/locales/en.yml

Updated the amber banner for applications chosen to have evidence checked.

Updated evidence results message

---

config/settings.yml

Inline with decision of HMCTS project board

Increased evidence check to 14 days

---

app/views/users/mailer/reset_password_instructions.html.slim
app/views/users/mailer/reset_password_instructions.text.slim
config/locales/devise.en.yml

[delivers #103519722]
* updated wording in locale file
* changed html email to output url rather than link
* created plain text version of email

Updated reset password email

---

app/views/users/mailer/invitation_instructions.html.slim
app/views/users/mailer/invitation_instructions.text.slim
config/locales/devise.en.yml
config/locales/devise_invitable.en.yml

[delivers #105118410]
* updated wording in locale file
* changed html email to output url rather than link
* created plain text version of email

Updated sign-up email

---

config/settings.yml

The bug raised in this ticket:
https://www.pivotaltracker.com/story/show/100752692

Bug fix: changed the no-reply email for prod

---

app/assets/stylesheets/evidence.scss
app/controllers/payments_controller.rb
app/models/payment.rb
app/views/payments/_failed_letter.html.slim
app/views/payments/confirmation.html.slim
app/views/payments/summary.html.slim
config/locales/en.yml
config/routes.rb
db/migrate/20151016153328_add_completed_to_payment.rb
db/schema.rb
spec/controllers/payments_controller_spec.rb
spec/features/payments/payments_flow_spec.rb

The last bit of the payment journey.

Payment confirmation

---

db/seeds.rb

This allows branch builder boxes to have
standard login for all levels of access

Added Manager to seed data

---

app/models/application.rb
spec/features/evidence/applications_awaiting_evidence_are_displayed_on_dashboard_spec.rb
spec/models/application_spec.rb

Ensure evidence_checks are not displayed on
the front page once they have been completed

Update application scope

---

app/assets/stylesheets/base.scss
app/views/home/index.html.slim

Add the manager partial inside an accordion,
this allows admins to access the manager pane as well
as see the graphs, with the graphs set to default.

Quick fix for admin dashboard

---

app/assets/javascripts/guide.js
app/views/guide/evidence_checks.html.slim
app/views/guide/index.html.slim
app/views/guide/process_application.html.slim
app/views/guide/suspected_fraud.html.slim
app/views/home/_manager.html.slim
app/views/home/_user.html.slim
app/views/home/index.html.slim

Guide amends

---

app/views/shared/_footer.slim
config/settings.yml
spec/views/shared/_footer.slim_spec.rb

* updated the email address to remove feedback
* changed the feedback link in the footer to a
mail link for a logged out user
[finishes #106129810]

Updated feedback

---

app/views/home/_manager.html.slim
config/locales/en.yml
spec/views/home/index.html.slim_spec.rb

The waiting tables for evidence and payments were removed for managers
This returns them and [finishes #106288698]

Return waiting tables for managers

---

app/models/benefit_check.rb
app/models/r2_calculator.rb

Each model had a check_by_day scope, this already existed in
the CommonScope object.  I removed the Object specific scope
and ensured CommonScope was included.

Remove duplicated scope

---

app/models/applicant.rb
app/models/application.rb
spec/models/applicant_spec.rb
spec/models/application_spec.rb

* refactored into the applicant model
* test for leap year correct response
* test for delegation to applicant model
[ticket](https://www.pivotaltracker.com/story/show/106838812)
[finishes #106838812]

Released fix for leap year bug

---

app/models/applikation/forms/personal_information.rb

This will reduce the code duplication warning in coedclimate
and increase the file from an B to an A, an improve the GPA

Update personal_information form

---

Gemfile
Gemfile.lock
config/initializers/secret_token.rb
spec/lib/secret_token_spec.rb

Fix for:
https://codeclimate.com/github/ministryofjustice/fr-staffapp/coverage/5630b3ab7e0ef617240801d9

Env var test coverage

---

spec/lib/secret_token_spec.rb

This is the failure:
https://travis-ci.org/ministryofjustice/fr-staffapp/builds/88100149
and this change fixes it.

Fix for RuboCop violation

---

spec/javascripts/income_spec.coffee

It was not clearing the element after each test, the tests were
still passing, but the page was being extended on each test

Fixed minor bug in income_spec

---

app/views/payments/accuracy.html.slim
app/views/payments/confirmation.html.slim

https://www.pivotaltracker.com/story/show/103177818

payment guides added

---

app/models/query/waiting_for_base.rb
app/models/query/waiting_for_evidence.rb
app/models/query/waiting_for_payment.rb

Implemented a base class with the shared code.
Each query calls the super method using the 
symbol for the required attribute and extracting the 
database field name in the method.

Refactored waiting_for queries

---

app/models/applikation/forms/application_detail.rb

This was to improve the code-climate rating from a D
Removed:
* duplication in validation rules by adding date constants
* options block for single validation of refund field

Refactor Forms::ApplicationDetail

---

app/views/payments/accuracy.html.slim
db/schema.rb

added missing guides link

---

app/views/payments/confirmation.html.slim

fixed weird layout

---

app/views/evidence/confirmation.html.slim
app/views/evidence/result.html.slim
app/views/evidence/show.html.slim
app/views/evidence/summary.html.slim
db/schema.rb

pivotal https://www.pivotaltracker.com/story/show/105859572

confirmation page and some changes

---

app/views/evidence/result.html.slim

updated guidance

---

app/views/evidence/accuracy.html.slim
app/views/shared/forms/_accuracy.html.slim
config/locales/en.yml
spec/features/evidence/evidence_check_flow_spec.rb

Removed evidence check bullets

Updated copy on evidence check bullets

---

app/models/applikation/forms/application_detail.rb
spec/models/applikation/forms/application_detail_spec.rb

Following this morning's quick reversion of the previous refactoring 
code, this is another attempt at refactoring the application detail to 
remove the duplication.
Interested to discuss the pros and cons of the following
* 3.months.ago vs Time.zone.today - 3.months
* TIME_LIMIT_FOR_PROBATE.years.ago vs
Time.zone.today - TIME_LIMIT_FOR_PROBATE.years

Re-refactor application_detail

---

config/locales/en.yml

To reduce white space on the letter

Replace <p> with <div> on evidence letter

---

app/models/applikation/forms/application_detail.rb
config/locales/en.yml
spec/models/applikation/forms/application_detail_spec.rb

Also, refactored some of the tests to use the
subject-result constructs.

Add explicit tests for refund dates

---

app/models/query/processed_applications.rb
spec/factories/applications.rb
spec/models/query/processed_applications_spec.rb

* updated query to only include applications where completed_at is set
* extended tests
* created appropriate factory

Updated processed applications

---

app/controllers/evidence_controller.rb
spec/controllers/evidence_controller_spec.rb

Because only the authenticated users should have access to this
controller and its actions.

Added authentication for Evidence controller

---

app/models/views/processing_details.rb
spec/models/views/processing_details_spec.rb

Ignore processed_by name

---

app/views/guide/evidence_checks.html.slim
app/views/guide/index.html.slim
app/views/guide/process_application.html.slim

Updated the way letters are referred to
Updated part-payments (with hyphen) on guides home page

Content update letters

---

lib/log_stuff.rb

* refactored the log method to reduce the complexity  
* spread the single method into three parts

Updated log_stuff

---

README.md

Added a setup run task that will allow the database to be configured properly for *new* branches
Updated the readme to update qt4 references to qt5

Branch builder fixes

---

db/migrate/20151119112949_add_decision_fields_to_application.rb
db/schema.rb

This will allow new code to set the values.
Meanwhile, a separate PR will be added to
migrate the data for existing, complete, records.

Add decision fields to application

---

app/controllers/part_payments_controller.rb
spec/services/resolver_service_spec.rb

Tested all the outcomes for EvidenceCheck when resolved via
ResolverService.

Tested all the outcomes for EvidenceCheck

---

app/views/guide/evidence_checks.html.slim

See https://www.pivotaltracker.com/story/show/108851

Updated evidence check guide

---

app/controllers/part_payments_controller.rb
app/services/resolver_service.rb
app/views/part_payments/return_letter.html.slim
app/views/part_payments/show.html.slim
config/locales/en.yml
config/routes.rb
db/migrate/20151120112749_add_outcome_to_part_payment.rb
db/schema.rb
spec/controllers/part_payments_controller_spec.rb
spec/features/return_applications/return_part_payment_applications_spec.rb
spec/services/resolver_service_spec.rb
spec/support/resolver_service_common.rb

Return PartPayments using the ResolveService

Return part payment applications

---

app/assets/stylesheets/base.scss
app/views/applications/process/application_details.html.slim
app/views/applications/process/personal_information.html.slim
config/locales/en.yml

Consolidated front-end changes
* Added the date hint text
* Deleted the Hint text spans from the page
* Updated the yml file to add _html suffix to the optional
label, this removes need from putting html safe on view
* removed span.hint css
* updated the date hint text to point at the correct label

Front-end changes

---

app/models/query/waiting_for_base.rb
app/views/home/_waiting_applications.html.slim
config/locales/en.yml
spec/models/query/waiting_for_evidence_spec.rb
spec/models/query/waiting_for_part_payment_spec.rb

Instead of displaying `Expires at` we now display `Date processed`. Also the list is ordered by the processed date of the application from eldest to newest.

Use date processed on waiting applications list

---

app/models/views/processing_details.rb
spec/models/views/processing_details_spec.rb

It was causing an error on applications which were not completed.

Return nil when completed_at is missing

---

app/views/users/sessions/new.html.slim

[finishes #107394496]
@kelliematheson [Ticket](https://www.pivotaltracker.com/story/show/107394496)

Added Forgot Password link to sign in page

---

app/views/home/_manager.html.slim
app/views/layouts/application.html.slim
spec/views/home/index.html.slim_spec.rb

* removed from the manager's home page
* removed home page tests
[finishes #105864428]
@kelliematheson [ticket](https://www.pivotaltracker.com/story/show/105864428)

Moved manager links to top bar

---

app/views/evidence/_confirmation_none_remission.html.slim
app/views/evidence/_confirmation_part_remission.html.slim
app/views/evidence/_confirmation_return_remission.html.slim
app/views/evidence/return_letter.html.slim
app/views/evidence_checks/show.html.slim
app/views/part_payments/_failed_letter.html.slim
app/views/part_payments/return_letter.html.slim
config/application.rb
config/locales/en.yml
config/locales/letters_en.yml
spec/features/evidence/evidence_check_flow_spec.rb

This will simplify the main YML document and make it easier 
for the content team to manage the letters in isolation.

Move letters into separate YML file

---

config/locales/en.yml

* Removed the duplicate date_of_death section
* Added translation for date_of_death after after_or_equal_to
Addresses [Ticket](https://www.pivotaltracker.com/story/show/109614742)
[finishes #109614742]

Updated probate locale section

---

app/views/users/show.html.slim

This was left behind after a shuffling of the form

removed "label" text from staff view

---

app/controllers/reports_controller.rb
spec/controllers/reports_controller_spec.rb

* updated the tests for CSV output
* refactored the css generation

Improving code-climate test coverage

---

app/views/applications/process/confirmation.html.slim

Update column layout of confirmation page

---

app/controllers/offices_controller.rb
app/models/jurisdiction.rb
app/models/office.rb
app/views/offices/_form.html.slim
spec/features/manager_bec_details_spec.rb
spec/features/manager_out_of_the_box_experience_spec.rb
spec/views/offices/edit.html.slim_spec.rb
spec/views/offices/new.html.slim_spec.rb

Added the BEC to show on the checkboxes when editing the office.

Show BEC on office edit view

---

app/assets/stylesheets/evidence_check.scss
app/views/home/_processed_and_deleted_aplications.html.slim
config/locales/en.yml
spec/features/processed_applications/list_deleted_applications_spec.rb
spec/features/processed_applications/list_processed_applications_spec.rb
spec/views/home/index.html.slim_spec.rb

[Pivotal](https://www.pivotaltracker.com/story/show/110953768)
Before
---
After:
---

UI changes for completed applications on homepage

---

.travis.yml

After updating the app to 2.3.0, this synchronises travis to use it too.

Updated .travis.yml to rvm 2.3.0

---

app/views/home/index.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/110951470)
Before
---
After
---
Note the Process application panel is now butted up to the black bar. I'm going to have a little tidy up through some of the templates in a separate PR coming shortly. 👌

remove welcome banner

---

app/views/guide/process_application.html.slim
app/views/shared/processed_and_deleted/_index.html.slim

a couple of spacing issues missed out on the first pass

fixup spacing part 2

---

app/assets/stylesheets/utilities.scss
app/views/evidence/show.html.slim
app/views/part_payments/show.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/111971295)
Before
---
After
---

spacing for show/hide panels

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/foundation_and_overrides.scss
app/assets/stylesheets/navigation.scss
app/views/layouts/application.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/104901852)
Large screen
---
Before
After
(no change)
Medium screen
---
Before
After
Small screen - nav closed
---
Before
After
Small screen - nav open
---
Before
After

stop top nav breaking weirdly on small screens

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/result_tables.scss
app/controllers/business_entities_controller.rb
app/helpers/flash_message_helper.rb
app/policies/business_entity_policy.rb
app/services/business_entity_service.rb
app/views/business_entities/confirm.html.slim
app/views/business_entities/deactivate.html.slim
app/views/business_entities/index.html.slim
config/locales/en.yml
config/routes.rb
spec/controllers/business_entities_controller_spec.rb
spec/features/admin_can_maintain_business_entities_spec.rb
spec/policies/business_entity_policy_spec.rb
spec/routing/business_entities_routing_spec.rb
spec/services/business_entity_service_spec.rb

This is the technical implementation of the delete/deactivate feature.
Content updates may need a separate PR when terminology is agreed.

Deactivate Business Entity codes

---

app/views/evidence/show.html.slim
app/views/guide/evidence_checks.html.slim
app/views/guide/part_payments.html.slim
app/views/part_payments/show.html.slim
spec/features/return_applications/return_evidence_checkable_applications_spec.rb

Changes to processing applications waiting  for part-payment and evidence

Staff guide updates

---

app/policies/base_policy.rb
app/policies/office_policy.rb
app/views/business_entities/index.html.slim
spec/policies/office_policy_spec.rb

A quick fix of user permissions and broken link from BEC page.

Fix permissions

---

app/helpers/flash_message_helper.rb
spec/helpers/flash_message_helper_spec.rb

Added forgotten mailto: to link

Update BEC index

---

app/models/forms/application/applicant.rb
config/locales/en.yml
spec/models/forms/application/applicant_spec.rb
spec/models/forms/application/detail_spec.rb

Working with @leighmoney to update application
Updated tests to match

Update error messages

---

app/assets/stylesheets/errors.scss
app/views/home/index.html.slim
config/locales/en.yml

Set a manual message to show the DWP service has been restored.

Set DWP fixed message

---

app/models/views/reports/finance_report_data_row.rb
spec/models/views/reports/finance_report_data_row_spec.rb

After a refactor a comma was left in a word array. :/

Fixed word array

---

app/views/applications/process/application_details.html.slim

User pointed out the mis-spelling of received on the label

fixed spelling mistake

---

app/views/guide/process_application.html.slim

Listed at bottom of staff processing guide

Added jost contact emails

---

app/builders/finance_report_builder.rb
spec/builders/finance_report_builder_spec.rb

Change finance report

---

db/migrate/20160308155249_add_online_application_tables.rb
db/schema.rb

I'm creating this PR just to be able to easily see changes and have a discussion. Not to be merged yet.

Create online data store

---

app/models/online_application.rb
spec/factories/online_applications.rb
spec/models/online_application_spec.rb

The model only contains basic validation, based on the decided database
structure.

Create OnlineApplication and its factory

---

app/controllers/home_controller.rb
app/controllers/online_applications_controller.rb
app/models/forms/online_application.rb
app/models/online_application.rb
app/policies/online_application_policy.rb
app/views/online_applications/edit.html.slim
config/locales/en.yml
config/routes.rb
db/migrate/20160312100207_add_details_to_online_application.rb
db/schema.rb
spec/controllers/home_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/features/online_applications/staff_can_add_details_spec.rb
spec/features/online_applications/staff_can_search_for_online_application_spec.rb
spec/models/forms/online_application_spec.rb
spec/models/online_application_spec.rb
spec/policies/online_application_policy_spec.rb

Second page of the online applications flow, which is the edit page. Staff should add details to the existing data, before they can complete processing of it.

Online applications editting

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/panels.scss
app/controllers/home_controller.rb
app/controllers/online_applications_controller.rb
app/models/forms/online_application.rb
app/models/forms/search.rb
app/models/online_application.rb
app/policies/online_application_policy.rb
app/views/home/index.html.slim
app/views/online_applications/edit.html.slim
app/views/online_applications/show.html.slim
config/locales/en.yml
config/routes.rb
db/migrate/20160312100207_add_details_to_online_application.rb
db/schema.rb
spec/controllers/home_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/factories/online_applications.rb
spec/features/online_applications/staff_can_add_details_spec.rb
spec/features/online_applications/staff_can_search_for_online_application_spec.rb
spec/models/forms/online_application_spec.rb
spec/models/forms/search_spec.rb
spec/models/online_application_spec.rb
spec/policies/online_application_policy_spec.rb
spec/views/home/index.html.slim_spec.rb

This is the main PR for the whole online applications flow. Other PRs are going to be merged to this one eventually. 
Waiting for #617 to be reviewed / merged and than this branch should be rebased on `master`.

Dashboard for online applications

---

config/locales/en.yml

DD/MM/YYYY isn't an example date, it's the date format.

update date hint text

---

app/assets/javascripts/application.js
app/assets/javascripts/fee_field.js
app/assets/stylesheets/errors.scss
app/assets/stylesheets/form_elements.scss
app/assets/stylesheets/utilities.scss
app/views/applications/process/application_details.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/114557909)

show warning message when fee too high

---

app/views/guide/process_application.html.slim

Updated with info about delete function and multiple claimants

Guide additions 160316

---

.rubocop.yml
app/builders/online_application_builder.rb
app/controllers/api/submissions_controller.rb
app/services/hwf_reference_generator.rb
config/routes.rb
config/settings.yml
spec/builders/online_application_builder_spec.rb
spec/controllers/api/submissions_controller_spec.rb
spec/factories/public_app_submissions.rb
spec/routing/online_applications_routing_spec.rb
spec/services/hwf_reference_generator_spec.rb

Include routing and return value tests
This will become a root branch for other features to merge into.

Add the API endpoint for publicapp submissions

---

app/builders/application_builder.rb
app/controllers/online_applications_controller.rb
app/models/application.rb
app/policies/online_application_policy.rb
app/services/application_calculation.rb
app/services/resolver_service.rb
app/views/online_applications/show.html.slim
config/routes.rb
db/migrate/20160324110832_add_online_application_reference_to_application.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/factories/online_applications.rb
spec/features/online_applications/staff_can_complete_processing_spec.rb
spec/models/application_spec.rb
spec/policies/online_application_policy_spec.rb
spec/services/application_calculation_spec.rb
spec/services/resolver_service_spec.rb

This finishes the online applications journey by allowing the staff to complete processing. They should get relevant result and the same confirmation page as paper based applications.

Complete online application

---

app/assets/stylesheets/form_elements.scss
app/views/users/sessions/new.html.slim

Stop fooling Firefox's password manager

fix firefox password amnesia

---

app/controllers/home_controller.rb
app/views/home/index.html.slim
spec/controllers/home_controller_spec.rb

Minor tweaks for staff searches
* upper case the search string (prevents hwf-abc-123 not found, when HWF-ABC-123 exists)
* turn off auto-complete on the search field
[finishes #116868539]

Search update

---

app/services/dwp_monitor.rb
spec/services/dwp_monitor_spec.rb

During a recent outage this error message needs tracking too.

Update the DWP monitor to check for Server broke connection messages too

---

lib/tasks/trial_production_migration.rake

For the moment it's rake tasks to support the migration, but it may be more if needed.

Support for trial -> production migration

---

app/services/dwp_monitor.rb

Fix DWP monitor for trial

---

app/views/guide/process_application.html.slim

For domestic violence & insolvency

Updates to guidance

---

app/assets/stylesheets/local/inputs.scss

restyle currency input

---

app/models/user.rb

I decided to just go ahead with the existing regexp solution. I started making it more generic and configurable, but then I decided not to pollute the codebase with unnecessary complexity.

Allow justice.gsi.gov.uk users to register

---

app/services/hwf_reference_generator.rb

Replace hex references with an extended character set with no
ambiguities. "3 4 6 7 9 A C D E F G H J K L M N P Q R T V W X Y"
The new algorithm delivers collisions at about 1:10,000
Created | Time taken (sec) | Collisions | Percent
:-----: | ---------: | :--------: | :-----:
10,000 | 0.04 | 1 | 0.01%
100,000 | 0.4 | 21 | 0.02%
1,000,000 | 5.1 | 2080 | 0.21%
7,000,000 | 43.0 | 98586 | 1.41%
Obviously, that will increase over time but it seems acceptable for now.
Algorithm based on speed tests done [here](http://goo.gl/QwVedv) and [here](http://codereview.stackexchange.com/a/15997)

Update HWF reference generator

---

app/controllers/reports_controller.rb
app/models/views/reports/public_submission_data.rb
app/policies/report_policy.rb
app/views/reports/index.html.slim
app/views/reports/public.html.slim
config/routes.rb
spec/controllers/reports_controller_spec.rb
spec/factories/applications.rb
spec/factories/online_applications.rb
spec/models/views/reports/public_submission_data_spec.rb
spec/policies/report_policy_spec.rb

[Pivotal ticket](https://www.pivotaltracker.com/story/show/117995369)
Surface data from public submissions to admin users.
Display total completed all time + last 7 days
Display processed by court, all time + last 7 days
Work in progress
===
Time taken to between online submission and application processed

Trial dashboard

---

.env.development
.env.test
Dockerfile
Gemfile
Gemfile.lock
app/models/user.rb
app/services/mail_service.rb
bin/delayed_job
config/environments/production.rb
config/initializers/active_job.rb
config/settings.yml
db/migrate/20160509152138_create_delayed_jobs.rb
db/schema.rb
run.sh
spec/services/mail_service_spec.rb

Hi @novotnyjakub. Can we check how this is with branch runner (created pull request to test)

Create fr staff worker

---

app/assets/stylesheets/local/errors.scss
app/assets/stylesheets/local/inputs.scss
app/assets/stylesheets/local/labels.scss
app/services/application_search.rb
app/views/applications/process/application_details.html.slim
app/views/applications/process/income.html.slim
app/views/evidence/income.html.slim
app/views/home/index.html.slim
app/views/online_applications/edit.html.slim
spec/controllers/home_controller_spec.rb
spec/services/application_search_spec.rb

The HWF search box is now more forgiving - prefix and dashes / spaces don't have to be provided.

Improve hwf retrieval

---

app/views/shared/_tag_manager.html.slim

A cut and paste error left issues with the tag manager JS block...

Updated slim layout for JS

---

app/builders/application_builder.rb
app/controllers/api/submissions_controller.rb
app/controllers/online_applications_controller.rb
app/models/application.rb
app/models/online_application.rb
app/services/application_calculation.rb
db/migrate/20160620085231_add_new_saving_fields_to_online_application.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/factories/online_applications.rb
spec/factories/public_app_submissions.rb
spec/models/application_spec.rb
spec/models/online_application_spec.rb
spec/services/application_calculation_spec.rb

**This should be merged into the savings-update branch before it's merged into master**
Allows the public app to submit updated inputs and process them.

Online application saving update

---

app/models/forms/application/savings_investment.rb
app/views/shared/savings/_amount.slim
config/locales/en.yml
spec/models/forms/application/savings_investment_spec.rb

The original validation left something to be desired.
This tightens it up and makes it, hopefully, more refined!

Refactor saving validation

---

app/assets/javascripts/evidence_confirmation.js
app/assets/javascripts/income.js
app/assets/javascripts/radio_checkbox_module.js

[Pivotal](https://www.pivotaltracker.com/story/show/122129503)
Lets the radio/checkbox module handle show/hide for the children input box, and fixes the case where it would not be hidden on page load.

don't show children input unless it's needed

---

app/assets/stylesheets/local/panels.scss
app/views/applications/process/application_details.html.slim
app/views/applications/process/benefits.html.slim
app/views/applications/process/income.html.slim
app/views/applications/process/personal_information.html.slim
app/views/applications/process/savings_investments.html.slim
app/views/benefit_overrides/paper_evidence.html.slim
app/views/business_entities/index.html.slim
app/views/guide/evidence_checks.html.slim
app/views/guide/process_application.html.slim
app/views/home/_processed_and_deleted_aplications.html.slim
app/views/home/_waiting_applications.html.slim
app/views/home/index.html.slim
app/views/offices/_form.html.slim
app/views/offices/index.html.slim
app/views/offices/show.html.slim
app/views/online_applications/edit.html.slim
app/views/reports/public.html.slim
app/views/shared/_decision_override.html.slim
app/views/shared/processed_and_deleted/_index.html.slim
app/views/shared/processed_and_deleted/_show.html.slim
app/views/shared/savings/_max_threshold_exceeded.slim
app/views/users/deleted.html.slim
app/views/users/index.html.slim
app/views/users/show.html.slim
config/locales/en.yml

Applying some of the accessibility learnings from the public app to the staff app, mainly to do with tables and fieldsets.

Accessibility improvements

---

app/views/offices/show.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/126495387)

caption should be visuallyhidden

---

app/lib/income_calculation.rb
app/lib/income_thresholds.rb
app/models/views/application_overview.rb
config/locales/summary.en.yml
config/settings.yml
spec/lib/income_thresholds_spec.rb
spec/models/views/application_overview_spec.rb

Some refactoring has been done here as well.

Display income thresholds when processing online application

---

app/helpers/summary_helper.rb
spec/helpers/summary_helper_spec.rb

Replace the code that highlights outcome statements with code that doesn't highlight all text that starts with W!

Refactor the W bug

---

app/views/guide/evidence_checks.html.slim
app/views/guide/part_payments.html.slim
app/views/guide/process_application.html.slim
app/views/guide/suspected_fraud.html.slim

— updates to reflect online service is now available not just in trial
courts
— minor amends to typos and style

Amends to staff guides

---

app/controllers/users_controller.rb

When editing a user, sort the list of offices alphabetically

Sort offices alphabetically

---

app/helpers/summary_helper.rb
db/schema.rb

replace the erroneous `x` with, the correct, `✗`

Update the summary helper

---

app/controllers/reports_controller.rb
app/policies/report_policy.rb
app/views/evidence/_confirmation_none_remission.html.slim
app/views/evidence/return_letter.html.slim
app/views/guide/evidence_checks.html.slim
app/views/guide/process_application.html.slim
app/views/part_payments/_failed_letter.html.slim
app/views/part_payments/return_letter.html.slim
app/views/reports/index.html.slim
app/views/reports/letters.html.slim
config/locales/letters_en.yml
config/routes.rb
spec/controllers/reports_controller_spec.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/features/part_payments/part_payments_flow_spec.rb
spec/policies/report_policy_spec.rb

— add ref no to letters
— add text about adding ref no. to documents
— amended letter references in staff guides
@colinbruce note
Also addresses [ticket](https://www.pivotaltracker.com/story/show/124493221) to provide a page with all letters that staff can link to from the guide (at some point in the future)... this also makes it easier to debug changes to the letters!

Letters update

---

Guardfile

guardfile was outdated and needed updating

updated guardfile

---

README.md
app/controllers/evidence_checks_controller.rb
app/policies/base_policy.rb

Improve gaps in the test coverage and update the readme to link to the test coverage page of code climate

Improve code climate

---

app/assets/stylesheets/local/tables.scss
app/models/views/application_list.rb
app/views/shared/processed_and_deleted/_index.html.slim
config/locales/en.yml
spec/models/views/application_list_spec.rb

[Trello ticket](https://trello.com/c/PpcKSV4z/6-update-list-of-process-and-deleted-applications-to-include-marked-for-evidence-check-and-part-payment)
[Original pivotal ticket](https://www.pivotaltracker.com/story/show/113885717)
Add extra columns to the processed and deleted application tables

Extend columns on application table

---

app/controllers/users/invitations_controller.rb
app/views/users/invitations/new.html.slim
spec/views/users/invitations/new.html.slim_spec.rb

Add a sorted office list to the user invitation controller and view, test it

Add sorted offices

---

app/services/dwp_monitor.rb
spec/controllers/home_controller_spec.rb
spec/services/dwp_monitor_spec.rb
spec/support/dwp_setup.rb

A new error is being received from the LAA
This counts and updates the status banner when it occurs

Added handler for new error type

---

.travis.yml
package.json

* Update the selenium package version
* ensure phantomJS version is always set to 2.1.1
* cache and pre-install in travis
This corrects issued raised by Gemnasium

Update npm handling

---

app/mailers/public_mailer.rb
app/services/mail_service.rb
app/views/public_mailer/submission_confirmation_et.html.slim
app/views/public_mailer/submission_confirmation_et.text.erb
config/locales/emails_en.yml
config/settings.yml
spec/controllers/api/submissions_controller_spec.rb
spec/factories/online_applications.rb
spec/factories/public_app_submissions.rb
spec/mailers/previews/public_mailer_preview.rb
spec/mailers/public_mailer_spec.rb
spec/services/mail_service_spec.rb

Add an email for the completion of online ET applications
Duplicated the text from the publicapp confirmation screen, mainly!

Add ET confirmation email

---

app/models/views/reports/raw_data_export.rb

[Trello ticket](https://trello.com/c/XWSWvrRm/59-update-raw-data-extract)
Extended the number of columns in the raw data extract

Add columns to raw data extract

---

app/views/part_payments/return_letter.html.slim

It was being added in the the view-model as well as the view itself.

Remove pound symbol from view

---

config/locales/en.yml

https://triadmoj.atlassian.net/browse/RST-154
Just copy change. There is a test that is checking the message.

Updating dwp unavailable message.

---

app/controllers/processed_applications_controller.rb
app/views/shared/processed_and_deleted/_index.html.slim
app/views/shared/processed_and_deleted/_per_page_display.html.slim
spec/controllers/processed_applications_controller_spec.rb

Removing sort and search from processed application page. It looks like there will be more complex functionality implemented instead of this.

Removing search and sort from process application page.

---

app/views/home/index.html.slim
spec/features/applications/stray_error_on_confirmation_page_spec.rb
spec/features/evidence-checks/evidence_check_spec.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb
spec/features/return_applications/return_part_payment_applications_spec.rb
spec/support/feature_helpers.rb
spec/views/home/index.html.slim_spec.rb

Fix for https://triadmoj.atlassian.net/browse/RST-209

Fixing IE8 issue of not accepting post method from link_to.

---

app/services/part_payment_builder.rb
app/views/online_applications/edit.html.slim
config/locales/en.yml
spec/factories/online_applications.rb
spec/features/part_payments/refund_part_payment_spec.rb
spec/services/part_payment_builder_spec.rb
spec/support/admin_application_steps.rb

JIRA: https://triadmoj.atlassian.net/browse/RST-226

Partial payment application is marked as process if it's refund.

---

spec/features/evidence-checks/evidence_check_spec.rb
spec/support/admin_application_steps.rb

Adding test that check the flag evidence check.

---

app/services/evidence_check_selector.rb
spec/services/evidence_check_selector_spec.rb

** The NINO stands for National Insurance Number

skip ni_exists evidence check for applicants without NINO

---

spec/factories/online_applications.rb
spec/features/online_applications/evidence_check_spec.rb

Just a test to check on a specific scenario.

Adding test for online evidence check.

---

app/controllers/benefit_overrides_controller.rb
app/models/application.rb
spec/factories/benefit_checks.rb
spec/models/application_spec.rb
spec/services/benefit_check_runner_spec.rb

Empty benefit checks were affecting result view. 
Approved by Dan.

Empty benefit checks are not returned.

---

app/controllers/users/invitations_controller.rb
spec/controllers/users/invitations_controller_spec.rb

It was case sensitive and db is downsizing it.

Fixing issue with deleted user invitation

---

.gitignore
config/database.yml
db/schema.rb

Allows flexible configuration of database via ENV vars (for development and test environments) for docker configs
If ENV vars are not set, works as before

Allows flexible configuration of database via ENV vars 

---

db/schema.rb

The schema appears out of date - this was corrected when I ran the migrations, and according to the migrations, it is correct and therefore, master is incorrect

The schema appears out of date

---

.env.test
app/mailers/application_mailer.rb
config/locales/emails_en.yml
spec/mailers/application_mailer_spec.rb
spec/rails_helper.rb

So we know where the alert email is from.

Adding environment value to subject of alert email.

---

app/services/benefit_check_runner.rb
spec/features/applications/processing_refund_application_spec.rb
spec/services/benefit_check_runner_spec.rb

For some reason, we merged 594 to Prod. But there is more to it so I'm reverting those changes.

Reverting back the benefit check date changes.

---

app/lib/income_calculation.rb
spec/support/calculator_test_data.rb

Updating the calculator logic so it does not ignore upper limit.

Fixing bug in income calculator.

---

spec/features/no_evidence_check/rst_975_spec.rb
spec/support/admin_application_steps.rb

Test auto for RST-975 PLEASE DO NOT MERGE

Test auto for feature RST-975

---

spec/factories/applications.rb
spec/features/no_evidence_check/rst_985_spec.rb
spec/models/application_spec.rb

Test auto for RST-985, second scenario to delete is still missing as I am trying to figure out how to delete on the app.

Adding test auto for RST-985

---

app/helpers/guide_helper.rb
app/views/guide/index.html.slim
spec/helpers/guide_helper_spec.rb

Using same icon for Suspected fraud guide.

Adding guide Fraud awareness

---

app/services/dwp_monitor.rb
spec/support/dwp_setup.rb

There is a new API coming soonish so we will have a better way how to check if the DWP is down. For now this has to do.

Fixing bug where the monitor was not seeing bad requests.

---

app/controllers/business_entities_controller.rb
app/models/business_entity.rb
app/services/business_entity_service.rb
app/views/business_entities/index.html.slim
spec/models/business_entity_spec.rb
spec/services/business_entity_service_spec.rb

We are not using be_code as the main code which is causing errors, because it could be empty. Validation in the scope of name and office_id should sort out this issue.

Changing scope for sop_code uniqueness validation

---

app/models/views/overview/application.rb
app/models/views/overview/details.rb
app/views/shared/processed_and_deleted/_show.html.slim
config/locales/en.yml
spec/models/views/overview/details_spec.rb

Adding discretion manager lines.

Fixing message for failed paper evidence.

---

db/migrate/20180808095028_add_object_changes_to_versions.rb
db/schema.rb

So we can track what values changed and how.

Adding object_changes to versions table

---

app/views/layouts/application.html.slim
spec/features/navigation_spec.rb

Adding a link to letter templates into a menu.

Adding link to a menu to access Letter templates

---

app/controllers/home_controller.rb
app/views/home/index.html.slim
spec/controllers/home_controller_spec.rb

To improve UX I'm moving "Your last applications" to the top of the page so users don't have to scroll all the way down to find it.

Moving "Your last applications" at the top of the list

---

.travis.yml
Gemfile
features/setup_db.rb
features/sign_in.feature
features/step_definitions/application_details_steps.rb
features/step_definitions/benefits_steps.rb
features/step_definitions/confirmation_steps.rb
features/step_definitions/paper_evidence_steps.rb
features/step_definitions/personal_details_steps.rb
features/step_definitions/savings_investments_steps.rb
features/step_definitions/summary_steps.rb
features/support/page_objects/application_details_page.rb

As we now have some Cucumber tests that pass locally, I want to add them to Travis so the tests run before code is merged.
I have added the command to run the tests to the travis.yml and done some fixes to ensure the tests reliably pass on Travis.

task/rst-1673 add cucumber to .travis.yml

---

app/assets/javascripts/gtm_track_timestamps.js
app/views/home/_last_updated_applications.html.slim
app/views/home/_processed_and_deleted_aplications.html.slim
app/views/home/index.html.slim

Pushing data to dataLayer when user clicks on last updated apps or perform the search or clicks on the result of the search.

Adding more GTM tracking

---

.travis.yml

- Ask travis to use qt5
- Use postgres 9.6 to match our current db version
- Run cucumber tests with xvfb-run

Update travis conf

---

app/assets/stylesheets/local/pagination.scss
app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/models/application.rb
app/views/home/_search_results.html.slim
app/views/home/index.html.slim
config/locales/en.yml
config/routes.rb
features/application_search.feature
features/step_definitions/application_search_steps.rb
features/step_definitions/user_dashboard_steps.rb
features/support/capybara_driver_helper.rb
features/support/env.rb
features/support/generic_helpers.rb
features/support/page_objects/application_search_page.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/sign_in_page.rb
features/user_dashboard.feature
spec/controllers/home_controller_spec.rb
spec/features/search/user_can_search_for_completed_applications_spec.rb

Pagination is set to 100 records per page.

Adding pagination and default sorting

---

app/models/application.rb
config/locales/en.yml
features/application_search.feature
features/step_definitions/application_search_steps.rb
features/support/page_objects/application_search_page.rb
spec/services/application_search_spec.rb

Just adding NI number to search parameters.

Extending search to NI number

---

app/models/forms/application/detail.rb
app/models/forms/online_application.rb
app/views/applications/process/details/index.html.slim
app/views/online_applications/edit.html.slim
config/locales/en.yml
features/admin_dashboard.feature
features/application_details.feature
features/sign_in.feature
features/step_definitions/application_details_steps.rb
features/support/page_objects/application_details_page.rb
spec/factories/details.rb
spec/factories/online_applications.rb
spec/features/applications/application_form_application_details_spec.rb
spec/features/applications/application_form_stories_spec.rb
spec/features/applications/show_result_on_confirmation_spec.rb
spec/features/applications/stray_error_on_confirmation_page_spec.rb
spec/features/benefit_override/allow_override_when_dwp_checker_says_no_spec.rb
spec/features/benefit_override/no_ni_number_and_undetermined_result_spec.rb
spec/features/benefit_override/when_benefits_checker_returns_undetermined_result_spec.rb
spec/models/forms/application/detail_spec.rb
spec/models/forms/online_application_spec.rb
spec/support/admin_application_steps.rb

Adding form_name format validation

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/local/banners.scss
app/assets/stylesheets/local/dwp-tags.scss
app/assets/stylesheets/local/errors.scss
app/views/home/index.html.slim
app/views/layouts/application.html.slim
app/views/shared/_notifications.html.slim
app/views/shared/dwp/_offline.html.slim
app/views/shared/dwp/_online.html.slim
app/views/shared/dwp/_warning.html.slim
config/locales/en.yml
features/application_search.feature
features/dwp_message.feature
features/process_online_application.feature
features/step_definitions/admin_dashboard_steps.rb
features/step_definitions/dashboard_steps.rb
features/step_definitions/dwp_message_steps.rb
features/step_definitions/process_online_application_steps.rb
features/step_definitions/sign_in_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/dwp_message_page.rb
features/support/page_objects/navigation_page.rb
features/user_dashboard.feature
spec/views/home/index.html.slim_spec.rb
spec/views/layouts/application.html.slim_spec.rb

This PR is about UI changes for the notifications displayed in the homepage.
Changes:
- reduced box sizes for notifications
- replaced the phase banner with the DWP notification messages
- reworded the DWP notification messages
- moved the feedback link to the top menu
This PR should sort out issues mentioned in the #888

Change notifications styles in homepages

---

config/locales/en.yml
features/support/page_objects/application_details_page.rb
spec/support/admin_application_steps.rb

Changing the application fee label will help the staff users to enter the correct fee.

Change the application fee label

---

app/builders/application_builder.rb
app/controllers/applications/process/details_controller.rb
app/controllers/online_applications_controller.rb
app/models/forms/fee_approval.rb
app/policies/application_policy.rb
app/policies/online_application_policy.rb
app/repositories/application_form_repository.rb
app/services/details_router.rb
app/views/applications/process/details/approve.html.slim
app/views/online_applications/approve.html.slim
app/views/shared/forms/_approve.html.slim
config/locales/en.yml
config/routes.rb
config/settings.yml
db/migrate/20190610091108_add_first_name_and_last_name_to_online_applications.rb
db/migrate/20190610102245_add_manager_firstname_and_manager_lastname_to_details.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/controllers/applications/process/details_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/factories/online_applications.rb
spec/models/forms/fee_approval_spec.rb
spec/policies/application_policy_spec.rb
spec/policies/online_application_policy_spec.rb
spec/repositories/application_form_repository_spec.rb
spec/services/details_router_spec.rb

This PR introduces an approval page when processing applications, so that high fee amounts can be authorised by a suitable person

Introduce fee approval page

---

app/models/concerns/data_field_formattable.rb
app/models/forms/application/applicant.rb
spec/features/applications/show_result_on_confirmation_spec.rb
spec/models/forms/application/detail_spec.rb
spec/support/shared_examples/date_received_validation.rb

It didn't displayed the date when you revisited the page

RST-1947 - Fixing issue with dob fields

---

app/models/forms/online_application.rb
app/views/online_applications/edit.html.slim
config/locales/en.yml
spec/features/applications/processing_refund_application_spec.rb
spec/features/online_applications/staff_can_add_details_spec.rb
spec/models/forms/online_application_spec.rb
spec/support/shared_examples/date_received_validation.rb

RST-1962 - Updating date field to follow gds pattern

---

features/dashboard.feature
features/step_definitions/dashboard_steps.rb
features/step_definitions/user_dashboard_steps.rb
features/step_definitions/your_last_applications_steps.rb
features/support/page_objects/dashboard_page.rb
features/user_dashboard.feature
features/your_last_applications.feature

This PR adds a test that ensures that when a paper application is started and abandoned that the data is saved when the application is opened from 'Your last application'.
```
[ ] Yes
[x ] No
```

Feature test for abandoned applications

---

Dockerfile
run.sh

RST-2057 base image service support

---

.dockerignore
Gemfile
azure-pipelines.yml
pipeline-steps/add-dependencies.yaml
pipeline-steps/docker-build.yaml
pipeline-steps/manual-docker-build.yaml
pipeline-steps/publish-tests.yaml
pipeline-steps/test-application.yaml

Adding applicaiton tests, postgres service and templates
```
[ ] Yes
[x] No
```

pipeline updates

---

performance-tests/.gitignore
performance-tests/Dockerfile
performance-tests/README.md
performance-tests/gatling.sh
performance-tests/src/test/resources/application.conf
performance-tests/src/test/resources/local.conf
performance-tests/src/test/scala/simulations/HttpConfiguration.scala
performance-tests/src/test/scala/simulations/StaffAppPerformance.scala

Gatling tests

---

performance-tests/README.md

updated format of readme

---

app/assets/javascripts/gtm_track_timestamps.js
app/views/home/index.html.slim
app/views/layouts/application.html.slim
app/views/layouts/local-template.html.erb

This is a branch dedicated to more fixes for Rails upgrade branch rst-1893.

v3 for Rails upgrade branch

---

azure-pipelines.yml
pipeline-steps/test-application.yaml

This change affects test in Azure DevOps only
```
[ ] Yes
[x] No
```

adding superuser to ADO Test Postgres user

---

app/views/static/400.html.slim
app/views/static/404.html.slim
app/views/static/500.html.slim
app/views/static/503.html.slim
public/404.html

To match the GDS patern.
https://tools.hmcts.net/jira/browse/RST-2113
Updating static error pages
```
[ ] Yes
[x] No
```

RST-2113 - Updating static error pages

---

app/views/evidence/result.html.slim
app/views/processed_applications/show.html.slim
app/views/shared/part_payment_evidence/_show.html.slim
config/locales/en.yml
features/step_definitions/user_dashboard_steps.rb

https://tools.hmcts.net/jira/browse/RST-2061
Updates page titles for accessibility reasons
```
[ ] Yes
[X] No
```

Update page titles

---

app/views/applications/process/benefits/index.html.slim
config/locales/en.yml
features/step_definitions/benefits_steps.rb
features/support/page_objects/benefits_page.rb

https://tools.hmcts.net/jira/browse/RST-2071
Update ambiguous question
```
[ ] Yes
[X] No
```

Update the Benefits question

---

run.sh

RST-2250
DB migration in a correct dir
```
[ ] Yes
[x] No
```

RST-2250 DB migration in a correct dir

---

app/controllers/evidence/accuracy_failed_reason_controller.rb
app/controllers/evidence_controller.rb
app/views/shared/part_payment_evidence/_show.html.slim
features/evidence.feature
features/problem_with_evidence.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/problem_with_evidence_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
features/support/page_objects/problem_with_evidence_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb
spec/controllers/evidence/accuracy_failed_reason_controller_spec.rb
spec/controllers/evidence_controller_spec.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/features/online_applications/evidence_check_spec.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-2308
When the evidence is rejected you will get to choose why, before the rejection letter is displayed.
```
[ ] Yes
[x] No
```

RST-2308 rejection reasons

---

app/views/users/_filters_panel.html.slim
app/views/users/index.html.slim
features/step_definitions/navigation_steps.rb
features/step_definitions/users_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/deleted_staff_page.rb
features/support/page_objects/send_invitation_page.rb
features/support/page_objects/users_page.rb
features/users.feature
spec/views/users/index.html.slim_spec.rb

https://tools.hmcts.net/jira/browse/RST-2007
```
[ ] Yes
[x] No
```

RST-2007 - Moving links to top of the page

---

app/assets/stylesheets/local/headings.scss
app/assets/stylesheets/local/inputs.scss
app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
app/controllers/reports_controller.rb
app/models/forms/finance_report.rb
app/models/forms/report/finance_transactional_report.rb
app/views/reports/finance_report.html.slim
app/views/reports/finance_transactional_report.html.slim
app/views/reports/raw_data.html.slim
app/views/shared/_report_dates.html.slim
config/locales/en.yml
features/generate_report.feature
features/step_definitions/generate_report_steps.rb
features/support/page_objects/generate_report_page.rb
spec/builders/finance_report_builder_spec.rb
spec/builders/finance_transactional_report_builder_spec.rb
spec/controllers/reports_controller_spec.rb

Add more report filters to both the finance transactional and aggregate reports
https://tools.hmcts.net/jira/browse/RST-1703
Adding filters to the export options
```
[ ] Yes
[x] No
```

RST-1703 report filters

---

app/views/users/_filters_panel.html.slim

https://tools.hmcts.net/jira/browse/RST-2007
Moving links to the top of the box and making them bold
```
[ ] Yes
[x] No
```

Moving links to the top of the filter box

---

app/models/forms/application/applicant.rb
config/locales/en.yml
features/personal_details.feature
features/step_definitions/personal_details_steps.rb
features/support/page_objects/personal_details_page.rb
spec/models/forms/application/applicant_spec.rb

https://tools.hmcts.net/jira/browse/RST-2361
Acceptending under 16 now, but not the ones born in the future.
```
[ ] Yes
[x] No
```

RST-2361 - Changing dob validation

---

app/helpers/processed_views_helper.rb
app/views/evidence/return_letter.html.slim
config/locales/letters_en.yml
features/evidence.feature
features/problem_with_evidence.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/problem_with_evidence_steps.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/problem_with_evidence_page.rb

https://tools.hmcts.net/jira/browse/RST-2320
Updating the rejection later based on incorrect reason value
```
[ ] Yes
[x] No
```

RST-2320 - Rejection letter is now based on the incorrect_reason value

---

config/locales/letters_en.yml
spec/features/evidence/evidence_check_flow_spec.rb

Copy changes
https://tools.hmcts.net/jira/browse/RST-2149
```
[ ] Yes
[x] No
```

RST-2149 - Removing line about maximum income allowed

---

app/views/evidence/_confirmation_none_remission.html.slim
config/locales/letters_en.yml
spec/features/evidence/evidence_check_flow_spec.rb

when evidence is rejected.
https://tools.hmcts.net/jira/browse/RST-2379
```
[ ] Yes
[x] No
```

RST-2379 Adding new generic rejection letter

---

app/controllers/evidence/accuracy_incorrect_reason_controller.rb
app/views/evidence/accuracy_incorrect_reason/show.html.slim
app/views/evidence/show.html.slim
app/views/shared/part_payment_evidence/_show.html.slim
config/locales/en.yml
features/problem_with_evidence.feature
features/step_definitions/evidence_steps.rb
features/support/page_objects/base_page.rb
features/support/page_objects/evidence_accuracy_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/problem_with_evidence_page.rb
spec/features/evidence-checks/evidence_check_part_payment_flow_spec.rb
spec/features/no_evidence_check/rst_985_spec.rb
spec/features/online_applications/evidence_check_spec.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-2371
Copy changes.
```
[ ] Yes
[x] No
```

RST-2371 - Changing copy on few places for evidence flow

---

app/models/forms/application/detail.rb
app/models/views/application_list.rb
app/models/views/overview/details.rb
app/views/applications/process/details/index.html.slim
app/views/applications/process/savings_investments/index.html.slim
app/views/online_applications/edit.html.slim
features/application_details.feature
features/step_definitions/application_details_steps.rb
features/support/page_objects/application_details_page.rb
spec/models/forms/application/detail_spec.rb
spec/models/views/application_list_spec.rb
spec/models/views/overview/details_spec.rb

RST-1839 decimal v2

---

app/assets/stylesheets/local/headings.scss
app/assets/stylesheets/local/inputs.scss
app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
app/controllers/reports_controller.rb
app/models/forms/finance_report.rb
app/models/forms/report/finance_transactional_report.rb
app/views/reports/finance_report.html.slim
app/views/reports/finance_transactional_report.html.slim
app/views/reports/raw_data.html.slim
app/views/shared/_report_dates.html.slim
config/locales/en.yml
features/generate_report.feature
features/step_definitions/generate_report_steps.rb
features/support/page_objects/generate_report_page.rb
spec/builders/finance_report_builder_spec.rb
spec/builders/finance_transactional_report_builder_spec.rb
spec/controllers/reports_controller_spec.rb

* Adding filters to finance report page
* Adding filters field to report generator page
* Adding filters to finance report builder
* Fixing failing tests
clash with rails 6 upgrade. Fixing formatting.
* Updating spec for report controller
* Filters for finance transactional report
* Filters for finance transactional report
* Updating translations and form tags
* Updating the layout for report form
* Fixing issue of missing date from inputs
When form was reloaded, due to an error, you lost the date you put in.
* rst-1703 cucumber tests for filters
https://tools.hmcts.net/jira/browse/RST-1703
```
[ ] Yes
[x] No
```

RST-1703 report filters 

---

app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
app/controllers/reports_controller.rb
app/models/forms/finance_report.rb
app/models/forms/report/finance_transactional_report.rb
app/models/views/reports/raw_data_export.rb
app/views/shared/_report_dates.html.slim
config/locales/en.yml
features/support/page_objects/generate_report_page.rb
spec/builders/finance_report_builder_spec.rb
spec/builders/finance_transactional_report_builder_spec.rb
spec/controllers/reports_controller_spec.rb
spec/models/forms/finance_report_spec.rb
spec/models/views/reports/raw_data_export_spec.rb

RST-2259 date fields

---

app/models/forms/application/detail.rb
app/models/views/application_list.rb
app/models/views/overview/details.rb
app/views/applications/process/details/index.html.slim
app/views/applications/process/savings_investments/index.html.slim
app/views/online_applications/edit.html.slim
spec/models/forms/application/detail_spec.rb
spec/models/views/application_list_spec.rb
spec/models/views/overview/details_spec.rb

https://tools.hmcts.net/jira/browse/RST-1839
Allowing to enter and display fee with 2 decimal points.
```
[ ] Yes
[x] No
```

RST-1839 decimal entry fee

---

app/views/evidence/accuracy_failed_reason/show.html.slim
features/support/page_objects/problem_with_evidence_page.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-2412
Updating page title.
```
[ ] Yes
[x] No
```

Updating title for the evidence problem page

---

app/helpers/processed_views_helper.rb
app/models/views/processed_data.rb
app/views/evidence/_confirmation_none_remission.html.slim
app/views/evidence/return_letter.html.slim
config/locales/letters_en.yml
features/problem_with_evidence.feature
features/return_letter.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/problem_with_evidence_steps.rb
features/step_definitions/return_letter_steps.rb
features/support/page_objects/problem_with_evidence_page.rb
features/support/page_objects/return_letter_page.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/models/views/processed_data_spec.rb

https://tools.hmcts.net/jira/browse/RST-2410
Adding what to do next block to rejection letter page
```
[ ] Yes
[x] No
```

RST-2410, 2408, 2409 - evidence letter

---

app/helpers/summary_helper.rb
config/locales/en.yml
features/reason_for_rejecting_evidence.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/helpers/summary_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-2232
Updating sub-sections on summary page 
```
[ ] Yes
[x] No
```

RST-2232 summary page changes

---

app/controllers/evidence/accuracy_failed_reason_controller.rb
app/controllers/evidence/accuracy_incorrect_reason_controller.rb
app/models/evidence_check.rb
spec/models/evidence_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-2419
Resetting income value, when it should not be displayed or used.
```
[ ] Yes
[x] No
```

RST-2419 income reset and RST-2405

---

app/views/evidence/_confirmation_none_remission.html.slim
app/views/evidence/confirmation.html.slim
config/locales/letters_en.yml

Removing duplicated next steps section and updating fee text
https://tools.hmcts.net/jira/browse/RST-2421
```
[ ] Yes
[x] No
```

RST-2421 - Removing duplicated next steps section

---

app/services/ccmcc_evidence_check_rules.rb
app/services/evidence_check_selector.rb
db/migrate/20200108154850_add_ccmcc_check_type_to_evidence_checks_table.rb
db/schema.rb
spec/services/ccmcc_evidence_check_rules_spec.rb
spec/services/evidence_check_selector_spec.rb

DO NOT MERGE 
And implementing the 5000 rule for non-refund checks
https://tools.hmcts.net/jira/browse/RST-2440
```
[ ] Yes
[x] No
```

RST-2440 - CCMCC evidence check  5k rule

---

app/services/ccmcc_evidence_check_rules.rb
app/services/evidence_check_selector.rb
spec/services/ccmcc_evidence_check_rules_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-2441
```
[ ] Yes
[x] No
```

RST-2441 - 25 percent between 1 and 5 thousand

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-2442
Adding 25 per cent rule between 100 and 999 for a refund only
```
[ ] Yes
[x] No
```

RST-2442 - Adding 25 percent rule between 100 and 999

---

app/views/evidence/accuracy_failed_reason/show.html.slim

when you choose a different option then Staff error
https://tools.hmcts.net/jira/browse/RST-2454
```
[ ] Yes
[x] No
```

RST-2454 Error box is now hiding

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-2442
10 per cent for non-refund between 100 and 999
```
[ ] Yes
[x] No
```

RST-2443 10 percent for non refund between 100 and 999

---

app/assets/stylesheets/local/layout.scss

https://tools.hmcts.net/jira/browse/RST-2462
Breaking text in notification panel so it doesn't overflow outside the box.
```
[ ] Yes
[x] No
```

RST-2462- Breaking text in notification panel

---

app/assets/stylesheets/local/alerts.scss
app/controllers/evidence_controller.rb
features/evidence.feature
features/step_definitions/evidence_steps.rb
features/support/page_objects/evidence_page.rb
spec/controllers/evidence_controller_spec.rb

after processing evidence
https://tools.hmcts.net/jira/browse/RST-2451
```
[ ] Yes
[x] No
```

RST-2451 Fixing bug when you could go back

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-2445
Adding 2 per cent rule for everything under 100 pounds.
```
[ ] Yes
[x] No
```

RST-2245 2 percent rule

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-2446
50 per cent for applications between 1 and 5 thousand
```
[ ] Yes
[x] No
```

RST-2446 - Adding another rule for refund application check

---

app/models/views/reports/ccmcc_data_export.rb
app/services/ccmcc_evidence_check_rules.rb
spec/models/views/reports/ccmcc_data_export_spec.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

We are calculating against the amount to remit (fee - amount_to_pay), not against fee only
```
[ ] Yes
[x] No
```

CCMCC remit amount

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

Updating CCMCC annotations in DB so they are easier to sort in Excel.
```
[ ] Yes
[ ] No
```

RST-2429 - Updating text of ccmcc annotations

---

features/staff_guides.feature
features/step_definitions/staff_guides_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/appeals_guide_page.rb
features/support/page_objects/evidence_checks_guide_page.rb
features/support/page_objects/forbidden_page.rb
features/support/page_objects/guide_page.rb
features/support/page_objects/guides_page.rb
features/support/page_objects/part_payments_guide_page.rb
features/support/page_objects/process_application_guide.rb
features/support/page_objects/suspected_fraud_guide_page.rb

I noticed a lack of Cucumber tests covering the staff guides so here they are.
```
[ ] Yes
[x] No
```

cucumber tests for staff guides

---

app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
spec/builders/finance_report_builder_spec.rb
spec/builders/finance_transactional_report_builder_spec.rb

https://tools.hmcts.net/jira/browse/RST-2483
Refund filter for report filters was always on.
```
[ ] Yes
[x] No
```

RST-2483 - Fixing bug when refund filter was always on

---

features/personal_details.feature
features/step_definitions/personal_details_steps.rb
features/support/page_objects/personal_details_page.rb

cucumber tests for personal details page

---

app/models/views/reports/raw_data_export.rb
spec/factories/jurisdictions.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-2479
Adding more fields to reflect changes in amount to pay and cost after Evidence checks
```
[ ] Yes
[x] No
```

RST-2479 - Updating raw data export columns

---

azure-pipelines.yml

Azure DevOps pg fix
```
[ ] Yes
[x] No
```

Azure DevOps pg fix

---

features/notification_banner.feature
features/step_definitions/dwp_message_steps.rb
features/step_definitions/generic_steps.rb
features/step_definitions/notification_banner_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/base_page.rb
features/support/page_objects/dwp_message_page.rb
features/support/page_objects/edit_banner_page.rb

tests for adding and removing banner

---

app/models/views/reports/ccmcc_data_export.rb
spec/models/views/reports/ccmcc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-2497
Update CCMCC data export fields
```
[ ] Yes
[x] No
```

RST-2497 - Updating ccmcc data export

---

app/controllers/report/fees_mechanical_data_controller.rb
app/models/views/reports/ccmcc_data_export.rb
app/models/views/reports/fees_mechanical_data_export.rb
app/policies/report_policy.rb
app/services/evidence_check_selector.rb
app/views/reports/fees_mechanical_data.html.slim
app/views/reports/index.html.slim
config/routes.rb
db/migrate/20200219102147_rename_ccmcc_annotation_to_checks_annotation.rb
db/schema.rb
features/reports.feature
features/step_definitions/reports_steps.rb
features/support/page_objects/reports_page.rb
spec/controllers/report/fees_mechanical_data_controller_spec.rb
spec/models/views/reports/ccmcc_data_export_spec.rb
spec/models/views/reports/fees_mechanical_data_export_spec.rb
spec/policies/report_policy_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-2489
Report export for Fees & Mechanical recording office
```
[ ] Yes
[x] No
```

RST-2489 fees mechanical export

---

config/environments/development.rb
config/environments/production.rb

https://tools.hmcts.net/jira/browse/RST-2470
Fixing the disabled button after the report is generated
```
[ ] Yes
[x] No
```

RST-2470 - Fixing issue with disabled report button

---

app/views/shared/_report_dates.html.slim
config/locales/en.yml

https://tools.hmcts.net/jira/browse/RST-2467
Updating error messages on date fields on the report page.
```
[ ] Yes
[x] No
```

RST-2467 date error messages

---

Gemfile
Gemfile.lock
config/application.rb

https://tools.hmcts.net/jira/browse/RST-2482
```
[ ] Yes
[X] No
```

Send metrics to Azure Application Insights

---

spec/rails_helper.rb

Stub requests to Azure Application Insights when running the specs
```
[ ] Yes
[X] No
```

Stub requests to Azure Application Insights

---

app/policies/user_policy.rb
app/views/users/shared/_form_jurisdiction.html.slim
app/views/users/shared/_form_office.html.slim
spec/policies/user_policy_spec.rb

https://tools.hmcts.net/jira/browse/RST-2522
```
[ ] Yes
[x] No
```

RST-2522  - Only reader can't change office and jurisdiction

---

app/helpers/application_helper.rb
app/models/views/application_result.rb
app/models/views/overview/application.rb
app/models/views/reports/ccmcc_data_export.rb
app/models/views/reports/fees_mechanical_data_export.rb
app/models/views/reports/raw_data_export.rb
app/views/applications/process/confirmation/index.html.slim
db/migrate/20200226120118_change_amount_to_pay_type.rb
db/migrate/20200227115846_change_amount_to_pay_type_at_evidence_check.rb
db/schema.rb
spec/factories/part_payments.rb
spec/features/evidence/evidence_check_flow_spec.rb
spec/lib/income_calculation_spec.rb
spec/models/views/application_result_spec.rb
spec/models/views/overview/application_spec.rb
spec/models/views/reports/ccmcc_data_export_spec.rb
spec/models/views/reports/fees_mechanical_data_export_spec.rb
spec/models/views/reports/raw_data_export_spec.rb
spec/support/calculator_test_data.rb

https://tools.hmcts.net/jira/browse/RST-2517
Storing and displaying amount to pay as a decimal.
```
[ ] Yes
[x] No
```

RST-2517 decimal amount to pay

---

features/support/env.rb

added stub request to env file

---

app/controllers/users/invitations_controller.rb
app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/users/shared/_form_roles.html.slim
spec/controllers/users/invitations_controller_spec.rb
spec/policies/user_policy_spec.rb

https://tools.hmcts.net/jira/browse/RST-2519
Updating managers' permissions so he can change roles to the reader and invite readers
```
[ ] Yes
[x] No
```

RST-2519- Updating manager permissions

---

app/policies/user_policy.rb
spec/policies/user_policy_spec.rb

https://tools.hmcts.net/jira/browse/RST-2531
A manager should be able to see Reader user in his staff list
```
[ ] Yes
[x] No
```

RST-2531 - Fixing visibility of a reader user for a manager

---

app/views/layouts/local-template.html.erb

https://tools.hmcts.net/jira/browse/RST-2539
```
[ ] Yes
[x] No
```

RST-2539 - Removing loader for FE to fix routing errors

---

features/change_user_details.feature
features/staff.feature
features/step_definitions/change_user_details_steps.rb
features/step_definitions/dwp_message_steps.rb
features/step_definitions/generic_steps.rb
features/step_definitions/notification_banner_steps.rb
features/step_definitions/staff_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/base_page.rb
features/support/page_objects/change_profile_details_page.rb
features/support/page_objects/change_user_details_page.rb
features/support/page_objects/sign_in_page.rb
features/support/page_objects/staff_details_page.rb
features/support/page_objects/staff_page.rb

tests for staff and changing profiles

---

app/models/application.rb
app/models/evidence_check_flag.rb
app/services/evidence_check_flagging_service.rb
app/services/evidence_check_selector.rb
db/migrate/20200407080356_rename_ni_number_to_reg_number_at_evidence_check_flags.rb
db/schema.rb
features/evidence.feature
features/ho_evidence_check.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/ho_evidence_check_steps.rb
features/step_definitions/personal_details_steps.rb
features/step_definitions/summary_steps.rb
features/step_definitions/your_last_applications_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/ho_evidence_check_page.rb
features/support/page_objects/paper_evidence_page.rb
features/support/page_objects/personal_details_page.rb
features/support/page_objects/problem_with_evidence_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb
features/support/page_objects/summary_page.rb
spec/factories/evidence_check_flags.rb
spec/models/application_spec.rb
spec/models/evidence_check_flag_spec.rb
spec/services/evidence_check_flagging_service_spec.rb
spec/services/evidence_check_selector_spec.rb
spec/support/admin_application_steps.rb

Updating Evidence Check logic to include HO number

RST-2560 evidence check HO number

---

features/staff_guides.feature
features/step_definitions/staff_guides_steps.rb
features/support/page_objects/guide_page.rb
spec/models/views/reports/raw_data_export_spec.rb

Guides cucumber tests fix

---

Dockerfile

Use correct Ruby base image
```
[ ] Yes
[X] No
```

Fix Ruby base image

---

config/locales/en.yml
features/benefits.feature
features/incomes.feature
features/step_definitions/benefits_steps.rb
features/step_definitions/incomes_steps.rb
features/step_definitions/paper_evidence_steps.rb
features/step_definitions/summary_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/benefits_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/summary_page.rb
spec/features/applications/processing_refund_application_spec.rb

RST-2564 copy changes v2

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/devise_security.rb
config/locales/devise.security_extension.en.yml
db/migrate/20200414125301_add_session_limitable_to_users.rb
db/schema.rb

https://tools.hmcts.net/jira/browse/RST-2120
This PR will force users to have only one active session.
```
[ ] Yes
[X] No
```

Force single user sessions

---

app/builders/finance_transactional_report_builder.rb
app/models/views/reports/finance_transactional_report_data_row.rb
spec/builders/finance_transactional_report_builder_spec.rb
spec/factories/offices.rb
spec/models/views/reports/finance_report_data_row_spec.rb
spec/models/views/reports/finance_transactional_report_data_row_spec.rb

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RST-2572
Change description
Removing Digital office from the report and adding SOP code.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

RST-2572 reports update

---

app/views/guide/evidence_checks.html.slim
app/views/guide/part_payments.html.slim
app/views/guide/process_application.html.slim
app/views/guide/suspected_fraud.html.slim

https://tools.hmcts.net/jira/browse/RST-2569
Copy changes
```
[ ] Yes
[x] No
```

RST-2569 guidance update

---

app/builders/application_builder.rb
app/controllers/api/submissions_controller.rb
app/models/application.rb
app/models/online_application.rb
db/migrate/20200427094157_add_income_kind_to_online_application_table.rb
db/migrate/20200428065811_add_income_kind_to_applications.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/controllers/api/submissions_controller_spec.rb
spec/factories/public_app_submissions.rb
spec/models/application_spec.rb
spec/models/online_application_spec.rb

Staff app part of https://tools.hmcts.net/jira/browse/RST-2573
```
[ ] Yes
[x] No
```

RST-2573 income kind api

---

Gemfile.lock
app/models/views/application_result.rb
features/part_payment.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/incomes_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/processed_applications_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/part_payment_page.rb
features/support/page_objects/processed_applications_page.rb
spec/models/views/application_result_spec.rb

When there was an evidence check and part payement the part payment banner was not working correctly.
https://tools.hmcts.net/jira/browse/RST-2016
```
[ ] Yes
[x] No
```

Part payment banner fix

---

app/models/views/overview/application.rb
app/views/evidence/show.html.slim
app/views/online_applications/show.html.slim
app/views/shared/part_payment_evidence/_show.html.slim
app/views/shared/part_payment_evidence/_summary.html.slim
app/views/shared/processed_and_deleted/_show.html.slim
config/locales/en.yml
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-2574
```
[ ] Yes
[x] No
```

RST-2574 income kind summary

---

app/views/applications/process/details/index.html.slim

https://tools.hmcts.net/jira/browse/RST-2576
```
[ ] Yes
[x] No
```

RST-2576 - Updating copy

---

app/views/applications/process/incomes/index.html.slim
config/locales/en.yml
features/incomes.feature
features/step_definitions/incomes_steps.rb
features/support/page_objects/incomes_page.rb

https://tools.hmcts.net/jira/browse/RST-2580
```
[ ] Yes
[x] No
```

RST-2580 Updating copy on income page

---

config/locales/en.yml
features/personal_details.feature
features/step_definitions/personal_details_steps.rb
features/support/page_objects/personal_details_page.rb

https://tools.hmcts.net/jira/browse/RST-2579
```
[ ] Yes
[x] No
```

RST-2579 - Updating error message and copy for HO number

---

app/helpers/evidence_check_helper.rb
app/views/evidence/_confirmation_none_remission.html.slim
app/views/reports/letters.html.slim
config/locales/letters_en.yml
spec/features/evidence/evidence_check_flow_spec.rb
spec/helpers/evidence_check_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-2059
```
[ ] Yes
[x] No
```

RST-2059 - Updating income rejection letter

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-2628
```
[ ] Yes
[x] No
```

RST-2628 raw data extension

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/models/views/overview/application.rb
app/views/applications/process/confirmation/index.html.slim
app/views/shared/_remission_type.html.slim
config/locales/en.yml
config/locales/letters_en.yml
features/part_payment.feature
features/reason_for_rejecting_evidence.feature
features/step_definitions/change_user_details_steps.rb
features/step_definitions/dwp_message_steps.rb
features/step_definitions/evidence_steps.rb
features/step_definitions/find_application_steps.rb
features/step_definitions/notification_banner_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/summary_steps.rb
features/support/capybara_driver_helper.rb
features/support/env.rb
features/support/generic_helpers.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/edit_banner_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/navigation_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-226
```
[ ] Yes
[x] No
```

RST-226 refund letter template

---

features/step_definitions/notification_banner_steps.rb
features/support/capybara_driver_helper.rb
features/support/generic_helpers.rb
features/support/page_objects/benefits_page.rb
features/support/page_objects/paper_evidence_page.rb
features/support/page_objects/personal_details_page.rb

Fix capybara driver helper

---

Gemfile
app/helpers/application_helper.rb
app/models/views/application_result.rb
app/services/resolver_service.rb
app/views/applications/process/confirmation/index.html.slim
app/views/evidence/confirmation.html.slim
app/views/shared/_refund_template.html.slim
app/views/shared/_remission_type.html.slim
features/evidence.feature
features/part_payment.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/part_payment_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/evidence_page.rb
spec/features/evidence-checks/evidence_check_part_payment_flow_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/views/application_result_spec.rb
spec/services/resolver_service_spec.rb

it doesn’t go to part payment but to processed state
https://tools.hmcts.net/jira/browse/RST-226
```
[ ] Yes
[x] No
```

RST-226 - When the refund is part payment

---

features/notification_banner.feature
features/step_definitions/confirmation_steps.rb
features/step_definitions/dwp_message_steps.rb
features/step_definitions/evidence_steps.rb
features/step_definitions/generic_steps.rb
features/step_definitions/notification_banner_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/staff_steps.rb
features/step_definitions/summary_steps.rb
features/support/page_objects/change_user_details_page.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/evidence_accuracy_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/find_application_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/navigation_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb

Unreliable test fix v2

---

app/views/shared/_refund_template.html.slim
config/locales/letters_en.yml

https://tools.hmcts.net/jira/browse/RST-226
```
[ ] Yes
[x] No
```

RST-226 - Updating partial refund template

---

app/views/applications/process/confirmation/index.html.slim
app/views/evidence/_confirmation_part_remission.html.slim
app/views/reports/letters.html.slim
config/locales/letters_en.yml
spec/features/applications/remission_confirmation_spec.rb
spec/features/evidence/evidence_check_flow_spec.rb

https://tools.hmcts.net/jira/browse/RST-2565
```
[ ] Yes
[x] No
```

RST-2565 evidence check letter template v2

---

app/helpers/guide_helper.rb
app/views/guide/index.html.slim
features/staff_guides.feature
features/step_definitions/staff_guides_steps.rb
features/support/page_objects/guide_page.rb

https://tools.hmcts.net/jira/browse/RST-2675
```
[ ] Yes
[x] No
```

RST-2675 - Adding link to training course on the guide line page

---

app/models/forms/online_application.rb
features/evidence.feature
features/step_definitions/evidence_steps.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/incomes_page.rb
spec/models/forms/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-2724
```
[ ] Yes
[x] No
```

RST-2724 - Updating fee type from integer to decimal

---

app/controllers/benefit_overrides_controller.rb
app/controllers/online_application_benefits_controller.rb
app/controllers/online_applications_controller.rb
app/models/forms/online_application.rb
app/views/home/index.html.slim
app/views/online_application_benefits/edit.html.slim
config/locales/en.yml
config/routes.rb
db/migrate/20200521073854_add_benefits_override_to_online_application.rb
db/schema.rb
spec/controllers/benefit_overrides_controller_spec.rb
spec/controllers/online_application_benefits_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/models/forms/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-2670
https://tools.hmcts.net/jira/browse/RST-2630
```
[ ] Yes
[x] No
```

RST-2670  and RST-2630 only paper evidence for benefit

---

app/controllers/benefit_overrides_controller.rb
app/controllers/online_applications_controller.rb
app/models/dwp_warning.rb
features/benefit_checker.feature
features/step_definitions/benefit_checker_steps.rb
features/support/generic_helpers.rb
spec/controllers/benefit_overrides_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/models/dwp_warning_spec.rb

https://tools.hmcts.net/jira/browse/RST-2730
```
[ ] Yes
[x] No
```

RST-2730 update processing switch

---

app/services/dwp_monitor.rb
spec/services/dwp_monitor_spec.rb
spec/support/dwp_setup.rb

so the DWP monitor reacts more quickly
https://tools.hmcts.net/jira/browse/RST-2716
```
[ ] Yes
[x] No
```

RST-2716 - Reducing number of application to be checked

---

app/helpers/evidence_check_helper.rb
app/views/evidence_checks/show.html.slim
app/views/reports/letters.html.slim
config/locales/letters_en.yml
features/step_definitions/reason_for_rejecting_evidence_steps.rb
spec/helpers/evidence_check_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-2711
```
[ ] Yes
[x] No
```

RST-2711 evidence needed letter based on income type

---

app/helpers/summary_helper.rb
app/views/applications/process/confirmation/index.html.slim
config/locales/letters_en.yml
features/step_definitions/application_details_steps.rb
features/step_definitions/approve_steps.rb
features/step_definitions/benefit_checker_steps.rb
features/step_definitions/confirmation_steps.rb
features/step_definitions/evidence_steps.rb
features/step_definitions/generic_steps.rb
features/step_definitions/incomes_steps.rb
features/step_definitions/personal_details_steps.rb
features/step_definitions/problem_with_evidence_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
features/step_definitions/savings_investments_steps.rb
features/step_definitions/your_last_applications_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/approve_page.rb
features/support/page_objects/benefits_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/paper_evidence_page.rb
features/support/page_objects/part_payment_page.rb
features/support/page_objects/personal_details_page.rb
features/support/page_objects/problem_with_evidence_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb
features/support/page_objects/savings_investments_page.rb
spec/helpers/summary_helper_spec.rb
spec/rails_helper.rb

https://tools.hmcts.net/jira/browse/RST-2768
```
[ ] Yes
[x] No
```

RST-2768 Partial refund bug

---

app/controllers/applications/process/benefits_controller.rb
app/controllers/home_controller.rb
app/controllers/users/sessions_controller.rb
app/views/applications/process/benefits/index.html.slim
app/views/home/index.html.slim
app/views/layouts/application.html.slim
features/benefit_checker.feature
features/step_definitions/benefit_checker_steps.rb
features/support/page_objects/benefit_checker_page.rb
spec/controllers/applications/process/benefits_controller_spec.rb
spec/controllers/home_controller_spec.rb
spec/views/layouts/application.html.slim_spec.rb

https://tools.hmcts.net/jira/browse/RST-2760
Display the DWP status banner in the sign in page.
```
[ ] Yes
[X] No
```

Rst 2760 dwp banner

---

config/locales/letters_en.yml
features/step_definitions/confirmation_steps.rb
features/step_definitions/find_application_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/personal_details_page.rb
features/support/page_objects/savings_investments_page.rb

https://tools.hmcts.net/jira/browse/RST-2772
```
[ ] Yes
[x] No
```

RST-2772 - Updating evidence rejection letter template

---

app/helpers/summary_helper.rb
app/models/application.rb
app/views/applications/process/confirmation/index.html.slim
app/views/reports/letters.html.slim
config/locales/letters_en.yml
features/step_definitions/benefit_checker_steps.rb
features/step_definitions/confirmation_steps.rb
features/step_definitions/find_application_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/personal_details_page.rb
features/support/page_objects/savings_investments_page.rb
spec/helpers/summary_helper_spec.rb
spec/rails_helper.rb

https://tools.hmcts.net/jira/browse/RST-2766
https://tools.hmcts.net/jira/browse/RST-2767
https://tools.hmcts.net/jira/browse/RST-2772
```
[ ] Yes
[x] No
```

RST-2766 and RST-2767- Auto populating saving rejection letter and benefits fail letter

---

app/views/home/index.html.slim
features/evidence.feature
features/step_definitions/benefit_checker_steps.rb
features/step_definitions/confirmation_steps.rb
features/step_definitions/evidence_steps.rb
features/step_definitions/navigation_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/problem_with_evidence_steps.rb
features/step_definitions/process_online_application_steps.rb
features/step_definitions/summary_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/base_page.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/problem_with_evidence_page.rb
features/support/page_objects/savings_investments_page.rb
spec/features/applications/application_form_stories_spec.rb
spec/features/evidence-checks/evidence_check_spec.rb
spec/features/no_evidence_check/rst_974_spec.rb
spec/views/home/index.html.slim_spec.rb

https://tools.hmcts.net/jira/browse/RST-2741
https://tools.hmcts.net/jira/browse/RST-2742
```
[ ] Yes
[x] No
```

RST-2741 and RST-2742 messages refactor and DWP banner

---

app/helpers/application_helper.rb
app/views/shared/_refund_template.html.slim
config/locales/letters_en.yml
spec/helpers/application_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-2780
```
[ ] Yes
[x] No
```

RST-2780  Fixing bug and wording in partial refund template

---

features/step_definitions/benefit_checker_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/base_page.rb
features/support/page_objects/benefits_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/savings_investments_page.rb
lib/tasks/rerun_benefit_checks.rake
spec/lib/tasks/task_rerun_benefit_checks_spec.rb

https://tools.hmcts.net/jira/browse/RST-2752
```
[ ] Yes
[x] No
```

RST-2752 Adding logging for rerun job rake task

---

app/views/guide/process_application.html.slim

https://tools.hmcts.net/jira/browse/RST-2777
```
[ ] Yes
[x] No
```

RST-2777 - Updating side menu in “processing application”

---

app/assets/javascripts/application.js
app/assets/javascripts/savings.js
app/models/forms/application/savings_investment.rb
app/views/applications/process/incomes/index.html.slim
app/views/shared/savings/_amount.slim
config/locales/en.yml
features/step_definitions/confirmation_steps.rb
features/step_definitions/incomes_steps.rb
features/step_definitions/savings_investments_steps.rb
spec/models/forms/application/savings_investment_spec.rb

and rounding the value to nearest whole pound
https://tools.hmcts.net/jira/browse/RST-2414
```
[ ] Yes
[x] No
```

RST-2414 - Adding hint about rounding to savings page

---

app/views/reports/letters.html.slim
config/locales/letters_en.yml

https://tools.hmcts.net/jira/browse/RST-2816
```
[ ] Yes
[x] No
```

RST-2816 - Removing DWP deceased response template

---

.env.test
.gitignore
config/cucumber.yml
features/process_online_application.feature
features/step_definitions/benefit_checker_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
features/step_definitions/summary_steps.rb
features/step_definitions/unprocessed_applications_when_dwp_is_down_steps.rb
features/support/generic_helpers.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/dwp_failed_applications_page.rb
features/support/page_objects/reason_for_rejecting_evidence_page.rb
features/support/page_objects/sign_in_page.rb
features/unprocessed_applications_when_dwp_is_down.feature
spec/factories/benefit_checks.rb

https://tools.hmcts.net/jira/browse/RST-2757
Add Cucumber feature - unprocessed_applications_when_dwp_is_down.feature and steps
```
[ ] Yes
[ x] No
```

RST-2757 Add Cucumber scenarios

---

.gitignore
features/skip_ev_check_for_15_and_under.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
features/step_definitions/return_letter_steps.rb
features/step_definitions/skip_ev_check_for_15_and_under.steps.rb
features/support/generic_helpers.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/personal_details_page.rb

https://tools.hmcts.net/jira/browse/RST-2727
Add cucumber tests for RST-2727 change
```
[ ] Yes
[x] No
```

Rst 2727 cucumber tests

---

.gitignore
.travis.yml
app/models/applicant.rb
app/models/online_application.rb
app/models/views/overview/applicant.rb
app/services/evidence_check_selector.rb
config/locales/en.yml
features/skip_ev_check_for_15_and_under.feature
features/step_definitions/evidence_steps.rb
features/step_definitions/part_payment_steps.rb
features/step_definitions/personal_details_steps.rb
features/step_definitions/reason_for_rejecting_evidence_steps.rb
features/step_definitions/return_letter_steps.rb
features/step_definitions/skip_ev_check_for_15_and_under.steps.rb
features/support/generic_helpers.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/evidence_page.rb
features/support/page_objects/incomes_page.rb
features/support/page_objects/personal_details_page.rb
pipeline-steps/test-application.yaml
spec/models/applicant_spec.rb
spec/models/online_application_spec.rb
spec/models/views/overview/applicant_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-2727
```
[ ] Yes
[x] No
```

RST-2727 -  Skip EV check for under 16

---

app/helpers/result_helper.rb
features/rejection_letter.feature
spec/helpers/result_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-2660
```
[ ] Yes
[x] No
```

RST-2660 - Updating copy for income rejection letter max amount

---

app/controllers/evidence_controller.rb
app/services/evidence_check_flagging_service.rb
features/nino_evidence.feature
features/part_payment.feature
features/step_definitions/benefit_checker_steps.rb
features/step_definitions/evidence_steps.rb
features/step_definitions/find_application_steps.rb
features/step_definitions/nino_evidence_steps.rb
features/step_definitions/part_payment_steps.rb
features/support/page_objects/application_details_page.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/personal_details_page.rb
spec/controllers/evidence_controller_spec.rb
spec/factories/applications.rb
spec/factories/online_applications.rb
spec/features/online_applications/evidence_check_spec.rb
spec/services/evidence_check_flagging_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-2858
```
[ ] Yes
[x] No
```

cucumber for rst 2858

---

features/saving_investments_61.feature
features/step_definitions/saving_investments_61_steps.rb
features/support/page_objects/personal_details_page.rb

https://tools.hmcts.net/jira/browse/RST-2876
```
[ ] Yes
[x] No
```

added test for ticket 2876

---

features/support/capybara_driver_helper.rb

Use Capybara headless Chrome driver on pipeline
```
[ ] Yes
[ x] No
```

Use Capybara headless Chrome driver on pipeline

---

app/views/applications/process/personal_informations/index.html.slim
app/views/guide/process_application.html.slim
features/step_definitions/personal_details_steps.rb

https://tools.hmcts.net/jira/browse/RST-2898
```
[ ] Yes
[x] No
```

RST-2898 Fixing anchors for links on personal details page

---

app/views/online_applications/edit.html.slim

https://tools.hmcts.net/jira/browse/RST-2899
```
[ ] Yes
[x] No
```

RST-2899 Removing duplication

---

app/models/views/confirmation/result.rb
app/views/applications/process/confirmation/index.html.slim
features/override.feature
features/override_results_discretion.feature
features/step_definitions/override_results_discretion.rb
features/step_definitions/override_steps.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/dashboard_page.rb
features/support/page_objects/paper_evidence_page.rb
spec/models/views/confirmation/result_spec.rb

https://tools.hmcts.net/jira/browse/RST-2922
```
[ ] Yes
[x] No
```

RST-2922 Fixing copy displayed when result is overridden

---

app/models/concerns/refund_validatable.rb
app/models/forms/application/detail.rb
app/models/views/overview/details.rb
config/locales/en.yml
features/refund_request_row.feature
features/step_definitions/refund_request_row.rb
features/support/page_objects/summary_page.rb
spec/models/forms/application/detail_spec.rb
spec/models/views/overview/details_spec.rb

https://tools.hmcts.net/jira/browse/RST-2908
```
[ ] Yes
[x] No
```

RST-2908 Adding line to summary page for refund

---

app/assets/javascripts/refund.js

RST-2919 - Fixing toggle issue for incomplete year

---

features/README.md
features/process_online_application.feature
features/summary.feature

https://tools.hmcts.net/jira/browse/RST-2999
```
[ ] Yes
[x] No
```

added smoke test to see if benefit and online applications work

---

app/controllers/guide_controller.rb
app/views/guide/accessibility_statement.html.slim
app/views/shared/_footer.slim
config/locales/en.yml
config/routes.rb

https://tools.hmcts.net/jira/browse/RST-2956
- Added accessibility statement page and link to it in the footer.
```
[ ] Yes
[x] No
```

RST-2956 Statement added

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-3015
```
[ ] Yes
[x] No
```

RST-3015 - Fixing missing values for saving in raw export

---

app/models/forms/application/applicant.rb
config/locales/en.yml
features/personal_details.feature
features/step_definitions/nino_evidence_steps.rb
features/step_definitions/personal_details_steps.rb
features/support/page_objects/personal_details_page.rb
spec/models/applicant_spec.rb
spec/models/forms/application/applicant_spec.rb

https://tools.hmcts.net/jira/browse/RST-3035
```
[ ] Yes
[x] No
```

RST-3035 Updating HO number to require seven digits

---

.gitignore
Gemfile
Gemfile.lock
package-lock.json

Updating puma gem

---

app/helpers/guide_helper.rb
app/views/guide/index.html.slim
features/staff_guides.feature
features/step_definitions/staff_guides_steps.rb
features/step_definitions/staff_steps.rb
features/support/page_objects/guide_page.rb
features/support/page_objects/sign_in_page.rb

https://tools.hmcts.net/jira/browse/RST-3044
```
[ ] Yes
[x] No
```

RST-3044 Job cards on guideline

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-3022
```
[ ] Yes
[x] No
```

RST-3022 Adding date fee paid to raw data extract

---

app/helpers/guide_helper.rb
features/step_definitions/staff_guides_steps.rb

https://tools.hmcts.net/jira/browse/RST-3044
```
[ ] Yes
[x] No
```

RST-3044 new link for job cards

---

app/models/feedback.rb
app/views/feedback/_form.html.slim
config/locales/en.yml
features/step_definitions/your_feedback_steps.rb
features/support/page_objects/feedback_page.rb
features/your_feedback.feature
spec/factories/feedbacks.rb
spec/models/feedback_spec.rb
spec/views/feedback/new.html.slim_spec.rb

https://tools.hmcts.net/jira/browse/RST-2940
```
[ ] Yes
[x] No
```

RST-2940 Feedback needs to have a rating answered

---

app/controllers/dwp_failed_applications_controller.rb
app/models/query/last_dwp_failed_applications.rb
app/views/dwp_failed_applications/index.html.slim
app/views/home/index.html.slim
features/step_definitions/unprocessed_applications_when_dwp_is_down_steps.rb
features/support/page_objects/dashboard_page.rb
features/unprocessed_applications_when_dwp_is_down.feature
spec/controllers/dwp_failed_applications_controller_spec.rb
spec/models/query/last_dwp_failed_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-2970
```
[ ] Yes
[x] No
```

RST-2970 DWP pending applications for admin

---

db/migrate/20210107141027_add_new_jurisdiction.rb
db/schema.rb

JIRA: https://tools.hmcts.net/jira/browse/RST-3073
```
[ ] Yes
[x] No
```

RST-3037 - Adding new jurisdiction

---

Gemfile
Gemfile.lock

Updating devise related gems

---

app/controllers/evidence_controller.rb
app/controllers/part_payments_controller.rb
app/views/evidence/confirmation.html.slim
app/views/evidence/return_letter.html.slim
app/views/guide/evidence_checks.html.slim
app/views/guide/part_payments.html.slim
app/views/part_payments/confirmation.html.slim
app/views/part_payments/return_letter.html.slim
config/locales/en.yml
features/evidence.feature
features/part_payment.feature
features/return_letter.feature
features/step_definitions/confirmation_steps.rb
features/step_definitions/nino_evidence_steps.rb
features/step_definitions/return_letter_steps.rb
features/step_definitions/user_dashboard_and_navigation.rb
features/support/helpers/generic_helpers.rb
features/support/page_objects/base_page.rb
spec/controllers/evidence_controller_spec.rb
spec/controllers/part_payments_controller_spec.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-3046
https://tools.hmcts.net/jira/browse/RST-3048
- Added 'Back to list' button to the confirmation page for 'waiting for evidence' and 'waiting for part-payment' applications.
```
[ ] Yes
[x] No
```

RST-3046+3048 Back to list button

---

Gemfile.lock
azure-pipelines.yml

Reverting bundler update

---

app/models/views/reports/finance_transactional_report_data_row.rb
spec/models/views/reports/finance_transactional_report_data_row_spec.rb

https://tools.hmcts.net/jira/browse/RST-3125
```
[ ] Yes
[x] No
```

RST-3125 - Fixing bug when the business entity is empty

---

app/controllers/applications/process/benefits_controller.rb
spec/controllers/applications/process/benefits_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-2984
```
[ ] Yes
[x] No
```

RST-2984 - Fixing bug when benefit override answer is changed

---

app/models/forms/online_application.rb
spec/models/forms/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-2944
```
[ ] Yes
[x] No
```

RST-2944 Fixing jurisdiction bug on details view

---

Gemfile
Gemfile.lock
spec/features/applications/application_form_application_details_spec.rb
spec/features/applications/application_form_stories_spec.rb
spec/features/applications/confirmation_is_rendered_spec.rb
spec/features/applications/new_savings_investment_spec.rb
spec/features/applications/remission_confirmation_spec.rb
spec/features/applications/show_result_on_confirmation_spec.rb
spec/features/applications/stray_error_on_confirmation_page_spec.rb
spec/rails_helper.rb
spec/support/dwp_api_response.rb

Removing capybara-webkit
https://tools.hmcts.net/jira/browse/RST-3103
```
[ ] Yes
[x] No
```

RST-3103  removing capybara-webkit

---

azure-pipelines.yml

to fix pending image build
https://tools.hmcts.net/jira/browse/RST-3134
```
[ ] Yes
[x] No
```

RST-3134 Updating pipeline config

---

app/models/views/reports/power_bi_export.rb

https://tools.hmcts.net/jira/browse/RST-3085
```
[ ] Yes
[x] No
```

RST-3085 - Updating inner query scope to match the main one

---

app/models/query/last_dwp_failed_applications.rb
app/views/dwp_failed_applications/index.html.slim
config/locales/en.yml
pipeline-steps/test-application.yaml
spec/models/query/last_dwp_failed_applications_spec.rb

https://tools.hmcts.net/jira/browse/RST-3138

RST-3138 - Fixing issue with duplicated records in admin list

---

app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
app/controllers/reports_controller.rb
app/models/forms/finance_report.rb
app/models/forms/report/finance_transactional_report.rb
app/views/shared/_report_dates.html.slim
config/locales/en.yml
features/step_definitions/generate_report_steps.rb
spec/builders/finance_report_builder_spec.rb
spec/builders/finance_transactional_report_builder_spec.rb
spec/controllers/reports_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-3136
```
[ ] Yes
[x] No
```

RST-3141 sop code is now used for financial reports

---

Dockerfile
Gemfile.lock
azure-pipelines.yml
pipeline-steps/test-application.yaml

Fixing path in docker file

---

azure-pipelines.yml
pipeline-steps/test-application.yaml
spec/features/applications/application_form_application_details_spec.rb

Tidying up the test rerun

---

config/initializers/filter_parameter_logging.rb

https://tools.hmcts.net/jira/browse/RST-3214
```
[ ] Yes
[x] No
```

RST-3214 sanitising logs

---

app/views/business_entities/edit.html.slim
app/views/business_entities/index.html.slim

https://tools.hmcts.net/jira/browse/RST-3176
```
[ ] Yes
[x] No
```

RST-3176 - Removing be_code from BE list

---

app/views/applications/process/savings_investments/index.html.slim

https://tools.hmcts.net/jira/browse/RST-2677

RST-2677 IE bug fix

---

Gemfile
Gemfile.lock
app/views/evidence/_confirmation_return_remission.html.slim
config/brakeman.ignore
features/README.md
pipeline-steps/test-application.yaml

https://tools.hmcts.net/jira/browse/RST-1162
- Added Brakeman security gem to pipeline
```
[ ] Yes
[x] No
```

RST-1162 Adding Brakeman security scanner gem

---

lib/tasks/rerun_benefit_checks.rake
spec/lib/tasks/task_rerun_benefit_checks_spec.rb

https://tools.hmcts.net/jira/browse/RST-3234

RST-3234 Logging rake task run as custom event

---

Dockerfile
Gemfile.lock
README.md

Mimemagic gem changed licence and yanked old versions.
```
[ ] Yes
[x] No
```

Bugfix -mimemagic

---

Gemfile
Gemfile.lock
README.md
app/jobs/benefit_check_rerun_job.rb
app/jobs/cron_job.rb
app/models/user.rb
db/migrate/20210330093124_add_cron_to_delayed_jobs.rb
db/schema.rb
spec/controllers/api/submissions_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-3256

RST-3256 cron job via delayed_job

---

app/controllers/dwp_failed_applications_controller.rb
app/views/dwp_failed_applications/index.html.slim
spec/controllers/dwp_failed_applications_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-3238

RST-3238 - Loading the state based on DWP warning

---

app/views/benefit_overrides/paper_evidence.html.slim
app/views/guide/evidence_checks.html.slim
config/locales/en.yml
features/step_definitions/benefit_checker_steps.rb
features/support/page_objects/benefit_checker_page.rb
features/support/page_objects/paper_evidence_page.rb
spec/features/applications/benefit_results_are_processed_spec.rb
spec/features/applications/processing_refund_application_spec.rb
spec/support/admin_application_steps.rb

https://tools.hmcts.net/jira/browse/RST-3305

RST-3305 - Updating copy for paper evidence text

---

app/services/resolver_cost_calculator.rb
spec/services/resolver_cost_calculator_spec.rb

https://tools.hmcts.net/jira/browse/RST-3347

RST-3347 Fixing bug with decision_cost for part refund

---

app/helpers/guide_helper.rb
features/step_definitions/staff_guides_steps.rb

https://tools.hmcts.net/jira/browse/RST-3368

RST-3368- Updating URL for training course on guides page

---

Gemfile
Gemfile.lock
app/jobs/hmrc_data_purge_job.rb
db/migrate/20210528093146_add_purged_at_to_hmrc_checks.rb
db/schema.rb
spec/factories/hmrc_checks.rb
spec/jobs/hmrc_data_purge_job_spec.rb

https://tools.hmcts.net/jira/browse/RST-3191

RST-3191 HMRC data purge

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/RST-3397

RST-3397 - Updating ubuntu image

---

public/404.html
public/422.html
public/500.html

https://tools.hmcts.net/jira/browse/RST-3411

RST-3144 - Removing auth token from static files

---

config/locales/en.yml
features/support/page_objects/personal_details_page.rb

https://tools.hmcts.net/jira/browse/RST-3390

RST-3390 - Updating HO number hint

---

app/views/guide/accessibility_statement.html.slim
app/views/guide/process_application.html.slim
app/views/static/400.html.slim
app/views/static/404.html.slim
app/views/static/422.html.slim
app/views/static/500.html.slim
app/views/static/503.html.slim
config/locales/en.yml
config/settings.yml
features/step_definitions/sign_in_steps.rb

https://tools.hmcts.net/jira/browse/RST-3531

RST-3531 Updating support email address

---

app/controllers/static_controller.rb
config/initializers/mime_types.rb
config/routes.rb
spec/controllers/static_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-3700

RST-3700 - Fixing issue when asset raise 404

---

app/controllers/evidence/hmrc_controller.rb
app/helpers/hmrc_check_helper.rb
app/models/forms/evidence/hmrc_check.rb
app/views/evidence/hmrc/new.html.slim
spec/controllers/evidence/hmrc_controller_spec.rb
spec/models/forms/evidence/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-3477

RST-3477 -Adding default date range for HMRC submission

---

app/views/guide/process_application.html.slim

https://tools.hmcts.net/jira/browse/RST-3658

RST-3658- Guide update

---

Gemfile.lock
package-lock.json
package.json

Updating notify gen and govuk-frontend js lib

---

config/locales/letters_en.yml

Removed content in the letter using amended template.
```
[ ] Yes
[X ] No
```

RST-3803 Removed content in the letter

---

app/views/guide/process_application.html.slim

Content changed on the Processing an application page for the section : "There are some exception"
```
[ ] Yes
[ ] No
```

RST-3905 Changed content for Processing an application page

---

app/assets/stylesheets/local/tables.scss
app/controllers/evidence/hmrc_controller.rb
app/controllers/evidence/hmrc_summary_controller.rb
app/views/evidence/hmrc/show.html.slim
app/views/evidence/hmrc_summary/show.html.slim

https://tools.hmcts.net/jira/browse/RST-4072

RST-4072: Updating income field and fixing table styling

---

Gemfile
Gemfile.lock
app/controllers/evidence/hmrc_controller.rb
app/services/hmrc_service.rb
spec/controllers/evidence/hmrc_controller_spec.rb
spec/services/hmrc_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-3738

RST-3738 rate limit

---

Gemfile
Gemfile.lock
app/assets/stylesheets/local/tables.scss
app/controllers/applications/process/confirmation_controller.rb
app/controllers/evidence/hmrc_controller.rb
app/controllers/evidence/hmrc_summary_controller.rb
app/models/hmrc_check.rb
app/policies/evidence_check_policy.rb
app/services/hmrc_service.rb
app/views/evidence/hmrc/show.html.slim
app/views/evidence/hmrc_summary/complete.html.slim
app/views/evidence/hmrc_summary/show.html.slim
config/routes.rb
spec/controllers/applications/process/confirmation_controller_spec.rb
spec/controllers/evidence/hmrc_controller_spec.rb
spec/controllers/evidence/hmrc_summary_controller_spec.rb
spec/models/hmrc_check_spec.rb
spec/policies/evidence_check_policy_spec.rb
spec/services/hmrc_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-3543

RST-3543 complete processing hmrc check

---

app/controllers/applications/process/confirmation_controller.rb
app/helpers/home_helper.rb
app/models/application.rb
app/models/evidence_check.rb
app/services/evidence_check_selector.rb
app/views/evidence/hmrc/show.html.slim
app/views/home/_last_updated_applications.html.slim
app/views/home/_waiting_applications.html.slim
features/step_definitions/user_dashboard_and_navigation.rb
features/support/helpers/generic_helpers.rb
features/support/page_objects/hmrc_income_check_page.rb
features/support/page_objects/waiting_for_evidence_applications_page.rb
features/user_dashboard_and_navigation.feature
spec/controllers/applications/process/confirmation_controller_spec.rb
spec/helpers/home_helper_spec.rb
spec/models/evidence_check_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-4080

RST-4080 hmrc evidence check link fix

---

app/controllers/evidence/hmrc_controller.rb
app/controllers/evidence/hmrc_skips_controller.rb
app/helpers/hmrc_check_helper.rb
app/helpers/home_helper.rb
app/models/forms/evidence/hmrc_check.rb
app/models/hmrc_check.rb
app/services/completed_application_redirect.rb
app/services/hmrc_api_service.rb
app/services/hmrc_service.rb
app/views/evidence/hmrc/new.html.slim
config/routes.rb
spec/controllers/evidence/hmrc_controller_spec.rb
spec/controllers/evidence/hmrc_skips_controller_spec.rb
spec/factories/hmrc_checks.rb
spec/helpers/home_helper_spec.rb
spec/models/forms/evidence/hmrc_check_spec.rb
spec/models/hmrc_check_spec.rb
spec/services/completed_application_redirect_spec.rb
spec/services/hmrc_api_service_spec.rb
spec/services/hmrc_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-4080

RST-4080 Fixing link generation when HMRC data are missing

---

app/controllers/evidence/hmrc_controller.rb
app/services/hmrc_api_service.rb
app/services/hmrc_service.rb
spec/controllers/evidence/hmrc_controller_spec.rb
spec/services/hmrc_api_service_spec.rb
spec/services/hmrc_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-4105

RST-4105 Saving error response

---

app/services/evidence_check_selector.rb
config/settings.yml
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-4108

RST-4108 Loading hmrc office code from settings

---

app/views/evidence/hmrc/new.html.slim

https://tools.hmcts.net/jira/browse/RST-3904

RST-3904 Disabling date fields input

---

app/models/views/reports/hmrc_ocmc_data_export.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4122

RST-4122 Fixing issue with income kind and adding test

---

app/models/views/reports/hmrc_ocmc_data_export.rb

https://tools.hmcts.net/jira/browse/RST-4125

RST-4125 Adding created_at field to report

---

app/lib/hmrc_income_parser.rb
app/models/hmrc_check.rb
app/models/views/reports/hmrc_ocmc_data_export.rb
spec/factories/hmrc_checks.rb
spec/lib/hmrc_income_parser_spec.rb
spec/models/hmrc_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4198

RST-4198 - Decimal point and updating tax credit calculation

---

app/views/applications/process/details/index.html.slim
app/views/applications/process/incomes/index.html.slim
app/views/applications/process/personal_informations/index.html.slim
app/views/evidence/accuracy_incorrect_reason/show.html.slim
app/views/evidence/hmrc/show.html.slim
app/views/home/index.html.slim
app/views/layouts/application.html.slim
app/views/online_applications/edit.html.slim
app/views/reports/ocmc_report.html.slim
app/views/shared/_footer.slim
app/views/shared/_report_dates.html.slim
app/views/shared/savings/_amount.slim
package-lock.json
package.json
spec/features/navigation_spec.rb

https://tools.hmcts.net/jira/browse/RST-4205

RST-4205 govuk frontend update

---

app/models/hmrc_check.rb
spec/models/hmrc_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4219

RST-4219 Fixing bug when there is no request params

---

app/views/applications/process/details/index.html.slim

RST-4181 Changed content for Application details page.

---

app/models/views/confirmation/result.rb
app/views/applications/process/confirmation/index.html.slim
spec/models/views/confirmation/result_spec.rb

https://tools.hmcts.net/jira/browse/RST-4251

RST-4251  Fixing income displayed on part payment template

---

.rubocop.yml
app/lib/hmrc_income_parser.rb
features/support/helpers/datashare_helper.rb
spec/helpers/home_helper_spec.rb
spec/lib/hmrc_income_parser_spec.rb
spec/models/hmrc_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
spec/services/completed_application_redirect_spec.rb

using taxable pay now
https://tools.hmcts.net/jira/browse/RST-4344

RST-4344 Updating income parsing logic

---

app/views/applications/process/details/index.html.slim
app/views/online_applications/edit.html.slim
features/step_definitions/process_online_application_steps.rb

Changed the content for Online and paper application page. Also changed a test.
```
[ ] Yes
[X] No
```

RST-4305 Changed content for Online and paper application

---

azure-pipelines.yml

Replacing pool name for image

---

app/models/forms/application/detail.rb
app/models/forms/application/income.rb
features/support/page_objects/incomes_page.rb
spec/models/forms/application/detail_spec.rb
spec/models/forms/application/income_spec.rb

https://tools.hmcts.net/jira/browse/RST-3881

RST-3881 Fixing bug with 0 income and fee

---

app/services/benefit_check_runner.rb
spec/services/benefit_check_runner_spec.rb

https://tools.hmcts.net/jira/browse/RST-4390

RST-4390 Updating benefit check logic

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/home/_graphs.html.slim
config/locales/en.yml

https://tools.hmcts.net/jira/browse/RST-4227

RST-4227 DWP banner copy update

---

app/views/home/index.html.slim

https://tools.hmcts.net/jira/browse/RST-3705

RST-3705 Fixing search result layout

---

Gemfile
Gemfile.lock
app/assets/stylesheets/local/banners.scss
app/views/layouts/local-template.html.erb

https://tools.hmcts.net/jira/browse/RST-4410

RST-4410 Removing cookie banner and updating parser gem

---

db/migrate/20220519083023_add_api_response_to_online_benefit_checks.rb
db/schema.rb

https://tools.hmcts.net/jira/browse/RST-4452

RST-4452 Adding missing column to online_benefit_checks

---

app/controllers/online_application_benefits_controller.rb
app/models/online_application.rb
spec/controllers/online_application_benefits_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-4453

RST-4453 Updating online benefit check override logic

---

app/assets/stylesheets/local/layout.scss
app/views/home/_last_updated_applications.html.slim
app/views/home/index.html.slim
features/support/page_objects/dashboard_page.rb
features/support/page_objects/find_application_page.rb
features/support/page_objects/sign_in_page.rb

https://tools.hmcts.net/jira/browse/RST-3502

RST-3502 Fixing missing h1 on homepage

---

Gemfile
Gemfile.lock
app/views/evidence/hmrc/new.html.slim

https://tools.hmcts.net/jira/browse/RST-3477

RST-3477 Enabling HMRC date range free input

---

app/models/hmrc_check.rb
spec/models/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-4226

RST-4226 Using higher income in evidence check when HMRC

---

app/views/guide/evidence_checks.html.slim
config/locales/letters_en.yml
features/step_definitions/summary_steps.rb

https://tools.hmcts.net/jira/browse/RST-4538
https://tools.hmcts.net/jira/browse/RST-4542

RST-4542 letter template and RST-4538 Updating evidence check guide

---

app/views/evidence/hmrc/new.html.slim

https://tools.hmcts.net/jira/browse/RST-4549

RST-4549 fixing minor bug

---

config/locales/letters_en.yml

https://tools.hmcts.net/jira/browse/RST-4542

RST-4542 letter copy update

---

.gitignore
app/models/views/confirmation/result.rb
app/views/applications/process/confirmation/index.html.slim
features/currency_format.feature
features/override.feature
features/override_results_discretion.feature
features/step_definitions/override_steps.rb
features/support/page_objects/confirmation_page.rb
features/support/page_objects/incomes_page.rb
spec/models/views/confirmation/result_spec.rb

https://tools.hmcts.net/jira/browse/RST-3428

RST-3428 Don’t override failed saving application

---

app/controllers/deleted_applications_controller.rb
app/controllers/evidence_checks_controller.rb
app/controllers/part_payments_controller.rb
app/controllers/processed_applications_controller.rb
app/helpers/application_helper.rb
app/helpers/filter_application_helper.rb
app/models/query/deleted_applications.rb
app/models/query/processed_applications.rb
app/models/query/waiting_for_evidence.rb
app/models/query/waiting_for_part_payment.rb
app/services/load_applications.rb
app/views/home/_waiting_applications.html.slim
app/views/shared/processed_and_deleted/_index.html.slim
config/application.rb
config/locales/en.yml
spec/controllers/applications/process/confirmation_controller_spec.rb
spec/controllers/deleted_applications_controller_spec.rb
spec/controllers/evidence_checks_controller_spec.rb
spec/controllers/part_payments_controller_spec.rb
spec/controllers/processed_applications_controller_spec.rb
spec/factories/applications.rb
spec/models/query/deleted_applications_spec.rb
spec/models/query/processed_applications_spec.rb
spec/models/query/waiting_for_evidence_spec.rb
spec/models/query/waiting_for_part_payment_spec.rb

https://tools.hmcts.net/jira/browse/RST-4545

RST-4545 Jurisdiction filter

---

app/controllers/report/hmrc_controller.rb
app/models/views/reports/hmrc_purged_export.rb
app/policies/report_policy.rb
app/views/reports/hmrc.html.slim
app/views/reports/index.html.slim
config/routes.rb
spec/controllers/report/hmrc_controller_spec.rb
spec/factories/applications.rb
spec/factories/evidence_checks.rb
spec/factories/hmrc_checks.rb
spec/models/views/reports/hmrc_purged_export_spec.rb
spec/policies/report_policy_spec.rb

* https://tools.hmcts.net/jira/browse/RST-4547

RST-4547 purge report

---

README.md
app/jobs/personal_data_purge_job.rb
app/lib/personal_data_purge.rb
app/models/audit_personal_data_purge.rb
config/settings.yml
db/migrate/20220824093212_add_purged_to_online_applications.rb
db/migrate/20220824093644_add_purged_to_applications.rb
db/migrate/20220825124832_create_audit_personal_data_purge.rb
db/schema.rb
spec/factories/applicants.rb
spec/factories/applications.rb
spec/jobs/personal_data_purge_job_spec.rb
spec/lib/personal_data_purge_spec.rb
spec/models/application_spec.rb
spec/models/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-4611

RST-4558 personal data disposal

---

app/models/application.rb
app/models/online_application.rb
spec/models/application_spec.rb
spec/models/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-4611

RST-4611 Purged models are not displayed

---

app/services/hmrc_api_service.rb
spec/services/hmrc_api_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-4631

RST-4631 Fixing issue when encryption on token raises error

---

app/jobs/personal_data_purge_job.rb
app/lib/personal_data_purge.rb
app/services/hmrc_api_service.rb
spec/jobs/personal_data_purge_job_spec.rb
spec/lib/personal_data_purge_spec.rb

https://tools.hmcts.net/jira/browse/RST-4637

RST-4637 script update

---

app/models/online_application.rb
app/models/views/reports/audit_personal_data_report.rb
spec/models/online_application_spec.rb
spec/models/views/reports/audit_personal_data_report_spec.rb

https://tools.hmcts.net/jira/browse/RST-4654

RST-4654 Updating report to display purged_at date

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/RST-4691

RST-4691 Ubuntu and postgres image update

---

README.md
config/cucumber.yml
features/support/env.rb
features/support/webmock.rb

Refactored cucumber
[RST-4696](https://tools.hmcts.net/jira/browse/RST-4696)
Refactored Cucumber and Webmock interactions so that internal Cucumber reporting fully works.
```
[ ] Yes
[ X] No
```

RST-4696 Cucumber reports

---

app/models/views/reports/hmrc_ocmc_data_export.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4705

RST-4705 Improving sql and formatting date

---

app/controllers/evidence/hmrc_controller.rb
app/controllers/evidence/hmrc_summary_controller.rb
config/locales/en.yml
spec/controllers/evidence/hmrc_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-4701

RST-4701 income message

---

app/lib/hmrc_income_parser.rb
spec/lib/hmrc_income_parser_spec.rb

https://tools.hmcts.net/jira/browse/RST-4697

RST-4697 Not counting cost if credit money in tax_credits

---

app/controllers/evidence/hmrc_controller.rb
app/models/forms/evidence/hmrc_check.rb
config/settings.yml
spec/models/forms/evidence/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-4671

RST-4671 income

---

Gemfile
Gemfile.lock
app/controllers/applications/process/summary_controller.rb
app/controllers/report/hmrc_controller.rb
app/controllers/report/power_bi_controller.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/sentry.rb
config/settings.yml
spec/controllers/applications/process/summary_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-4607

RST-4659 New Sentry client

---

Gemfile
Gemfile.lock
README.md
app/models/application.rb
app/models/query/deleted_applications.rb
app/models/query/last_updated_applications.rb
app/models/query/processed_applications.rb
app/services/application_search.rb
config/environments/development.rb

https://tools.hmcts.net/jira/browse/RST-4744

RST-4744 n query v2

---

app/models/evidence_check.rb
spec/controllers/applications/process/personal_informations_controller_spec.rb
spec/controllers/evidence_controller_spec.rb
spec/features/evidence/applications_awaiting_evidence_are_displayed_on_dashboard_spec.rb
spec/features/return_applications/return_evidence_checkable_applications_spec.rb
spec/features/search/user_can_search_for_completed_applications_spec.rb
spec/helpers/home_helper_spec.rb
spec/models/evidence_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
spec/services/completed_application_redirect_spec.rb

https://tools.hmcts.net/jira/browse/RST-4795

RST-4795 Validation uniqueness of application_id in evidence check

---

app/models/application.rb
app/models/benefit_check.rb
app/models/query/last_dwp_failed_applications.rb
app/services/dwp_monitor.rb
features/support/helpers/generic_helpers.rb
spec/models/benefit_check_spec.rb
spec/models/query/last_dwp_failed_applications_spec.rb
spec/support/dwp_setup.rb

https://tools.hmcts.net/jira/browse/RST-4829

RST-4829 Updating DWP fail messages check

---

app/services/ccmcc_evidence_check_rules.rb
app/services/evidence_check_selector.rb
spec/services/ccmcc_evidence_check_rules_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-4824

RST-4824 Adding another office to CCMCC checking rules

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4817

RST-4817 Over 61 is calculated against created_at date

---

app/controllers/online_application_benefits_controller.rb
app/models/online_application.rb
features/benefit_checker.feature
features/step_definitions/process_online_application_steps.rb
spec/controllers/online_application_benefits_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-4889

RST-4889 DWP processing online applications

---

app/models/online_benefit_check.rb
db/migrate/20230117143105_drop_online_benefit_checks_table.rb
db/schema.rb

Tidy up after the original RST-4892 and RST-4893 story.

RST-4892 - Removing online benefit checks 

---

app/builders/online_application_builder.rb
app/services/hwf_reference_generator.rb
spec/builders/online_application_builder_spec.rb
spec/services/hwf_reference_generator_spec.rb

https://tools.hmcts.net/jira/browse/RST-4888

RST-4888 Updating reference number generator

---

app/helpers/home_helper.rb
app/views/dwp_failed_applications/index.html.slim

https://tools.hmcts.net/jira/browse/RST-5047

RST-5047 Fixing bug when loading office

---

app/models/benefit_check.rb
spec/models/benefit_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-5030

RST-5030 Updating benefit check scope logic

---

README.md
app/controllers/report/raw_data_controller.rb
app/controllers/reports_controller.rb
app/models/views/reports/raw_data_export.rb
app/views/reports/index.html.slim
app/views/reports/raw_data.html.slim
config/routes.rb
lib/tasks/raw_data_extract.rake
spec/controllers/report/raw_data_controller_spec.rb
spec/controllers/reports_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-4903

RST-4903 Raw data export update

---

app/models/views/reports/income_claims_data_export.rb

https://tools.hmcts.net/jira/browse/RST-5078

RST-5078 - Adding more courts to income claim report

---

package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-5084

RST-5084 Updating GOV.UK Frontend to 4.5.0

---

app/models/query/waiting_for_evidence.rb
app/models/query/waiting_for_part_payment.rb

https://tools.hmcts.net/jira/browse/RST-5102

RST-5102 Fixing pre loading of user for part p and evidence

---

app/helpers/summary_helper.rb
app/models/views/overview/details.rb
spec/helpers/summary_helper_spec.rb
spec/models/views/overview/details_spec.rb

https://tools.hmcts.net/jira/browse/RST-5097

RST-5097 change link only for relevant fields

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-5104

RST-5104 - Adding no part payment returned to raw extract

---

app/models/views/overview/application.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-5125

RST-5125 - Amount to pay loaded from evidence if present

---

app/lib/hmrc_income_parser.rb
spec/lib/hmrc_income_parser_spec.rb
spec/models/hmrc_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-4782

RST-4782 child tax credit

---

.rubocop.yml
app/models/query/evidence_checkable.rb
app/services/evidence_check_selector.rb
features/ho_evidence_check.feature
features/step_definitions/ho_evidence_check_steps.rb
features/support/helpers/generic_helpers.rb
spec/factories/applications.rb
spec/factories/evidence_checks.rb
spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb
spec/features/evidence-checks/evidence_check_part_payment_flow_spec.rb
spec/features/evidence-checks/evidence_check_spec.rb
spec/features/no_evidence_check/rst_1006_spec.rb
spec/features/no_evidence_check/rst_985_spec.rb
spec/features/no_evidence_check/rst_987_spec.rb
spec/features/online_applications/evidence_check_spec.rb
spec/models/query/evidence_checkable_spec.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-5186

RST-5186 checks refactor

---

app/services/hwf_reference_generator.rb
app/services/reference_generator.rb
spec/services/hwf_reference_generator_spec.rb
spec/services/reference_generator_spec.rb

https://tools.hmcts.net/jira/browse/RST-5260

RST-5260 query online

---

db/migrate/20230315141711_change_benefit_checks_applicationable.rb
db/schema.rb

https://tools.hmcts.net/jira/browse/RST-5261

RST-5261 Adding index to benefit checks to speed up queries

---

app/services/reference_generator.rb
app/services/resolver_service_attribute.rb
spec/services/reference_generator_spec.rb
spec/services/resolver_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-5266

RST-5266 - Rerunning reference generator if ref is not valid

---

app/models/forms/online_application.rb
features/process_online_application.feature
features/step_definitions/datashare_steps.rb
features/step_definitions/nino_evidence_steps.rb
features/step_definitions/process_online_application_steps.rb
features/step_definitions/refund_request_row.rb
features/step_definitions/rejection_letter.rb
features/support/page_objects/process_online_application_page.rb

https://tools.hmcts.net/jira/browse/RST-5293

RST-5293 Stripping of space from fee input

---

app/lib/hmrc_income_parser.rb
spec/lib/hmrc_income_parser_spec.rb

https://tools.hmcts.net/jira/browse/RST-5183

RST-5183 Using postedDate in tax credit calculation

---

app/lib/hmrc_cost_of_living.rb
app/lib/hmrc_income_parser.rb
spec/lib/hmrc_income_parser_spec.rb

https://tools.hmcts.net/jira/browse/RST-5346

RST-5346 Adding May 2023 to cost of living

---

Gemfile
Gemfile.lock

Rolling back puma version

---

app/models/concerns/application_checkable.rb
spec/models/concerns/application_checkable_spec.rb

https://tools.hmcts.net/jira/browse/RST-5023
https://tools.hmcts.net/jira/browse/RST-5024

RST - 5024 Enable income checking where tax credits declared

---

README.md
app/models/feature_switching.rb
db/migrate/20230621132908_create_feature_switchings.rb
db/schema.rb
spec/models/feature_switching_spec.rb

https://tools.hmcts.net/jira/browse/RST-5285

RST-5285 feature switching plugin

---

config/environments/production.rb

https://tools.hmcts.net/jira/browse/RST-5502

RST-5502 - Removing ping from ssl exclude  

---

config/environments/production.rb

https://tools.hmcts.net/jira/browse/RST-5502

RST-5502 - Different way to check request

---

app/views/online_application_benefits/edit.html.slim
config/locales/en.yml

https://tools.hmcts.net/jira/browse/RST-5501

RST-5501 Updating benefits override message

---

app/helpers/application_helper.rb
app/views/online_applications/edit.html.slim
config/locales/en.yml
features/step_definitions/process_online_application_steps.rb

https://tools.hmcts.net/jira/browse/RST-5514

RST-5514 Adding date submitted by applicant information

---

app/controllers/report/ocmc_controller.rb
app/models/concerns/application_checkable.rb
config/settings.yml
features/support/page_objects/sign_in_page.rb
spec/models/concerns/application_checkable_spec.rb

https://tools.hmcts.net/jira/browse/RST-5521

RST-5521 Hmrc office check loads array

---

app/models/concerns/application_checkable.rb
spec/models/concerns/application_checkable_spec.rb

https://tools.hmcts.net/jira/browse/RST-5544

RST-5544 Allow paper application for HMRC check

---

app/controllers/users/passwords_controller.rb
app/controllers/users_controller.rb

https://tools.hmcts.net/jira/browse/RST-5564

RST-5564 Lowercase email for password reset

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-5529

RST-5529 Adding Birkenhead to ccmcc rules check

---

app/controllers/online_applications_controller.rb
app/lib/band_base_calculation.rb
app/models/application.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-5256

RST-5256 band based calculation of remission 

---

app/controllers/online_applications_controller.rb
app/models/detail.rb
app/models/forms/evidence/hmrc_check.rb
app/models/views/confirmation/result.rb
app/models/views/overview/application.rb
app/services/process_application.rb
app/views/evidence/show.html.slim
app/views/part_payments/show.html.slim
app/views/shared/part_payment_evidence/_summary.html.slim
app/views/shared/processed_and_deleted/_show.html.slim
config/locales/en.yml
db/migrate/20230725090312_add_calculation_scheme_to_details.rb
db/schema.rb
features/support/capybara_driver_helper.rb
spec/controllers/online_applications_controller_spec.rb
spec/models/forms/evidence/hmrc_check_spec.rb
spec/models/views/confirmation/result_spec.rb

RST-5519 application scheme

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-5527

RST-5527 Part payment outcome is now in AA column

---

app/models/views/reports/raw_data_export.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-5527

RST-5527 - Updating outcome value for pp column

---

app/models/views/confirmation/result.rb
spec/models/views/confirmation/result_spec.rb

https://tools.hmcts.net/jira/browse/RST-5583

RST-5583 Forgot summary page has scheme row

---

Gemfile.lock
package-lock.json
package.json
spec/controllers/applications/process/benefits_controller_spec.rb
spec/controllers/evidence/accuracy_failed_reason_controller_spec.rb
spec/controllers/evidence/accuracy_incorrect_reason_controller_spec.rb
spec/controllers/evidence/hmrc_controller_spec.rb
spec/controllers/offices_controller_spec.rb
spec/controllers/online_application_benefits_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/helpers/result_helper_spec.rb
spec/models/business_entity_spec.rb
spec/models/feedback_spec.rb
spec/models/forms/application/detail_spec.rb
spec/models/jurisdiction_spec.rb
spec/models/office_spec.rb
spec/models/user_spec.rb
spec/models/views/confirmation/result_spec.rb
spec/services/evidence_check_selector_spec.rb
spec/services/health_status_spec.rb
spec/services/hmrc_api_service_spec.rb
spec/services/hmrc_service_spec.rb
spec/services/mail_service_spec.rb
spec/support/shared_examples/date_received_validation.rb

https://tools.hmcts.net/jira/browse/RST-5588

RST-5588 govuk frontend update

---

config/environments/production.rb
features/support/capybara_driver_helper.rb

https://tools.hmcts.net/jira/browse/RST-5602

RST-5602 Fixing issue with url_host for mailer

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

Update base and rename Chart.yaml

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

Update MEM & CPU Chart.yaml

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

remove prod secret from conf for demo build

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

remove dev secret requirement

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

trigger staffapp rebuild all envs

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

set BC access to public URL

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

set BC access to internal svc URL

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

set BC access to internal podname

---

.rspec_parallel
Jenkinsfile_CNP
lib/tasks/test.rake

https://tools.hmcts.net/jira/browse/RST-5901

RST-5904 - pipeline extended setup

---

Jenkinsfile_CNP
features/step_definitions/process_online_application_steps.rb
lib/tasks/test.rake

https://tools.hmcts.net/jira/browse/RST-5904

RST-5904 Feature and smoke tests for CI

---

app/controllers/online_applications_controller.rb
app/services/savings_pass_fail_service.rb
charts/help-with-fees-staffapp/Chart.yaml
spec/controllers/online_applications_controller_spec.rb
spec/services/savings_pass_fail_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-5892

RST-5892 - Skip benefit check page if savings fails

---

config/locales/emails_en.yml

Reverts hmcts/hwf-staffapp#1527

Revert "RST-5637-v2 UCD content change"

---

app/controllers/applications/process/benefits_controller.rb
app/controllers/applications/process/incomes_controller.rb
app/controllers/applications/process_controller.rb
app/lib/band_base_calculation.rb
app/lib/band_calculation_helper.rb
app/models/forms/application/savings_investment.rb
app/services/process_application.rb
features/step_definitions/fee_status_steps.rb
spec/controllers/applications/process/benefits_controller_spec.rb
spec/controllers/applications/process/incomes_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-5256

RST-5256 band calculation integration 

---

app/controllers/api/submissions_controller.rb
app/controllers/online_applications_controller.rb
app/helpers/section_views_helper.rb
app/lib/band_base_calculation.rb
app/lib/band_calculation_helper.rb
app/lib/band_calculation_income.rb
app/models/online_application.rb
app/models/views/overview/children.rb
app/models/views/overview/online_applicant.rb
app/services/process_application.rb
app/views/online_applications/show.html.slim
config/locales/en.yml
db/migrate/20231121134436_add_new_fields_to_online_application.rb
db/schema.rb
spec/controllers/applications/process/incomes_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/lib/band_base_calculation_spec.rb
spec/models/views/overview/online_applicant_spec.rb

Online application band calculation

RST-5256 band integration v3

---

app/views/applications/process/summary/_post_ucd.html.slim
app/views/applications/process/summary/_pre_ucd.html.slim
app/views/applications/process/summary/index.html.slim
config/locales/en.yml

RST-5447 - Fixing minor issues

---

app/controllers/applications/process/confirmation_controller.rb
app/helpers/home_helper.rb
spec/controllers/applications/process/confirmation_controller_spec.rb
spec/helpers/home_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-5896

RST-5896 average income no HMRC check

---

app/controllers/applications/process/savings_investments_controller.rb
app/views/applications/process/summary/_post_ucd.html.slim
spec/controllers/applications/process/savings_investments_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-6061

RST-6061 saving fails flow

---

app/builders/application_builder.rb
app/controllers/api/submissions_controller.rb
app/helpers/home_helper.rb
app/lib/band_base_calculation.rb
app/lib/band_calculation_helper.rb
app/models/online_application.rb
app/models/saving.rb
app/models/views/overview/representative.rb
app/views/online_applications/show.html.slim
db/migrate/20231123223101_add_income_period_to_online_applicaiton.rb
db/migrate/20231123223304_add_over_16_to_applicant.rb
db/migrate/20231124101322_remove_not_null_on_representative.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/factories/online_applications.rb
spec/features/online_applications/evidence_check_spec.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-6062

RST-6062 age cap

---

README.md
app/models/applicant.rb
app/models/views/overview/savings_and_investments.rb
spec/models/applicant_spec.rb
spec/models/views/overview/savings_and_investments_spec.rb

https://tools.hmcts.net/jira/browse/RST-5447

RST-5447 summary

---

app/lib/band_calculation_income.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-6098

RST-6098 Fixing issue with nil savings

---

app/services/ccmcc_evidence_check_rules.rb
spec/services/ccmcc_evidence_check_rules_spec.rb

https://tools.hmcts.net/jira/browse/RST-6113

RST-6113 Fixing issue with nill amount to pay

---

app/models/views/overview/application.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6113

RST-6113 Fixing nil issue

---

app/models/views/overview/application.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6111

RST-6114 - Fixing display logic

---

app/builders/application_builder.rb
app/models/views/overview/application.rb
app/views/evidence/show.html.slim
app/views/online_applications/show.html.slim
app/views/part_payments/show.html.slim
app/views/shared/part_payment_evidence/_summary.html.slim
app/views/shared/processed_and_deleted/_show.html.slim
config/locales/en.yml
spec/builders/application_builder_spec.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6125

RST-6125 income period

---

app/controllers/applications/process/incomes_controller.rb
app/lib/band_base_calculation.rb
app/services/process_application.rb
spec/controllers/applications/process/incomes_controller_spec.rb
spec/controllers/online_applications_controller_spec.rb
spec/lib/band_base_calculation_spec.rb
spec/services/process_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6165

RST-6156 - Update income_max_threshold if income fails

---

app/models/views/reports/hmrc_ocmc_data_export.rb
app/models/views/reports/ocmc_data_export.rb
app/models/views/reports/ocmc_export_helper.rb
app/models/views/reports/raw_data_export.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
spec/models/views/reports/ocmc_data_export_spec.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-6164

RST-5995 mi report v3

---

app/lib/band_calculation_income.rb
spec/lib/band_base_calculation_spec.rb
spec/models/forms/evidence/income_spec.rb

https://tools.hmcts.net/jira/browse/RST-6179

RST-6179 rounding

---

app/lib/band_base_calculation.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-6201

RST-6201 Fixing max threshold check

---

app/lib/band_calculation_helper.rb
charts/help-with-fees-staffapp/Chart.yaml
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-6203

RST-6203 paper savings

---

app/models/forms/benefits_evidence.rb
app/models/views/overview/income.rb
app/services/benefit_check_runner.rb
spec/models/forms/benefits_evidence_spec.rb
spec/models/views/overview/income_spec.rb
spec/services/benefit_check_runner_spec.rb

https://tools.hmcts.net/jira/browse/RST-6147

RST-6147 summary page refund benefit amount

---

app/models/hmrc_check.rb
config/settings.yml
spec/models/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6216

RST-6216 - Allow 0 total income on HMRC check

---

config/locales/en.yml

https://tools.hmcts.net/jira/browse/RST-5890

RST-5890 - Fixing error message typo

---

app/controllers/application_controller.rb
app/controllers/applications/process/savings_investments_controller.rb
app/controllers/benefit_overrides_controller.rb
spec/controllers/applications/process/savings_investments_controller_spec.rb
spec/controllers/benefit_overrides_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-6178

RST-6178 declaration page v2

---

app/models/views/overview/application.rb
app/models/views/overview/overview_helper.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6126

RST-6126 children split fix on summary page

---

app/models/concerns/refund_validatable.rb
app/models/forms/application/detail.rb
app/models/forms/application/fee_status.rb
charts/help-with-fees-staffapp/Chart.yaml
config/locales/en.yml
spec/models/forms/application/fee_status_spec.rb
spec/support/shared_examples/date_received_validation.rb

https://tools.hmcts.net/jira/browse/RST-6074
https://tools.hmcts.net/jira/browse/RST-6209

RST-6209 and RST-6074 - 3 month rule

---

lib/tasks/test.rake

https://tools.hmcts.net/jira/browse/RST-6253

RST-6253 Smoke tests only for now

---

app/lib/band_calculation_helper.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-6266 - discovered while running though scenarios

RST-6266 Fixing decimal threshold

---

app/models/hmrc_check.rb
spec/models/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6293

RST-6293 Fixing missing band calculation from HMRC check

---

README.md
config/initializers/devise.rb
config/locales/en.yml
spec/factories/users.rb
spec/features/password_reset_message_spec.rb
spec/features/user_can_accept_invite_spec.rb
spec/features/user_profile_spec.rb

https://tools.hmcts.net/jira/browse/RST-6267

RST-6267 password config 

---

features/step_definitions/nino_evidence_steps.rb

https://tools.hmcts.net/jira/browse/RST-6267

RST-6267 Fixing failing test

---

config/environments/production.rb

https://tools.hmcts.net/jira/browse/RST-6269

RST-6269 Securing cookies

---

app/lib/hmrc_cost_of_living.rb
spec/lib/hmrc_income_parser_spec.rb

https://tools.hmcts.net/jira/browse/RST-6370

RST-6370 Cost of living exception for February 2024

---

app/views/benefit_overrides/paper_evidence.html.slim
features/step_definitions/override_steps.rb
features/step_definitions/process_online_application_steps.rb
features/step_definitions/staff_steps.rb
features/support/page_objects/confirmation_page.rb

https://tools.hmcts.net/jira/browse/RST-6398

RST-6398 Updating failing feature tests

---

app/builders/application_builder.rb
app/controllers/api/submissions_controller.rb
app/models/views/overview/representative.rb
charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml
config/locales/en.yml
db/migrate/20240319133300_add_legal_representative_position_to_online_application_table.rb
db/migrate/20240319134944_add_position_to_representative.rb
db/schema.rb
spec/builders/application_builder_spec.rb
spec/factories/online_applications.rb
spec/factories/representatives.rb
spec/models/views/overview/representative_spec.rb

https://tools.hmcts.net/jira/browse/RST-6109

RST-6109 position in the organisation

---

app/models/applicant.rb
app/models/views/overview/applicant.rb
app/models/views/overview/online_applicant.rb
config/locales/en.yml
features/skip_ev_check_for_15_and_under.feature
features/step_definitions/skip_ev_check_for_15_and_under.steps.rb
features/step_definitions/summary_steps.rb
spec/models/views/overview/applicant_spec.rb
spec/models/views/overview/online_applicant_spec.rb

https://tools.hmcts.net/jira/browse/RST-6427

RST-6427 under 16

---

charts/help-with-fees-staffapp/Chart.yaml
features/step_definitions/staff_steps.rb
lib/tasks/test.rake

https://tools.hmcts.net/jira/browse/RST-6253

RST-6253 - Whole functional test run

---

Dockerfile
Gemfile.lock
charts/help-with-fees-staffapp/Chart.yaml

Minor gem updates and Helm update

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

Increasing memory for the db query.

More memory

---

app/models/views/overview/application.rb
spec/models/views/overview/application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6391

RST-6391 Fixing evidence check first summary page result

---

.rubocop.yml
Gemfile
Gemfile.lock
config/initializers/sentry.rb

Related to https://tools.hmcts.net/jira/browse/RST-6502

Adding profiling to Sentry

---

README.md
app/jobs/abandoned_application_purge_job.rb
spec/jobs/abandoned_application_purge_job_spec.rb

https://tools.hmcts.net/jira/browse/RST-6390

RST-6390 purge old applications

---

app/builders/finance_transactional_report_builder.rb
app/controllers/reports_controller.rb
app/controllers/users/file_download_controller.rb
app/helpers/file_download_helper.rb
app/jobs/finance_transactional_report_job.rb
app/jobs/raw_data_export_job.rb
app/jobs/report_file_job.rb
app/mailers/notify_mailer.rb
app/views/users/file_download/show.html.slim
config/locales/en.yml
config/routes.rb
spec/controllers/report/raw_data_controller_spec.rb
spec/controllers/reports_controller_spec.rb
spec/jobs/finance_transactional_report_job_spec.rb
spec/mailers/notify_mailer_spec.rb

https://tools.hmcts.net/jira/browse/RST-6502

RST-6502 FY report delayed 

---

run.sh

https://tools.hmcts.net/jira/browse/RST-6527

RST-6527 Refactoring run.sh to run bg worker

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

Mem tuning Update Chart.yaml

---

app/services/evidence_check_selector.rb
spec/services/evidence_check_selector_spec.rb

https://tools.hmcts.net/jira/browse/RST-6550

RST-6550 - Fixing HMRC skip check

---

.gitignore
README.md

https://tools.hmcts.net/jira/browse/RST-6489

RST-6489 Readme update

---

config/settings.yml
spec/models/forms/evidence/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6593
TO BE DEPLOYED on 1st May 2024

RST-6593 - Updating benefit per child amount

---

Jenkinsfile_CNP
app/controllers/users/passwords_controller.rb
charts/help-with-fees-staffapp/Chart.yaml
config/locales/devise.en.yml
db/migrate/20240430152321_add_last_password_reset_check_at_to_users.rb
db/schema.rb
spec/controllers/users/passwords_controller_spec.rb
spec/features/new_password_spec.rb

Limit number of new password request attempts in one minute time period

---

charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml

https://tools.hmcts.net/jira/browse/RST-6033

RST-6033 - Loading redis url from keystore

---

app/mailers/notify_mailer.rb
spec/mailers/notify_mailer_spec.rb

https://tools.hmcts.net/jira/browse/RST-6589

RST-6589 - Confirmation emails is now send to new address

---

Gemfile
Gemfile.lock
README.md
app/controllers/application_controller.rb
app/controllers/applications/process/confirmation_controller.rb
app/controllers/applications/process_controller.rb
app/controllers/evidence_controller.rb
app/controllers/home_controller.rb
app/controllers/part_payments_controller.rb
app/helpers/application_helper.rb
app/lib/path_storage.rb
app/views/layouts/application.html.slim
app/views/layouts/local-template.html.erb
charts/help-with-fees-staffapp/Chart.yaml
charts/help-with-fees-staffapp/values.yaml
config/settings.yml
features/support/env.rb
spec/lib/path_storage_spec.rb
spec/rails_helper.rb

https://tools.hmcts.net/jira/browse/RST-6033

RST-6033 navigation link

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb

https://tools.hmcts.net/jira/browse/RST-6643

RST-6643 Disabling back link for now

---

app/models/forms/online_application.rb
app/models/validators/date_received_validator.rb
config/locales/en.yml
features/support/page_objects/process_online_application_page.rb
spec/factories/online_applications.rb
spec/features/applications/processing_refund_application_spec.rb
spec/features/online_applications/evidence_check_spec.rb
spec/features/online_applications/staff_can_add_details_spec.rb
spec/models/forms/online_application_spec.rb
spec/support/shared_examples/date_received_validation.rb

https://tools.hmcts.net/jira/browse/RST-5659

RST-5659 date received

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/lib/path_storage.rb
spec/lib/path_storage_spec.rb

https://tools.hmcts.net/jira/browse/RST-6657

RST-6657 - Adding Sentry reporting for Redis link

---

app/models/forms/evidence/hmrc_check.rb
charts/help-with-fees-staffapp/Chart.yaml
config/settings.yml
spec/models/forms/evidence/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6638

RST-6638 - Updating additional income calculation

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js

https://tools.hmcts.net/jira/browse/RST-6224

RST-6224 - Replacing sass-rails with dart sass

---

Gemfile
Gemfile.lock
package-lock.json
package.json

Minor gem and accessible-autocomplete update

---

app/assets/javascripts/application.js
app/assets/javascripts/date_received_online.js
app/controllers/online_applications_controller.rb
app/helpers/online_application_helper.rb
app/models/forms/online_application.rb
app/models/validators/date_received_validator.rb
app/models/views/overview/details.rb
app/views/online_applications/edit.html.slim
config/locales/en.yml
db/migrate/20240528115411_add_discretion_to_online_application.rb
db/migrate/20240531091401_remove_discretion_details_from_online_application.rb
db/schema.rb
sonar-project.properties
spec/controllers/online_applications_controller_spec.rb
spec/models/forms/online_application_spec.rb
spec/models/views/overview/details_spec.rb

https://tools.hmcts.net/jira/browse/RST-6671

RST- 6671 date received override by discretion 

---

app/models/forms/online_application.rb
app/models/validators/date_received_validator.rb
spec/models/forms/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-6700

RST-6700 Updating 3 months validation rules

---

app/models/views/overview/details.rb
charts/help-with-fees-staffapp/Chart.yaml
spec/models/views/overview/details_spec.rb

https://tools.hmcts.net/jira/browse/RST-6718

RST-6718 Fixing missing attribute for discretion and online

---

charts/help-with-fees-staffapp/Chart.yaml

Version up

---

Gemfile
Gemfile.lock
Jenkinsfile_CNP

Mnor gem updates. Rack update.

Minor gem updates

---

app/mailers/notify_mailer.rb
app/models/online_application.rb
app/services/mail_service.rb
spec/mailers/notify_mailer_spec.rb
spec/models/online_application_spec.rb
spec/services/mail_service_spec.rb

https://tools.hmcts.net/jira/browse/RST-6759

RST-6759 email notification

---

app/builders/application_builder.rb
app/controllers/api/submissions_controller.rb

Rst-6614a Partner ni number added to application details

---

package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6806

RST-6806 Minor update to gov uk library

---

app/models/views/reports/raw_data_export.rb
charts/help-with-fees-staffapp/Chart.yaml
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-6836

RST-6836 Updating raw data extract

---

Gemfile
Gemfile.lock
app/models/views/overview/application.rb
charts/help-with-fees-staffapp/Chart.yaml
package-lock.json
package.json
spec/models/views/overview/application_spec.rb

- Minor rails update
- GovUk update 
- Minor gem updates

System - gem updates v43

---

package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6952

Rolling back govuk changes

---

app/models/concerns/hmrc_checkeable.rb
spec/models/evidence_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6964

RST-6964 Fixing total income method

---

app/models/evidence_check.rb
app/models/views/reports/hmrc_ocmc_data_export.rb
db/migrate/20241024124005_add_hmrc_income_to_evidence_check.rb
db/schema.rb
spec/models/evidence_check_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-6964

RST-6964 HMRC income export

---

charts/help-with-fees-staffapp/Chart.yaml
package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6961

RST-6961 GvUk lib update

---

README.md
app/policies/application_policy.rb
app/views/home/index.html.slim
db/schema.rb
spec/policies/application_policy_spec.rb

See [RST-6822](https://tools.hmcts.net/jira/browse/RST-6822)
Fix admin page completed application search bar.
Unit and feature tests updated

RST-6822 - fix admin completed application search bar

---

db/schema.rb

remove claim_type and form_type fields (added from RST-6822 in error)

Remove claim_type and form_type fields

---

app/models/hmrc_check.rb
lib/hmrc_missing_data.rb
spec/models/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-6990

RST-6990 - Fixing issue when no request data

---

package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6969

GovUK update to 5.7.1

---

config/environments/production.rb

https://tools.hmcts.net/jira/browse/RST-6961

Assets compile change

---

config/environments/production.rb
package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6961

RST-6961- Downgrading govuk version

---

package-lock.json
package.json

Reverts hmcts/hwf-staffapp#1895

Revert "GovUK update to 5.7.1"

---

config/environments/production.rb
package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-6961

RSt-6961 - Removing js compiler

---

app/helpers/guide_helper.rb
app/views/guide/index.html.slim
charts/help-with-fees-staffapp/Chart.yaml
features/staff_guides.feature
features/step_definitions/process_online_application_steps.rb
features/step_definitions/staff_guides_steps.rb
features/support/page_objects/guide_page.rb
spec/helpers/guide_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-6994

RST-6994 - Updated staff guides with new links

---

Jenkinsfile_CNP
lib/tasks/test.rake

To debug failing tests I would like to see a seed number which then I should be able to use locally.

Debugging failing tests

---

features/evidence.feature
features/notification_banner.feature
features/sign_in.feature
features/step_definitions/sign_in_steps.rb
features/support/page_objects/sign_in_page.rb
features/your_feedback.feature

Removing old tests and removing tags

---

app/helpers/guide_helper.rb
charts/help-with-fees-staffapp/Chart.yaml
features/step_definitions/staff_guides_steps.rb
spec/helpers/guide_helper_spec.rb

https://tools.hmcts.net/jira/browse/RST-7027

RST-7027 - Updated staff guidance URL

---

app/views/applications/process/details/index.html.slim
charts/help-with-fees-staffapp/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7030

RST-7030 Fee amount format in Application Details

---

app/models/online_application.rb
app/views/online_applications/edit.html.slim
spec/factories/online_applications.rb
spec/features/online_applications/staff_can_add_details_spec.rb
spec/models/online_application_spec.rb

https://tools.hmcts.net/jira/browse/RST-7029

RST-7029 Display partner info

---

.rubocop.yml

Fixing rubocop issues after master merge

Don't force expect on params

---

app/models/views/overview/online_application_view.rb
app/views/online_applications/_post_ucd_show.html.slim
spec/models/views/overview/online_application_view_spec.rb

https://tools.hmcts.net/jira/browse/RST-7111
#bugfix

RST-7111 - Fixing nil issue with under 16 and kids section

---

app/views/online_applications/edit.html.slim
spec/features/online_applications/staff_can_add_details_spec.rb

https://tools.hmcts.net/jira/browse/RST-7058

RST-7058 - Removing partner info

---

app/assets/stylesheets/application.scss
charts/help-with-fees-staffapp/Chart.yaml
package-lock.json
package.json

https://tools.hmcts.net/jira/browse/RST-7098

RST-7098 Updated GovUK Frontend to 5.8.0

---

app/views/applications/process/partner_informations/index.html.slim
charts/help-with-fees-staffapp/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7116

RST-7116 - Remove Partner NI hint text

---

app/views/applications/process/details/index.html.slim
app/views/applications/process/incomes/index.html.slim
app/views/applications/process/partner_informations/index.html.slim
app/views/applications/process/personal_informations/index.html.slim
app/views/applications/process/representative/index.html.slim
app/views/home/index.html.slim
app/views/online_applications/edit.html.slim

https://tools.hmcts.net/jira/browse/RST-7014

7014 fire wall on special characters instead of validation

---

Gemfile.lock
app/views/applications/process/details/index.html.slim
app/views/applications/process/partner_informations/index.html.slim
app/views/applications/process/personal_informations/index.html.slim
app/views/applications/process/representative/index.html.slim
app/views/home/index.html.slim
app/views/online_applications/edit.html.slim
app/views/shared/savings/_amount.slim

https://tools.hmcts.net/jira/browse/RST-7157

RST 7517 Validation for inputs to disallow any consecutive special characters

---

app/views/shared/_application_summary.html.slim
app/views/shared/_notifications.html.slim
charts/help-with-fees-staffapp/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7158

RST-7158 - Only show representative details when present

---

app/models/views/overview/online_saving.rb
app/models/views/overview/savings_and_investments.rb
app/views/online_applications/_post_ucd_show.html.slim
app/views/shared/_application_summary.html.slim
spec/models/views/overview/online_saving_spec.rb
spec/models/views/overview/savings_and_investments_spec.rb

https://tools.hmcts.net/jira/browse/RST-7169

RSt-7169 Fixing savings on summary page

---

app/models/forms/application/fee_status.rb

https://tools.hmcts.net/jira/browse/RST-7159

RST 7159 Change date received limit from 2 to 3 years and edit the error message

---

app/views/shared/_processed_summary.html.slim

https://tools.hmcts.net/jira/browse/RST-7061

RST-7061 Reordering summary log

---

Gemfile
Gemfile.lock
app/builders/finance_report_builder.rb
app/builders/finance_transactional_report_builder.rb
app/models/views/reports/applicants_per_fy_export.rb
app/models/views/reports/audit_personal_data_report.rb
app/models/views/reports/hmrc_ocmc_data_export.rb
app/models/views/reports/hmrc_purged_export.rb
app/models/views/reports/income_claims_data_export.rb
app/models/views/reports/ocmc_export_helper.rb
app/models/views/reports/raw_data_export.rb
app/views/reports/public.html.slim
charts/help-with-fees-staffapp/Chart.yaml
spec/builders/finance_transactional_report_builder_spec.rb
spec/models/views/reports/audit_personal_data_report_spec.rb
spec/models/views/reports/finance_report_data_row_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
spec/models/views/reports/hmrc_purged_export_spec.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-7164

RST-7164 - Updated all empty blank fields to 'N/A'

---

app/views/shared/_remission_type_post_ucd.html.slim
charts/help-with-fees-staffapp/Chart.yaml
spec/factories/applications.rb
spec/features/evidence-checks/post_ucd_evidence_check_summary_spec.rb

https://tools.hmcts.net/jira/browse/RST-7140

RST-7140 - Fixed check details page showing wrong message

---

README.md
app/models/applicant.rb
app/models/application.rb
app/models/benefit_check.rb
app/models/detail.rb
app/models/dev_note.rb
app/models/evidence_check.rb
app/models/hmrc_check.rb
app/models/office.rb
app/models/online_application.rb
app/models/part_payment.rb
app/models/saving.rb
db/migrate/20250310135503_create_dev_notes.rb
db/schema.rb
spec/models/dev_note_spec.rb

https://tools.hmcts.net/jira/browse/RST-7160

RST-7160 notes for record changes

---

Gemfile.lock
app/services/evidence_check_selector.rb

Minot gem update and refactor

---

Gemfile
Gemfile.lock

HMRC API gem update

---

app/lib/band_base_calculation.rb
app/lib/band_calculation_helper.rb
app/lib/band_calculation_income.rb
spec/lib/band_base_calculation_spec.rb

https://tools.hmcts.net/jira/browse/RST-7242

RST-7242 - Updating premium band check and adding more tests

---

app/views/benefit_overrides/paper_evidence.html.slim
charts/help-with-fees-staffapp/Chart.yaml
config/locales/en.yml
spec/features/applications/processing_refund_application_spec.rb
spec/support/admin_application_steps.rb

https://tools.hmcts.net/jira/browse/RST-7259

RST-7259 - Benefits page content update

---

Gemfile.lock
app/helpers/common_scopes.rb
app/helpers/result_helper.rb
app/lib/income_calculation.rb
app/models/views/reports/hmrc_ocmc_data_export.rb
app/models/views/reports/public_submission_data.rb
spec/controllers/offices_controller_spec.rb
spec/controllers/processed_applications_controller_spec.rb
spec/helpers/result_helper_spec.rb
spec/models/forms/application/detail_spec.rb
spec/models/forms/application/fee_status_spec.rb
spec/models/forms/online_application_spec.rb
spec/models/views/application_result_spec.rb
spec/models/views/overview/application_spec.rb
spec/services/benefit_check_runner_spec.rb
spec/services/resolver_service_spec.rb

Gem updates v14

---

package.json
yarn.lock

Frontend libs update

---

README.md
app/helpers/hmrc_check_helper.rb
app/models/forms/evidence/additional_income.rb
app/models/forms/evidence/hmrc_check.rb
app/views/evidence/hmrc/show.html.slim
config/settings.yml
spec/helpers/hmrc_check_helper_spec.rb
spec/models/forms/evidence/hmrc_check_spec.rb

https://tools.hmcts.net/jira/browse/RST-7015

RST-7015 Additional income now based on date range

---

Gemfile
Gemfile.lock
README.md
app/models/views/reports/hmrc_ocmc_data_export.rb
charts/help-with-fees-staffapp/Chart.yaml
features/savings_investments.feature
features/step_definitions/process_online_application_steps.rb
features/step_definitions/savings_investments_steps.rb
features/support/capybara_driver_helper.rb
features/support/env.rb
features/support/saucelabs/browsers.yml
spec/models/views/reports/datashare_export_spec.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-7265

RST-7265 - Applications by Court fields update

---

README.md

Asset precompile rebuild trigger

Deploye trigger

---

README.md
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RST-7327
Attempting to force rebuild of the asset bundle

RST-7327 js bundle

---

app/views/layouts/local-template.html.erb
webpack.config.js

https://tools.hmcts.net/jira/browse/RST-7327

RSt-7327 - Updating js bundle name

---

app/models/forms/application/detail.rb
app/models/forms/online_application.rb
config/locales/en.yml
spec/models/forms/application/detail_spec.rb

https://tools.hmcts.net/jira/browse/RST-7280

RST-7280 Minimal fee 3

---

app/models/forms/application/income_kind_applicant.rb
app/views/applications/process/income_kind_applicants/index.html.slim
charts/help-with-fees-staffapp/Chart.yaml
config/locales/en.yml
spec/models/forms/application/income_kind_applicant_spec.rb

https://tools.hmcts.net/jira/browse/RST-7273

RST-7273 - Types of income validation

---

app/controllers/applications/process/benefits_controller.rb
app/services/dwp_monitor.rb
spec/controllers/applications/process/benefits_controller_spec.rb
spec/services/benefit_check_runner_spec.rb

https://tools.hmcts.net/jira/browse/RST-7337

RST-7337 Disable benefits call when message is offline

---

README.md
charts/help-with-fees-staffapp/Chart.yaml

Deploy trigger

---

app/controllers/applications/process/benefits_controller.rb
spec/controllers/applications/process/benefits_controller_spec.rb

https://tools.hmcts.net/jira/browse/RST-7337

RSt-7337 - Fixing redirect for no benefits

---

app/services/benefit_check_runner.rb
app/services/online_benefit_check_runner.rb
spec/services/benefit_check_runner_spec.rb
spec/services/online_benefit_check_runner_spec.rb

https://tools.hmcts.net/jira/browse/RST-7337

RST-7337  - Logging benefit check calls

---

app/services/benefit_check_runner.rb
spec/services/benefit_check_runner_spec.rb

https://tools.hmcts.net/jira/browse/RST-7338

RST-7338 No benefits check for no answer when digital

---

app/models/views/reports/hmrc_ocmc_data_export.rb
charts/help-with-fees-staffapp/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7238

RST-7238 - Report by Court Update

---

app/models/views/reports/hmrc_ocmc_data_export.rb
app/models/views/reports/raw_data_export.rb
spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
spec/models/views/reports/raw_data_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-7347

Rst-7347 benefit override report

---

app/controllers/report/ocmc_controller.rb
app/controllers/reports_controller.rb
app/jobs/ocmc_export_job.rb
app/models/forms/finance_report.rb
app/models/views/reports/hmrc_ocmc_data_export.rb
app/models/views/reports/ocmc_export_helper.rb
app/views/reports/ocmc_report.html.slim
app/views/reports/raw_data.html.slim
app/views/shared/_report_by_court.html.slim
charts/help-with-fees-staffapp/Chart.yaml
config/locales/en.yml
spec/controllers/report/ocmc_controller_spec.rb
spec/jobs/ocmc_export_job_spec.rb
spec/models/views/reports/datashare_export_spec.rb

https://tools.hmcts.net/jira/browse/RST-7352

RST-7352 - Applications by court update

---

app/views/guide/index.html.slim
charts/help-with-fees-staffapp/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7331

RST-7331 - Staff guides page banner

---

app/controllers/benefit_overrides_controller.rb
app/controllers/online_application_benefits_controller.rb
app/models/forms/online_application.rb
app/models/views/confirmation/result.rb
db/migrate/20250604102650_add_dwp_evidence_failed_to_online_application.rb
db/schema.rb
features/benefit_checker.feature
features/step_definitions/benefit_checker_steps.rb
features/unprocessed_applications_when_dwp_is_down.feature
spec/controllers/benefit_overrides_controller_spec.rb
spec/controllers/online_application_benefits_controller_spec.rb
spec/features/admin_can_manage_the_message_info_spec.rb
spec/models/forms/online_application_spec.rb
spec/models/views/confirmation/result_spec.rb

https://tools.hmcts.net/jira/browse/RST-7368

RST-7368  Disabling benefit fail redirect

---

.rubocop.yml
Gemfile.lock
app/views/layouts/local-template.html.erb
package.json
webpack.config.js
yarn.lock

Gem updates v18

---

app/views/layouts/local-template.html.erb
config/application.rb
webpack.config.js

https://tools.hmcts.net/jira/browse/RST-7425

RST-7425 - Frontend reload fix

---

README.md
config/locales/letters_en.yml
config/locales/new_letters_en.yml

https://tools.hmcts.net/jira/browse/RST-7361

RSt-7361 - Benefit letter template typo fix

---

app/builders/application_builder.rb
spec/builders/application_builder_spec.rb

https://tools.hmcts.net/jira/browse/RST-7475

RST-7475 - Assigning application type for online applications

---

app/helpers/application_helper.rb
app/views/applications/process/details/index.html.slim
app/views/applications/process/fee_status/index.html.slim
app/views/applications/process/partner_informations/index.html.slim
app/views/online_applications/edit.html.slim
config/locales/en.yml

https://tools.hmcts.net/jira/browse/RST-7602

RST-7602 Date hints

---

Gemfile
Gemfile.lock
yarn.lock

Gem updates v34
