app/views/dwp_checks/show.html.slim
This view included a call to a previous method, it now calls the correct function.
=> Fix the call to DWP checker

app/controllers/dwp_checks_controller.rb, app/views/dwp_checks/new.html.slim, config/initializers/date_time.rb, spec/controllers/dwp_checks_controller_spec.rb
Users were getting errors when inputting two digit years
Pivotal story https://www.pivotaltracker.com/story/show/91439958
Added tests and handlers to ensure wider type of inputs accepted.
=> Refactor date inputs for DWP check

app/models/office.rb, app/models/user.rb, app/views/users/invitations/new.html.slim, db/migrate/20150417125341_users_offices.rb, db/schema.rb, db/seeds.rb, spec/features/user_invite_spec.rb
Every user should be assigned to an office. The idea is to have an admin
per office so that when that admin creates/invites a user, that user
inherits that admin's office assignment.
=> Allow Admins to assign Users to an Office

app/controllers/ping_controller.rb, app/services/deployment.rb, config/routes.rb, spec/routing/ping_routing_spec.rb
As per ticket:
https://www.pivotaltracker.com/story/show/93418100
The idea is that 2nd line support crew requires this end point for all
the apps in order to make the monitoring easier.
=> Added '/ping.json'

app/models/user.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/features/user_invite_spec.rb, spec/models/user_spec.rb
So that nobody outside of those domains can be invited to the
application.
Right now it's only allowing: (hmcts.gsi|digital.justice).gov.uk.
=> Added white listed email domains

Gemfile, app/controllers/dwp_checks_controller.rb, app/models/dwp_check.rb, app/services/process_dwp_service.rb, spec/controllers/dwp_checks_controller_spec.rb, spec/features/perform_benefit_check_spec.rb, spec/models/dwp_check_spec.rb, spec/services/process_dwp_service_spec.rb
The front end should generate a unique value in the format:
username
timestamp in YYMMDDHHSS
unique id
Which will look like bsmith@YYMDDHHSS.some-id. 
It should be up to 50 characters long, as that is the constraint imposed by DWP API.
=> New - Create unique identifier for API

app/models/user.rb, spec/models/user_spec.rb
Currently we should only allow emails from white listed domains. This
change introduces meaningful and descriptive error messages, so that
when the admin users add a non MOJ approved email, they will know what
the issue is.
The ticket for this PR is [here](https://www.pivotaltracker.com/story/show/93001180).
=> Added error message for non white listed emails

app/assets/javascripts/income_calculator.coffee, app/assets/stylesheets/errors.scss, app/assets/stylesheets/r2_calculator.scss, app/models/user.rb, app/views/calculator/income.html.slim, app/views/dwp_checks/new.html.slim, app/views/users/edit.html.slim, app/views/users/invitations/edit.html.slim, app/views/users/invitations/new.html.slim, app/views/users/passwords/new.html.slim, app/views/users/sessions/new.html.slim, app/views/users/shared/_links.html.slim, config/locales/devise_invitable.en.yml, config/locales/en.yml, spec/features/perform_an_income_check_spec.rb, spec/features/user_can_accept_invite_spec.rb, spec/models/user_spec.rb
Updated styling in line with [DWP // Global // Error messaging ticket](https://www.pivotaltracker.com/story/show/93654782)
* Created validation messages and labels in locale file
Updated user screens
* moved to foundation base
* updated text and labels inline with copy changes
* moved validation and display texts into locale file
* updated tests to reflect text changes
=> Error message update

Gemfile, Gemfile.lock, app/controllers/dwp_checks_controller.rb, app/models/dwp_check.rb, app/views/dwp_checks/new.html.slim, config/locales/en.yml, spec/controllers/dwp_checks_controller_spec.rb, spec/factories/dwp_checks.rb, spec/models/dwp_check_spec.rb, spec/services/process_dwp_service_spec.rb
Prevent the error popping up when an invalid date is entered for the date of birth of for the date_application_made.
Also added constraints such as 16 years being the minimum age and 120 years being the maximum age of an applicant. The logic is that we've agreed as a team to have 120 be the maximum age. For minimum age, the reason it's 16 is because you get your national insurance card at that age.
=> 94407712 date validation error on dwp check form

app/assets/stylesheets/navigation.scss
The crest should be indented when
screen is at medium and lower
=> Crest style update

Gemfile, Gemfile.lock, app/assets/stylesheets/pagination.sass, app/controllers/home_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users_controller.rb, app/models/ability.rb, app/models/dwp_check.rb, app/models/office.rb, app/models/user.rb, app/views/home/_manager.html.slim, app/views/home/index.html.slim, app/views/layouts/_toolbar.html.slim, app/views/layouts/application.html.slim, app/views/users/edit.html.slim, app/views/users/index.html.slim, app/views/users/invitations/new.html.slim, app/views/users/show.html.slim, config/application.rb, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/features/user_invite_spec.rb, spec/models/office_spec.rb, spec/models/user_spec.rb, spec/views/layouts/_toolbar.html.slim_spec.rb, spec/views/users/invitations/new.html.slim_spec.rb
Allow admins to create managers per-office
A manager can:
* invite users and managers to the same office as themselves
* edit users from their own office, fields:
- name, email, role and office
* see a list of DWP checks on their dashboard that have 
been undertaken in their office
* they cannot see or amend users in other offices, or admins 
within their own office
**Note** : When a user is moved into another office, the manager
is shown the email addresses for managers in the new office
=> Create manager role

app/controllers/home_controller.rb
Admins should see graphs of dwp checks per office
The generation of the graph data was removed 
in an over enthusiastic refactoring exercise
=> Admin Graph fix

db/migrate/20150609104815_user_office_constraint.rb, db/schema.rb
Prevent the user from being created without being assigned to an
office. Added the constraint in the database schema.
=> Added a constraint for User's Office

app/controllers/dwp_checks_controller.rb, app/services/process_dwp_service.rb, lib/exceptions.rb, spec/services/process_dwp_service_spec.rb
When a user searches using incorrect data
the system should return them to the input 
screen with a warning and allow them to 
amend the data.
[finishes #94226772]
=> Handle undetermined results

app/assets/stylesheets/base.scss, app/assets/stylesheets/feedback.scss, app/controllers/offices_controller.rb, app/models/jurisdiction.rb, app/models/office.rb, app/models/office_jurisdiction.rb, app/views/offices/_form.html.slim, app/views/offices/index.html.slim, app/views/offices/show.html.slim, db/migrate/20150619115804_create_join_table_office_jurisdiction.rb, db/schema.rb, db/seeds.rb, spec/factories/jurisdictions.rb, spec/models/jurisdiction_spec.rb, spec/models/office_jurisdiction_spec.rb, spec/models/office_spec.rb, spec/rails_helper.rb, spec/views/offices/edit.html.slim_spec.rb, spec/views/offices/index.html.slim_spec.rb, spec/views/offices/new.html.slim_spec.rb
Create a link table between office and jurisdiction
* many-to-many link between the two models
* add jurisdiction check boxes to the office _form
* add jurisdiction display methods
* display the jurisdiction count on office index
Changes to existing objects
* a jurisdiction can be displayed as: name, name (abbr) and abbr only
* an office can have zero to many jurisdictions
* the office form views display jurisdiction checkboxes
=> Link office and jurisdictions

Gemfile.lock
Even though it's just an issue in development, it's good to silence
Gemnasium alerts also.
This is the vulnerability description:
https://groups.google.com/forum/#!topic/ruby-security-ann/lzmz9_ijUFw
=> Vulenrability fix for web-console gem

db/seeds.rb
Staging and Demo had different Office.id values for the bristol
office.  This allows each environment to locate the correct ID and
link it.
=> Update seed data

Gemfile.lock
As per http://seclists.org/oss-sec/2015/q2/818
redcarpet has a vuln. This upgrade fixes it.
=> Upgraded redcarpet gem due to vuln

spec/controllers/users_controller/admin_user_spec.rb
The failing test (on TravisCI only):
```
./spec/controllers/users_controller/admin_user_spec.rb:110
```
with error:
```
1) UsersController admin user PUT #update with valid params and a new email assigns the requested user as @user
Failure/Error: create_list :user, 3, office: create(:office)
ActiveRecord::RecordInvalid:
Validation failed: Name has already been taken
```
Trying to create the users with 'create_list', but omitting the office
creation, to see how it fares.
=> Testing a hypothesis

config/environments/production.rb
Use secure cookies.
This was one of the issues that was highlighted by the security
audit as done by @ohmygauss. So turning it on.
=> Enforce all access to the app over SSL

app/views/users/mailer/invitation_instructions.html.slim
The user id should not be included in the invitation url.
It turns out that it isn't needed anyway.  Removing the 
resource and leaving the token is all that's required.
[finishes #94841546]
=> Fix for user id in invitation url

config/environments/production.rb
Reverts ministryofjustice/fr-staffapp#163
This is due to enforcement of secure cookies on **everything** which also includes **ping.json** which is not what we want. So reverting this change as the cookies will be secured by nginx.
=> Revert "Enforce all access to the app over SSL"

spec/factories/offices.rb
* reduce likelihood of office name duplication
This should prevent recurrences of the following error:
Failure/Error: let(:office)  { create :office, jurisdictions: create_list(:jurisdiction, 3) }
ActiveRecord::RecordInvalid:
Validation failed: Name has already been taken
=> Updated office factory

Dockerfile
These tasks must be separate because we need rails to generate the
manifest for the assets before we create the static pages.
=> Split assets generate and static page tasks

app/controllers/dwp_checks_controller.rb, spec/controllers/dwp_checks_controller_spec.rb
When the user tries to look up some made up DWP check, it would return an error with 500 status code. Which means that the app would actually take the invalid input and do a database query with it. Which is not what we want.
This change prevents that by only allowing the valid format of the DWP check reference to be looked up.
=> Return 404 instead of 500

.rubocop.yml, app/controllers/calculator_controller.rb, app/controllers/dwp_checks_controller.rb, app/controllers/feedback_controller.rb, app/controllers/home_controller.rb, app/controllers/offices_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users_controller.rb, app/models/ability.rb, app/models/dwp_check.rb, app/models/r2_calculator.rb, app/models/user.rb, app/services/process_dwp_service.rb, lib/settings.rb
Changed the RuboCop setting so that the keywords are indented instead of
outdented. This applies to `private', `protected', ...
=> Indent instead of outdent of keywords

config/initializers/markdown_handler.rb
Markdown was rendering, not executing, a script tag
the filter_html switch was the cause.
Removed the tag to ensure proper display
The JS was highlighting the page choice on the 
navigation bar.  This will be removed anyway once the 
design is updated.
=> Fixed markdown rendering bug

app/controllers/users_controller.rb, app/views/users/edit.html.slim, config/locales/en.yml, spec/controllers/users_controller/manager_user_spec.rb, spec/controllers/users_controller/standard_user_spec.rb, spec/controllers/users_controller/user_jurisdictions_spec.rb
As discussed between @kelliematheson and @colinbruce.
Users will only be shown jurisdictions currently selected 
by office managers.
If managers have not chosen any jurisdictions, users are 
shown a warning message.
=> Updating user jurisdiction management

app/views/users/edit.html.slim
It should be the current_users elevated status that is checked
not the user being edited
=> Fix user bug

app/controllers/users_controller.rb, spec/controllers/users_controller/manager_user_spec.rb
Allows managers to update the office of a staff member
* It redirects to the list of their remaining users and displays
a flash message of where the user has transferred to.
* Replaced all references to User.first with explicit objects
=> Updated manager/user editing

.travis.yml
When building jobs on Travis CI, this message shows up:
`This job ran on our legacy infrastructure. Please read our docs on how
to upgrade'
The link to the document is: http://j.mp/1CtCCRO
Trying it out with this commit.
But still not sure if I have to remove all the mentions of **sudo** from
**.travis.yml**.
=> Faster TravisCI builds

app/views/users/edit.html.slim, spec/controllers/users_controller/manager_user_spec.rb, spec/features/prevent_managers_from_downgrading_themselves_to_user_role_spec.rb
Don't allow a manager to change their role to user.
Added the examples for the scenario and removed the previous scenario
which did allow the manager to change his role.
=> Prevent the manager from changing their role

app/assets/stylesheets/application.scss, app/assets/stylesheets/dwp_checks.scss, app/assets/stylesheets/r2_calculator.scss, app/assets/stylesheets/result_tables.scss, app/views/calculator/income.html.slim, app/views/dwp_checks/show.html.slim
Result tables were wider than the result blocks
https://www.pivotaltracker.com/story/show/95699558
=> Result table display fix

app/controllers/users_controller.rb, spec/controllers/users_controller/manager_user_spec.rb, spec/controllers/users_controller/standard_user_spec.rb
Privilege escalation prevention branch.
Workarounds for: 
* a user to prevent them from escalating their own privileges
* a manager to prevent them from escalating their user's or their own priviledges
=> Privilege escalation prevention

app/models/application.rb, app/views/applications/build/savings_investments.html.slim
Add the summary block to the foot of the 
savings and investment page.
This needed to access the applicant age 
from the model, so it was made public.
=> Savings summary

Gemfile.lock, app/controllers/users/invitations_controller.rb, spec/features/user_invite_spec.rb
When an elevated user creates a new user, an enters an incorrect email
it was rendering a 500 error page.
This fix redirects them to the previous screen with the appropriate
error message.
=> Incorrect email error fix

app/views/layouts/_toolbar.html.slim, app/views/offices/show.html.slim, app/views/users/edit.html.slim, app/views/users/index.html.slim, app/views/users/show.html.slim, config/locales/en.yml, spec/controllers/users_controller/admin_user_spec.rb, spec/features/user_profile_spec.rb, spec/views/layouts/_toolbar.html.slim_spec.rb
- Used term ‘log in’, now use ‘sign in’
- Used term ‘users’, now use ‘staff’
- Used term ‘edit’, now use ‘change’
- Used term ‘Invite’, now use ‘add’
- Used term ‘delete’, now use ‘remove’
Because it is more plain English
=> Update copy on various pages

app/assets/stylesheets/foundation_and_overrides.scss, app/views/calculator/income.html.slim, app/views/dwp_checks/new.html.slim, app/views/users/invitations/edit.html.slim, app/views/users/invitations/new.html.slim, app/views/users/passwords/edit.html.slim, app/views/users/passwords/new.html.slim, app/views/users/sessions/new.html.slim
- Before the button sizes were very small and hard to read, now they
are larger and easier to read.
- Before the column widths for the benefits check and income check were
narrow and didn’t match the prototype. Now the column widths are wider
and match the prototype and other form pages.
- Before the form label text colour was light and very similar to the
hint text colour. Now the form label text colour is darker and there is
more distinction from the hint text colour.
=> Update button sizes, column widths, text colour

app/views/home/index.html.slim, app/views/layouts/application.html.slim, spec/views/home/index.html.slim_spec.rb
- Before users would not see the sign in link in the top right and
would click the support link in the body.
- Now a sign in button has been added to the body and information about
contacting their manager before contacting support.
=> Update the homepage to include sign in link and info to contact manager

app/views/offices/edit.html.slim, app/views/offices/index.html.slim, app/views/users/edit.html.slim, app/views/users/show.html.slim, spec/features/user_profile_spec.rb, spec/views/offices/index.html.slim_spec.rb
Before said ‘edit’, now says ‘change’
Before said ‘default’, now says ‘main’
Before said ‘user’, now says ‘staff’
=> Update copy on the office and user sections

app/assets/javascripts/income.coffee, app/models/application.rb, app/views/applications/build/income.html.slim, app/views/applications/build/summary.html.slim, config/locales/en.yml, spec/javascripts/income_spec.coffee, spec/models/applications/income_spec.rb
Updates to the income page inline with the prototype
* re-uses the coffeescript for handling radio button show hide
* updates labels and error massages to use the locale file
* updated the view to always show the income field and make the 
children question optional depending on the dependents response
=> Update application form income page

app/views/applications/build/benefits.html.slim, app/views/applications/build/savings_investments.html.slim
Added status field to views, this allows the submission of the form 
with no other fields completed.  This means that validations will fire
and return an error enforcing the completion of the question.
=> Allow submission of 'empty' forms

app/assets/stylesheets/base.scss, app/controllers/applications/build_controller.rb, app/models/application.rb, app/views/applications/build/savings_investments.html.slim, app/views/applications/build/summary.html.slim, app/views/applications/partials/_deleted.html.slim, config/locales/en.yml, db/migrate/20150817083012_add_high_threshold_exceeded_to_application.rb, db/schema.rb, spec/controllers/applications/build_controller_spec.rb, spec/factories/applications.rb, spec/models/application_spec.rb, spec/models/applications/benefits_result_spec.rb, spec/models/applications/benefits_spec.rb, spec/models/applications/savings_investments_spec.rb
When an applicant has a partner and either of them is over 61
there is an increased savings threshold of £16,000.
This adds input questions to the savings_and_investments view,
processes the inputs in the model and updates the routing to, and
display of, the summary page.
It also improves the setting of outcome to ensure the summary is
correctly displayed.
=> Handle increased limits for partner applications

Gemfile, Gemfile.lock, app/models/application.rb, app/views/applications/build/summary.html.slim, lib/income_calculator.rb, spec/controllers/applications/build_controller_spec.rb, spec/controllers/users_controller/admin_user_spec.rb, spec/controllers/users_controller/manager_user_spec.rb, spec/controllers/users_controller/standard_user_spec.rb, spec/features/applications/application_form_application_details_spec.rb, spec/features/applications/application_form_personal_details_spec.rb, spec/features/applications/application_form_stories_spec.rb, spec/models/application_spec.rb, spec/rails_helper.rb, spec/support/application_form_macros.rb, spec/support/personae.rb
To allow testing of on-page javascript as well as end-to-end testing of the application form
* Added database-cleaner and configured rails_helper to:-
* remove transactional_fixtures
* clean the database
* auto-load support files
* Removed explicit loading of support files from previous tests
* Created persona files for future use and standard tests
* Created tests for the personal and application details pages in isolation
* Created end-to-end tests for some of the available paths through the form.
* added fixes for issues picked up by the e-to-e tests
=> Implement JS feature tests

app/controllers/users_controller.rb, app/helpers/flash_message_helper.rb, app/models/office.rb, spec/controllers/users_controller/manager_user_spec.rb, spec/features/manager_transfers_user_spec.rb, spec/models/office_spec.rb
This removes the `html_safe` call from `Office` model and moves that particular presentation logic to a helper.
=> Fix xss on office model

app/views/applications/build/confirmation.html.slim, spec/features/applications/remission_confirmation_spec.rb
Changed the copy for full remissionon on the confirmation page.
Why? Got told to do it and the content person writes the copy.
Also :bug: [102568132](https://www.pivotaltracker.com/story/show/102568132).
=> Copy change on confirmation page

app/controllers/home_controller.rb, app/views/home/_manager.html.slim, app/views/home/index.html.slim, app/views/layouts/_welcome_banner.html.slim, spec/controllers/home_controller_spec.rb, spec/features/applications/application_form_stories_spec.rb, spec/views/home/index.html.slim_spec.rb
When the user is not signed in & visits the home page they should be
redirected to log in. 
Why? Because this is how Kellie designed it to work.
=> Redirect non-signed in users to login page

.travis.yml
The idea is to have RuboCop run it's checks first because it's faster
than all the other tests. And if it is going to fail, it's better that
we know those failures straight away instead of waiting for all the
RSpec tests to pass and only then to be notified of the Ruby style
violations by RuboCop.
=> Run RuboCop first

.travis.yml
Since Rails 4.1 this line in rails_helper:
ActiveRecord::Migration.maintain_test_schema!
checks if there are any pending migrations and complains if there are.
Otherwise just load the schema.
=> Using 'rake db:schema:load' for TravisCI

app/controllers/dwp_checks_controller.rb, spec/controllers/dwp_checks_controller_spec.rb, spec/features/perform_benefit_check_spec.rb
The users should not be able to access '/dwp_check'.
I've left the examples by commenting them out: /it/(xit|pending)/,
because there will be a ticket in the backlog to deal with this
properly. This is just a band aid fix until tomorrow.
=> Prevent the users from access '/dwp_check'

app/models/application.rb, spec/features/applications/over_61_applicants_can_complete_form_spec.rb
'Next' button doesn't work on savings and investment page [Ticket](https://www.pivotaltracker.com/story/show/103322556)
---
Fix to allow progression past savings investments when applicant is over 61
=> Next 16000

spec/features/applications/application_form_application_details_spec.rb, spec/features/applications/application_form_stories_spec.rb, spec/features/applications/application_savings_and_investments_spec.rb, spec/features/applications/benefit_results_are_rendered_spec.rb, spec/features/applications/change_from_r1_to_r2_spec.rb, spec/features/applications/confirmation_is_rendered_spec.rb, spec/features/applications/over_61_applicants_can_complete_form_spec.rb, spec/features/applications/remission_confirmation_spec.rb, spec/features/perform_benefit_check_spec.rb, spec/support/dwp_api_response.rb, spec/support/dwp_response.rb
Trimmed away at a stub request that is used frequently.
There are other instances of this stub being used, but they have more detailed responses configured. It might be an option to look at them and see if they need to be trimmed down.
=> DWP stub trim

app/models/application.rb, lib/fee_threshold.rb, spec/lib/fee_threshold_spec.rb
Added the ability to work out the fee threshold band even when the fee
is supplied as a decimal value. Previously it only handled whole
numbers.
Also, passing in just the fee instead of the whole Application model.
=> Fee threshold rounding

app/models/application.rb, spec/models/application_spec.rb
When entering a national insurance number with spaces, an error is shown. 
This PR fixes that by removing the whitespace before validation.
delivers [#103088140](https://www.pivotaltracker.com/story/show/103088140)
=> Remove spaces from NI number

lib/tasks/rubocop.rake
When the vagrant box was started locally, the rubocop rake task 
would block __any__rake task.  This prevented rake db:migrate
running.
This fix prevents rubocop running when DOCKER_STATE = 'vagrant', 
but still runs if rake is used locally.
=> Fix for rubocop blocking vagrant provision

app/controllers/home_controller.rb, app/models/benefit_check.rb, app/views/home/_admin.html.slim, db/migrate/20150921084620_add_timestamps_to_benefit_check.rb, db/schema.rb, spec/controllers/home_controller_spec.rb, spec/models/benefit_check_spec.rb
Following the release of the application form, the checks are recorded differently
This allows us to track the new benefit checks and display the admin 
graphs for new dwp checks.
=> Updated admin dashboard

db/seeds.rb, run.sh
Local vagrant deploy was working, but the database was not being seeded.
To fix this: 
* I updated the seed file to create offices with pre-selected jurisdictions, this satisfies the
new validation created by the out-of-box experience feature
* Made sure that the run.sh file runs migrate _before_ attempting to seed the data
=> Making vagrant work

app/controllers/applications/build_controller.rb, app/models/forms/benefit.rb, app/views/applications/build/benefits.html.slim, config/locales/en.yml, spec/models/forms/benefit_spec.rb
Created Benefit model which only handles the benefit page form. This is
done as part of the refactoring task on the monolithic Application
model.
Also removed the 'status' attribute from the benefits page and addded a
hidden field, this is because otherwise the form would not submit any of
the fields from the radio buttons.
=> Eased out benefits page to a form object

app/controllers/users_controller.rb, app/views/users/show.html.slim, spec/controllers/users_controller/admin_user_spec.rb
Update user handling to prevent deleting themselves
* hide the link from user if viewing own record
* route them back to the details page with an error if
they spoof the delete function
[finishes #103483020]
=> Prevent user deleting themselves

app/controllers/users_controller.rb, app/models/ability.rb, app/services/user_management.rb, app/views/users/deleted.html.slim, app/views/users/index.html.slim, app/views/users/show.html.slim, config/routes.rb, spec/controllers/users_controller/admin_user_spec.rb, spec/controllers/users_controller/manager_user_spec.rb, spec/routing/users_routing_spec.rb, spec/services/user_management_spec.rb, spec/views/users/deleted.html.slim_spec.rb, spec/views/users/index.html.slim_spec.rb
There was a need for admins to undelete users.
This adds a new users/deleted view that only lists deleted users
The table has a per user restore function
As part of the work, I refactored some of the complexity to a new UserManagement 
service class.  This is called from the UserController and the show view to determine
eligibility to delete.
=> Admin user delete

lib/tasks/static_pages.rake
The static pages were being generated with www.example.com because
(as they are static!) they did not have access to root_url.
This replaces http://www.example.com with /, thus taking users
to the root page of the current site, regardless of environment.
=> Update static page rake task

app/models/forms/personal_information.rb, config/locales/en.yml, spec/models/forms/personal_information_spec.rb
When refactoring the monolithic Application model to be extracted to
Personal Informaton form object, the validation for the minimum/maximum age was
not brought over.
=> DOB validations

app/views/feedback/index.html.slim, spec/views/feedback/display.html.slim_spec.rb
This will allow admins to contact users directly
without having to search for users and copy/paste
email addresses from the user table.
=> Add Email link to feedback display

app/models/user.rb, config/locales/en.yml, spec/models/user_spec.rb
The model shouldn't know the full path to the locale error messages,
they should be derived upon validation.
=> I18n cleanup in User model

spec/controllers/applications/build_controller_spec.rb, spec/controllers/dwp_checks_controller_spec.rb, spec/features/applications/application_form_application_details_spec.rb, spec/features/applications/application_form_personal_details_spec.rb, spec/features/applications/application_form_stories_spec.rb, spec/features/applications/benefit_results_are_rendered_spec.rb, spec/features/applications/confirmation_is_rendered_spec.rb, spec/features/applications/over_61_applicants_can_complete_form_spec.rb, spec/features/applications/remission_confirmation_spec.rb, spec/features/perform_an_income_check_spec.rb, spec/rails_helper.rb, spec/services/benefit_check_service_spec.rb, spec/services/health_status_spec.rb
Instead of enabling WebMock in individual specs, turn it on once for the
whole test suite. Less error prone and avoids the distraction in the
tests.
=> Cleaned up WebMock usage

spec/rails_helper.rb
From my reading of:
https://www.relishapp.com/rspec/rspec-core/v/3-2/docs/hooks/before-and-after-hooks
it seems that having the stubs set before each context, fixes the
intermitten failures.
=> Stub out the requests before each context

db/migrate/20150910151042_add_expires_at_to_spotcheck.rb
Previous migration script ran a per object script
A the object was renamed, it could not resolve the object to
the database. I switched it to a sql script to run purely
agains the table and it now works on local machines.
Lets see how branch builder does...
=> Fix for migration error

spec/models/form_object_spec.rb
This is not needed after a renaming of the object and
was generating a reubocop warning
=> Remove rubocop exclusion

app/models/feedback.rb, spec/controllers/feedback_controller_spec.rb, spec/factories/users.rb
When feedback was displayed, if a deleted user had left 
feedback the page would error.  This sets the association to 
include with_deleted to prevent the error.
=> Set feedback to retain deleted users details

app/assets/stylesheets/dwp_checks.scss, app/models/evidence/views/overview.rb, app/views/evidence/show.html.slim, app/views/shared/_remission_type.html.slim, spec/models/evidence/views/overview_spec.rb
Added the result partials.
I also extended the overview class to add amount_to_pay
(needed for a partial remission) and a required_partial
method.   This allows the view to render a partial depending
on the data in the application model within the overview.
It always passes in the amount to pay because,
if it's not needed it is ignored, but in a partial it merges it.
=> Partial views for results

app/helpers/summary_helper.rb, app/models/evidence/views/overview.rb, app/views/evidence/show.html.slim, config/locales/en.yml, spec/helpers/summary_helper_spec.rb, spec/models/evidence/views/overview_spec.rb
To improve re-usability and simplify the views, the
evidence overview page has been refactored into 
a helper.
This required setting up new locale entries for the
overview object.
=> Split overview with partials

app/assets/stylesheets/summary.scss, app/helpers/summary_helper.rb, app/models/evidence/views/overview.rb, config/locales/en.yml, spec/models/evidence/views/overview_spec.rb
Added css styling to the new summary page to match
the design.
Checks for ✓ or ✗ in the value and applies the current 
result (full, part or none) to the value row.
The styles are updated to ensure that the names match
the (current) outcomes.
=> Styling evidence summary pages

app/assets/stylesheets/evidence_check.scss, app/controllers/application_controller.rb, app/controllers/home_controller.rb, app/models/application.rb, app/models/evidence/views/overview.rb, app/models/office.rb, app/views/home/_manager.html.slim, app/views/home/_user.html.slim, app/views/home/_waiting_for_evidence.html.slim, app/views/home/index.html.slim, config/locales/en.yml, spec/factories/applications.rb, spec/features/evidence/applications_awaiting_evidence_are_displayed_on_dashboard_spec.rb, spec/models/application_spec.rb, spec/models/office_spec.rb
It adds the list of applications waiting for evidence to the dashboard for managers and staff. 
I'm not particularly happy with some bits of the implementation, but I tried to re-use as much as possible from what we already have, so we can move on to the next bits of the evidence check flow.
=> Waiting for evidence dashboard

app/controllers/evidence_controller.rb, app/models/evidence/views/result.rb, app/views/evidence/result.html.slim, config/routes.rb, spec/factories/evidence_checks.rb, spec/features/evidence/evidence_check_flow_spec.rb, spec/models/evidence/views/result_spec.rb
Added a Result view model, it returns the EvidenceCheck.outcome 
and amount to pay.
This is rendered on the view using the remission partial.
The EvidenceCheck factory was updated to include the outcome
and amount_to_pay fields.
=> Implement evidence calculation result

app/assets/stylesheets/summary.scss, app/controllers/evidence_controller.rb, app/helpers/summary_helper.rb, app/models/evidence/forms/evidence.rb, app/models/evidence/views/evidence.rb, app/models/evidence/views/result.rb, app/views/evidence/result.html.slim, app/views/evidence/summary.html.slim, config/locales/en.yml, config/routes.rb, spec/factories/evidence_checks.rb, spec/factories/reasons.rb, spec/features/evidence/evidence_check_flow_spec.rb, spec/models/evidence/forms/evidence_spec.rb, spec/models/evidence/views/evidence_spec.rb, spec/models/evidence/views/result_spec.rb, spec/routing/evidence_routing_spec.rb
It's ready to be reviewed / merged now. 
It brings the "page No. 6" part of the evidence flow. When the evidence is not correct, the page is redirected straight to this summary page. When the evidence is correct, the summary page is displayed after income result page.
=> Evidence summary page

app/views/evidence/summary.html.slim, spec/features/evidence/evidence_check_flow_spec.rb
Added a link that enables the user to move from the summary page to the
confirmation page.
=> Link from evidence summary to confirmation

spec/controllers/evidence_controller_spec.rb, spec/routing/evidence_routing_spec.rb
Added the missing specs to the result action on the evidence controller.
All the other actions have these specs, so trying to stay uniform.
=> Evidence result specs

app/assets/javascripts/evidence_confirmation.coffee, spec/javascripts/evidence_confirmation_spec.coffee
This feature was covered by the feature test, but what wasn't covered is
the textarea wasn't being cleared after the users chose the 'Yes'
option.
Added the feature that clears the textarea and the test.
=> Added clearing of the reason

app/views/evidence/summary.html.slim, spec/features/evidence/evidence_check_flow_spec.rb
The design calls for the button to have a specific
wording, not just Next.
More work is needed to submit this page as a form to
set completed_at and _by values.  A separate branch
will be created for this.
=> updated wording inline with design

app/controllers/evidence_controller.rb, app/models/evidence/forms/accuracy.rb, app/models/evidence/forms/income.rb, app/models/evidence/views/evidence.rb, app/models/evidence_check.rb, app/models/form_object.rb, app/models/reason.rb, app/views/evidence/accuracy.html.slim, app/views/evidence/income.html.slim, app/views/evidence/summary.html.slim, config/locales/en.yml, db/migrate/20151013143545_move_reason_to_evidence_check.rb, db/schema.rb, spec/controllers/evidence_controller_spec.rb, spec/factories/evidence_checks.rb, spec/factories/reasons.rb, spec/features/evidence/evidence_check_flow_spec.rb, spec/models/evidence/forms/accuracy_spec.rb, spec/models/evidence/forms/income_spec.rb, spec/models/evidence/views/evidence_spec.rb, spec/models/form_object_spec.rb
This is not just a refactoring PR, but also a preparation for the new Payment flow.
As discussed and agreed with @dotemacs, we'll for now put the `reason` back to the `EvidenceCheck` table. That way we should be able to re-use exactly the same form object for the new flow. We've briefly discussed and I'm sure there'll be more how to slice our models going forward.
It's also one further step to make our form objects as similar to each other as possible.
Last but not least the `EvidenceController` should now be cleaner and not have any responsibility for parameters processing.
=> Improve evidence controller and forms

app/controllers/evidence_controller.rb, app/models/evidence_check.rb, app/views/evidence/summary.html.slim, config/routes.rb, db/migrate/20151012135047_add_completed_to_evidence_check.rb, db/schema.rb, spec/controllers/evidence_controller_spec.rb
When the user clicks 'Complete processing' on the summary page, 
the model should record when it was clicked and by whom.
This adds the required fields, the routes and actions to handle it.
=> Confirm evidence

config/locales/en.yml
Updated to include: “You should send this letter back with your
evidence” so staff can identify evidence for checking.
=> Updated evidence check letter

app/controllers/applications/build_controller.rb, spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb
Added evidence_check feature flag tests, then implemented 
a fix where the 10th income application would get flagged
even if the feature flag was turned off.
=> Evidence check creation fix

app/models/applikation/forms/personal_information.rb, config/locales/en.yml, spec/models/applikation/forms/personal_information_spec.rb
[finishes #104996152]
Addresses these [sentry alerts](https://sentry.service.dsd.io/mojds/prod-staff-app/group/247/)
When a user entered a two digit year into date of birth, a 500 error was
being generated.  This fix returns an error to the user and returns to
the page with a validation message.
=> Two digit year fix

app/views/evidence/_confirmation_none_remission.html.slim, app/views/evidence/_confirmation_part_remission.html.slim, app/views/evidence/confirmation.html.slim, config/locales/en.yml, spec/features/evidence/evidence_check_flow_spec.rb
[finishes #105467270]
[finishes #105467530]
The evidence check letters for part and no remission had 
placeholders for values.  Replaced the placeholders with 
the required data.
=> Add values to letters

config/settings.yml
The bug raised in this ticket:
https://www.pivotaltracker.com/story/show/100752692
This should be merged in once **it's confirmed** that the new email is **fully operational** with WebOps crew & Jiten.
=> Bug fix: changed the no-reply email for prod -- hold until 16-OCT

app/models/applikation/forms/savings_investment.rb, app/models/views/application_overview.rb, app/models/views/application_result.rb, app/views/applications/build/application_details.html.slim, app/views/applications/build/benefits.html.slim, app/views/applications/build/income.html.slim, app/views/applications/build/income_result.html.slim, app/views/applications/build/personal_information.html.slim, app/views/applications/build/savings_investments.html.slim, app/views/applications/build/summary.html.slim, config/locales/en.yml, spec/features/applications/application_jurisdiction_validation_spec.rb
The application form referenced the local file in the ActiveRecord
namespace.  Once the form objects were created, the labels 
needed moving into the ActiveModel namespace.  This left 
duplication and some form labels/errors that had not transitioned 
properly.
This PR moves all entries into their proper namespaces and 
updates the savings_investment model to add the correct error
messages.
=> Move locale to activemodel

app/models/application.rb, spec/features/payments/applications_awaiting_payment_are_displayed_on_dashboard_spec.rb, spec/models/application_spec.rb
Updated the application waiting_for_payment scope to exclude
completed payments
Fixes [ticket](https://www.pivotaltracker.com/story/show/106099058)
[delivers #106099058]
=> Update application scope

config/locales/en.yml
The dashboards were looking for locale keys named no_record
I renamed the two keys from no_evidence_checks which were
wrong for evidence_checks and **very** wrong for payments!
=> Dashboard fix

app/controllers/benefit_overrides_controller.rb, app/models/application.rb, app/models/benefit_override.rb, app/models/forms/benefits_evidence.rb, app/views/applications/build/benefits_result.html.slim, app/views/applications/build/confirmation.html.slim, app/views/applications/build/summary.html.slim, app/views/applications/partials/_full_fee.html.slim, app/views/benefit_overrides/paper_evidence.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20151021112859_create_benefit_overrides.rb, db/schema.rb, spec/controllers/benefit_overrides_controller_spec.rb, spec/factories/benefit_overrides.rb, spec/features/applications/application_form_stories_spec.rb, spec/features/applications/benefit_results_are_rendered_spec.rb, spec/features/applications/no_ni_number_and_undetermined_result_spec.rb, spec/features/applications/stray_error_on_confirmation_page_spec.rb, spec/features/applications/when_benefits_checker_returns_undetermined_result_spec.rb, spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb, spec/models/benefit_override_spec.rb, spec/models/forms/benefits_evidence_spec.rb, spec/services/evidence_check_selector_spec.rb
There was an issue when a user didn't provide their NI number and the
application was started, the benefit check was attempted but it could
not be done because benefit check requires the NI number for the lookup.
This would throw the user into a loop. This change tries to prevent
that.
=> When no NI number provided, prevent loop

.travis.yml
This parameter enables caching of gem for Travis CI, so it speeds up the
testing.
Travis CI docs here:
http://docs.travis-ci.com/user/caching/
=> Enabled caching of gems for Travis CI

app/controllers/evidence_controller.rb, app/models/application.rb, app/services/payment_builder.rb, spec/features/evidence/evidence_check_flow_spec.rb
Implement test for creation of object at end of evidence-check flow
Update the payment builder to check for application and
evidence check being passed in.
The Payment builder was only looking at the application model to check
for part payment results, I re-used the code from the application_result
view model to test for the presence of both.
=> Fix for part payments from evidence-checks

app/models/application.rb
After fixing the part payments creation by evidence checks
the ni number is no longer displayed correctly on the application
form summary page.
Despite this being re-done in an upcoming refactoring pull request
this fixes the display issue so that other features can be
released.
=> Fix for NI summary display

app/models/application.rb, spec/features/evidence/applications_awaiting_evidence_are_displayed_on_dashboard_spec.rb, spec/features/payments/applications_awaiting_payment_are_displayed_on_dashboard_spec.rb
When applications linked to evidence_checks and payments where created
by deleted users, the dashboard was breaking.
* implemented tests to cover the case
* added a with_deleted filter to the application object
=> Implement fix for broken dashboard

app/controllers/home_controller.rb, app/models/application.rb, app/models/query/evidence_checkable.rb, app/models/query/waiting_for_evidence.rb, app/models/query/waiting_for_payment.rb, app/services/evidence_check_selector.rb, spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb, spec/models/application_spec.rb, spec/models/query/evidence_checkable_spec.rb, spec/models/query/waiting_for_evidence_spec.rb, spec/models/query/waiting_for_payment_spec.rb
This is just a discussion starter, to see what you @colinbruce & @novotnyjakub think.
This is just an example of how we can do things: instead of having it
all stuffed into the Application model, tease it out.
The new nested structure directory 'query', that is open for debate,
maybe it should be called 'queries'?
Also something like this can be extracted out into this new query object and tested tighter:
https://github.com/ministryofjustice/fr-staffapp/blob/extract-queries/app/services/evidence_check_selector.rb#L33
=> Extracted scopes from Application into Query objects

app/models/application.rb
When the personal_information model was split out, the age
validation code was [moved over](https://github.com/ministryofjustice/fr-staffapp/blob/master/app/models/applikation/forms/personal_information.rb#L56), along with the tests.
The original code was left behind and is no longer used.
This removal should improve the code-climate score for the
(decreasingly) monolithic application model.
=> Refactor the application model

app/models/applikation/forms/application_detail.rb, spec/models/applikation/forms/application_detail_spec.rb
The new time constants were being set on first creation and locking the date
to the server launch date.
Added a Timecop test to ensure that any future attempts to refactor this
don't break it again!
=> Reverted the validation changes

app/models/views/application_overview.rb, app/views/applications/build/benefits_result.html.slim, config/locales/en.yml, spec/features/applications/allow_override_when_dwp_checker_says_no_spec.rb
Allow the staff to override benefit check when the result is 'No', if
the member of public presents paper based evidence.
=> Allow the users to override benefits check

app/controllers/benefit_overrides_controller.rb, app/models/forms/benefits_evidence.rb, app/models/views/application_overview.rb, app/views/applications/build/benefits_result.html.slim, app/views/benefit_overrides/paper_evidence.html.slim, config/locales/en.yml, spec/controllers/benefit_overrides_controller_spec.rb, spec/features/applications/allow_override_when_dwp_checker_says_no_spec.rb, spec/models/forms/benefits_evidence_spec.rb
When the Benefits Override flow's evidence page would be submitted
without the either options chosen, the form could be submitted and an
error would be thrown.
This commit prevent's the form to be submitted for saving without one of
the options being picked.
=> Bug fix: prevent empty paper evidence submission

spec/factories/applicants.rb, spec/factories/applications.rb, spec/factories/details.rb, spec/factories/factory_helpers.rb
This may not seem as an improvent, but it allows us to build stubbed
Application with Applicant / Detail. Before it was possible but without
being able to inject any of those when stubbing.
=> Cleanup factories and improve stubbing

app/models/views/application_overview.rb, spec/models/views/application_overview_spec.rb
There was a bug which tried to format income even though it was `nil`. That's now fixed.
=> Fix processed application detail page for benefit based application

app/models/application.rb, app/models/applikation/forms/benefit.rb, app/models/query/evidence_checkable.rb, app/models/query/processed_applications.rb, app/models/views/application_overview.rb, app/models/views/application_result.rb, app/models/views/applikation/result.rb, app/services/benefit_check_runner.rb, app/services/income_calculation_runner.rb, app/views/applications/process/confirmation.html.slim, app/views/applications/process/income_result.html.slim, db/migrate/20151112110146_rename_application_outcome_to_outcome.rb, db/schema.rb, spec/factories/applications.rb, spec/features/applications/remission_confirmation_spec.rb, spec/models/applikation/forms/benefit_spec.rb, spec/models/query/processed_applications_spec.rb, spec/models/views/application_overview_spec.rb, spec/models/views/application_result_spec.rb, spec/models/views/applikation/result_spec.rb, spec/services/benefit_check_runner_spec.rb, spec/services/income_calculation_runner_spec.rb
No need for the **`application_'** part of the name, especially since this is a column in **`applications'** table.
Also added a **'missed'** migration for a foreign key for applications on benefit_override table.
=> Rename application outcome to outcome

app/controllers/evidence_controller.rb, app/controllers/part_payments_controller.rb, spec/services/resolver_service_spec.rb
This ensures that all three models: Application, EvidenceCheck and PartPayment use the same method of setting their completed data fields.
Next step: 
Move the creation of EvidenceChecks and PartPayments into the ResolverService
This will reduce the work done in the controllers
=> Extend resolver service

spec/controllers/evidence_controller_spec.rb, spec/controllers/part_payments_controller_spec.rb, spec/features/applications/benefit_results_are_rendered_spec.rb
No need for them to be left lying around, so removing them.
=> Removed 'focus' tags from specs

app/models/applikation/forms/income.rb, spec/models/applikation/forms/income_spec.rb
The Income form needed validation on the income field.
The page could not be saved without it and was then throwing a 500 error
if the page was saved without an income recorded.
=> Added validation for income

app/services/resolver_service.rb, spec/services/resolver_service_spec.rb
Enabled it to resolve the decision of the application on the application
itself, but also to update the corresponding object by which the
application decision was derived.
=> Extended ResolverService

app/assets/stylesheets/base.scss, app/controllers/evidence_controller.rb, app/views/evidence/return_letter.html.slim, app/views/evidence/show.html.slim, config/locales/en.yml, config/routes.rb, spec/controllers/evidence_controller_spec.rb, spec/features/return_applications/return_evidence_checkable_applications_spec.rb, spec/routing/evidence_routing_spec.rb
Allow users to return applications that are due for evidence check, where the applicant has not provided evidence during the required time window.
All it does is generate a letter for the applicant and marks.
=> Return application

db/migrate/20150508131347_add_fields_to_dwp_check.rb
Because the DwpCheck model had been deleted, this would cause db:migrate to fail
when run from scratch.
Switched the script to execute SQL rather the use the ActiveRecord::connection method.
=> Fix for running db:migrate from scratch

Gemfile, Gemfile.lock
A security vulnerability was discovered with libxml2 & libxslt which
affects nokogiri (which uses those libraries).
More information here:
https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc#167rc4--2015-11-22
https://github.com/sparklemotion/nokogiri/commit/ee52b7be5b47e1029af98f6b7eb6df7fc5ffd359
https://github.com/sparklemotion/nokogiri/commit/0948e9fa38c949661983a33752fdcb94a453e272
=> Nokogiri upgrade due to security vuln

app/models/applikation/forms/application_detail.rb, config/locales/en.yml, spec/models/applikation/forms/application_detail_spec.rb
This changes validation of the refund date form field. It now has to be:
* up to 3 months before the date application received
* not later than date application received
=> Validate refund date relative to date received

app/views/processed_applications/show.html.slim, config/locales/en.yml
Fix for processed application summary showing the wrong labels for benefits based check
[ticket](https://www.pivotaltracker.com/story/show/108233338)
=> Fix process application labels

app/models/forms/application/applicant.rb, spec/models/forms/application/applicant_spec.rb
The user surname was not being trimmed before being sent to the DWP.
We now trim the name fields before validating to prevent this.
This should prevent transcription errors when users cut and paste from other sources.
=> Trim applicant name fields

app/models/application.rb
This had been moved into a view model and this method was no longer used, or tested
=> Removed duplicate NI number display

app/views/guide/evidence_checks.html.slim
1. Court staff feedback to say needed to be clearer re not accepting /
rejecting applications before evidence is rec’d
2. Applications awaiting evidence > Applications waiting for evidence
=> Updated guide to evidence checks

app/views/offices/show.html.slim, app/views/users/show.html.slim
Following a CSS update the management views for office and staff
had become... sub-optimal
This update corrects the spacing and adds a row for the BE code.
This means that users will have a better experience on the management side of the app, until the 'merging staff and office' ticket reaches the backlog.
=> Updated management views

spec/factories/offices.rb
- The factory generates sequences of entity_codes
- Using ljust creates 100, 200, 300, 400...
- Switching to rjust means that 001, 002 sequences are created, this
leads to less opportunities to clash.
=> Fix for entity code test fails

app/models/forms/application/detail.rb, config/locales/en.yml, spec/models/forms/application/detail_spec.rb
Allow the date fee paid to be on the same day as the date the
application was received.
Previously it only allowed the paid fee date to be the date before.
:ticket::
https://www.pivotaltracker.com/story/show/109797244
=> Allow the date fee paid to match received date

app/builders/application_builder.rb, app/models/application.rb, app/models/business_entity.rb, app/services/reference_generator.rb, app/services/resolver_service.rb, db/migrate/20151210152605_create_business_entities.rb, db/migrate/20151214170243_add_business_entity_to_application.rb, db/schema.rb, spec/builders/application_builder_spec.rb, spec/controllers/applications/process_controller_spec.rb, spec/factories/applications.rb, spec/factories/business_entities.rb, spec/factories/offices.rb, spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb, spec/models/application_spec.rb, spec/models/business_entity_spec.rb, spec/services/reference_generator_spec.rb, spec/services/resolver_service_spec.rb
This introduces `BusinessEntity` model which will be managed by HQ. `BusinessEntity` has to exist for each combination of `Office` and `Jurisdiction` in use. Editing of business entities will be added later.
A big change is that `reference` for `Application` is now only created on completion of application. Until then it's `NULL`. Because the prefix for the reference is now taken from the relevant `BusinessEntity`, reference to it is also stored to `Application`.
=> Business entities

app/controllers/users/invitations_controller.rb, spec/controllers/users/invitations_controller_spec.rb
This PR fixes this privilege escalation issue: https://www.pivotaltracker.com/story/show/102069424
Don't allow the managers to invite admins.
In fact this was not allowed, but the PR prevents even the malicious attempts at privileged invitation attempt.
I'm aware that some of the controller tests can be interpreted as feature tests, but since this is a security related, I'm happy to violate test purity for the sake of security.
=> Lock down invites for managers

app/services/resolver_cost_calculator.rb, app/services/resolver_service.rb, db/migrate/20151215144022_migrate_decision_to_application.rb, db/migrate/20151215154501_add_decision_date_and_decision_cost_to_application.rb, db/schema.rb, lib/decision_date_and_cost_migration.rb, lib/decision_migration.rb, spec/factories/part_payments.rb, spec/lib/decision_date_and_cost_migration_spec.rb, spec/lib/decision_migration_spec.rb, spec/services/resolver_cost_calculator_spec.rb, spec/services/resolver_service_spec.rb
This adds `decision_date` and `decision_cost` to `Application`. The main purpose is to be able to easily access the summary of decided application. After this we may consider taking all the `decision_` columns to a separate table, which then can be used for various stats (like finance).
It also migrates all existing processed applications to have all the decision columns filled in (including `decision` and `decision_type`.
=> Add more decision columns

app/views/applications/process/confirmation.html.slim, app/views/evidence/confirmation.html.slim, app/views/part_payments/confirmation.html.slim, spec/features/applications/remission_confirmation_spec.rb, spec/features/applications/temporary_reference_number_spec.rb, spec/features/evidence/evidence_check_flow_spec.rb, spec/features/part_payments/part_payments_flow_spec.rb
* Added tests for hiding remission register text and showing reference number
* Updated optional display/style of confirmation block
* only display the right hand guidance on remission register for 
evidence_check and part_payments when the reference date has passed
* styled the reference number display when completing an application form
=> Reference number display update

app/views/applications/process/savings_investments.html.slim, spec/features/applications/application_savings_and_investments_spec.rb
When a user processes a married applicants form and submitted
the savings and investment view without answering the first
question, a 500 error was raised.
This improves the logic to invalidate the object and render
the validation message on the view.
[finishes #110493440]
=> Fix for married applicant savings validation

app/views/offices/_form.html.slim, spec/views/offices/edit.html.slim_spec.rb, spec/views/offices/new.html.slim_spec.rb
When editing an office, managers should not see the office entity code
or be able to edit it.
Updated the tests for new office to match
[finishes #110499670]
[Ticket](https://www.pivotaltracker.com/story/show/110499670)
=> Hide office BE Codes from managers

Gemfile, Gemfile.lock
Updated Nokogiri to the latest stable version due to the security
vulnerability issue:
* https://groups.google.com/forum/#!topic/ruby-security-ann/aSbgDiwb24s
* https://github.com/sparklemotion/nokogiri/pull/1378
=> Updated Nokogiri to 1.6.7.1

app/assets/javascripts/application.js, app/assets/javascripts/cookies.js, app/assets/javascripts/guide.js, app/assets/javascripts/login.js, app/assets/stylesheets/form_elements.scss, app/views/users/sessions/new.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/100523714)
* When user submits the login form, set a cookie to the content of the username (email) field
* When loading the login form, check for that cookie and if present, prefill the username field
* Prevent browser autocomplete of password box using decoy visually hidden password field (`autocomplete="off"` is not respected by most browsers any more)
=> use cookie to autofill username

app/controllers/users/registrations_controller.rb, app/policies/user_policy.rb, config/routes.rb, spec/features/user_profile_spec.rb, spec/policies/user_policy_spec.rb
Since the introduction of Pundit, the users were unable to change their
own passwords. This change allows them to do that again.
=> Allow users to edit their own passwords

app/assets/stylesheets/application.scss, app/assets/stylesheets/utilities.scss, app/views/home/index.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/110953430)
Before
---
After
---
Note the Pivotal story says to remove the space between the bulleted list and the 'Start now' button, but this looks too cramped. Removing the top margin from the button container has reduced the space, which looks good.
Here is the cramped version:
=> process application module changes

.travis.yml
Previously there was a reason for specifiying the Ruby version in both
.travis.yml and .ruby-version. Hoping that this is no longer the case,
since maintaining the Ruby version in two places is error prone.
=> Removing the Ruby version from Travis CI config

app/views/shared/_footer.slim
Teeny little PR so that you don't see links to the staff guides if you're logged out (since you can't view them when logged out).
=> hide staff guides in footer if logged out

app/controllers/offices_controller.rb, app/models/jurisdiction.rb, spec/controllers/offices_controller_spec.rb, spec/models/jurisdiction_spec.rb
I'm creating this PR to be merged to #542 so that both can be released together, because they depend on each other in terms of UX. 
The big part of this PR is refactoring of the `office_controller_spec.rb` which is now made in a way that not all functionality has to be tested for all types of users. It's now driven by the policy, rather than being sort of an integration test, which is hard to maintain.
=> Manager only sees jurisdictions with bec

app/controllers/offices_controller.rb, app/models/jurisdiction.rb, app/models/office.rb, app/views/home/index.html.slim, app/views/offices/_form.html.slim, app/views/offices/edit.html.slim, app/views/offices/new.html.slim, app/views/offices/show.html.slim, config/locales/en.yml, spec/controllers/offices_controller_spec.rb, spec/models/jurisdiction_spec.rb, spec/models/office_spec.rb, spec/views/home/index.html.slim_spec.rb, spec/views/offices/edit.html.slim_spec.rb, spec/views/offices/new.html.slim_spec.rb
When admin tries to add a new office, now it only requires a name. 
This PR also removes the validation on `Office` to have at least one `OfficeJurisdiction`. 
To prevent staff creating applications and then not being able to progress through application details, the `Start now` button only appears when there is at least 1 jurisdiction. Otherwise there's a message to contact a manager.
=> Changes to Add new office page

app/views/home/index.html.slim, app/views/reports/finance_report.html.slim, config/locales/en.yml
Looky likey:
Note that there is a subsequent ticket to move the graphs below off the admin dashboard onto their own page.
=> add two new modules to admin dashboard

app/views/users/sessions/new.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/111955271)
Before
---
1.
2.
After
---
=> show support email on sign in page

app/assets/stylesheets/base.scss, app/assets/stylesheets/foundation_and_overrides.scss, app/views/guide/appeals.html.slim, app/views/guide/evidence_checks.html.slim, app/views/guide/index.html.slim, app/views/guide/part_payments.html.slim, app/views/guide/process_application.html.slim, app/views/guide/suspected_fraud.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/111965025)
Guides home page
---
Before
After
Guides detail "more guides" section
---
Before
After
=> make staff guide panels responsive

app/views/evidence/confirmation.html.slim, app/views/evidence/result.html.slim, app/views/home/index.html.slim, app/views/part_payments/confirmation.html.slim, app/views/part_payments/show.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/112148431)
Seems to be caused by actually applying the class 'success' to some buttons, so that's been removed.
🚫
👌
=> make green buttons consistent

app/assets/javascripts/login.js, app/assets/stylesheets/base.scss, app/assets/stylesheets/buttons.scss, app/views/evidence/show.html.slim, app/views/evidence/summary.html.slim, app/views/feedback/_form.html.slim, app/views/home/index.html.slim, app/views/offices/_form.html.slim, app/views/part_payments/show.html.slim, app/views/users/invitations/edit.html.slim, app/views/users/passwords/edit.html.slim, app/views/users/passwords/new.html.slim, app/views/users/sessions/new.html.slim, app/views/users/shared/_form.html.slim, app/views/users/shared/_form_roles.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/112236157)
I think I've caught everything here - best if @kelliematheson checks though...
* make all green buttons the same size across the application, except
* 'Complete processing' on the three summary pages should be large, and
* blue 'Return application' and 'Delete application' buttons should use class `small` for smaller font size
=> Make button sizes consistent across the application

app/controllers/home_controller.rb, app/controllers/reports_controller.rb, app/views/home/_graphs.html.slim, app/views/reports/graphs.html.slim, app/views/reports/index.html.slim, config/routes.rb, spec/controllers/home_controller_spec.rb, spec/controllers/reports_controller_spec.rb
As the number of offices has grown, the index page for admins has slowed
down more and more.
This PR aims to make it faster while still allowing relatively quick access to the data
I have migrated the graphs to the reports controller and 
provided a link to new action on front page
=> Move graphs from admin/index

app/views/business_entities/edit.html.slim, app/views/business_entities/index.html.slim, app/views/business_entities/new.html.slim, config/locales/en.yml, spec/features/admin_can_maintain_business_entities_spec.rb
The `Delete` button took users to a `deactivate` view.
The index page columns was titled BEC description, the edit page called the field Name
Index column sequence was code > name, the edit view was name > code.
These have all been resolved.
=> BECs labelling update

app/controllers/home_controller.rb
During a rather too agressive refactoring, all of the code for
the collation of graph data was moved to the reports controller
and subsequently deleted when it was not needed.
This returns the two front page graphs to their correct state.
[finishes #112616861]
=> Restore graph data for admin

app/policies/office_policy.rb, spec/features/manager_office_access_spec.rb, spec/policies/office_policy_spec.rb
Updated the office.index? policy by enabling it only for admin and mi users.
[finishes #112617015]
=> Updated the office permissions

app/controllers/users/invitations_controller.rb, config/locales/devise_invitable.en.yml, spec/controllers/users/invitations_controller_spec.rb, spec/features/user_invite_spec.rb
Show warning message when deleted user is invited
This should prevent the `PG::UniqueViolation: ERROR:  duplicate key
value violates unique constraint "index_users_on_email"` sentry warnings.
=> Prevent deleted user errors

app/models/forms/application/detail.rb, spec/features/applications/application_form_application_details_spec.rb, spec/models/forms/application/detail_spec.rb
The field is now not validated until `date_received` is a valid date. 
The error message on `date_received` field is not ideal, because if the format is incorrect, it simply says "The application must have been made in the last 3 months". We should create a new card to improve that message in case of an incorrect date. 
The `date_validator` would work well in case of being used with `ActiveRecord`, which provides `...before_type_cast` methods. But because we're only using `ActiveModel` and `Virtus`, that gem doesn't work as expected. But I think we can achieve similar thing maybe using a **custom Virtus coercer** or so.
=> Don't raise error on date_fee_paid validation

app/views/shared/forms/_accuracy.html.slim, config/locales/en.yml
When the user submitted the evidence/accuracy page without
checking either checkbox, the boxes were highlighted in red,
but no error was shown.
This has added an error message to the view and set the text in the
locale file.
=> Update evidence accuracy error handling

config/initializers/i18n.rb, config/locales/en.yml, spec/features/admin_can_maintain_business_entities_spec.rb, spec/features/manager_out_of_the_box_experience_spec.rb, spec/lib/i18n_spec.rb
Content have requested that the default submit buttons should lower case the model names.
This PR adds an I18n extension that allows us to lower case models within the YML file, instead of having to manually set the text on every submit button on every form.
=> Update locale handling

app/controllers/applications/process_controller.rb, app/services/completed_application_redirect.rb, spec/controllers/applications/process_controller_spec.rb, spec/services/completed_application_redirect_spec.rb
When a user has clicked 'completed processing' on the summary page,
any attempts to view the individual process views should be redirected
to the current state's end point, e.g. deleted, processed, awaiting
payment, awaiting evidence.
The controller calls the service class which returns the relevant path,
this is overridden for create and confirmation to allow new items to be
created(!) and the final page to be re-shown if users need to get the
letters from the view.
=> Created application redirect service

app/controllers/applications/process_controller.rb, app/services/completed_application_redirect.rb, config/locales/en.yml, spec/controllers/applications/process_controller_spec.rb, spec/services/completed_application_redirect_spec.rb
Because the pages were stored in the browser history the users could
still use the browser back button.
This was designed to set the application processed page to expire and
force a reload/redirect if trying to view in the same browser session.
=> Force application redirect after completion

app/views/home/index.html.slim
Because the DWP has remained down for 4 days...
Show a warning to users, this will need to be removed manually...
Or we could write a checker to see if it should be displayed automatically!
=> Display emergency banner

db/seeds.rb
It now only creates a BEC entry from the previously created office_jurisdiction objects.
This will allow users to create applications on the demo environments without having to manually create BEC codes.
=> Update the Business Entity seed script

app/builders/finance_report_builder.rb, app/models/views/reports/finance_report_data_row.rb, spec/models/views/reports/finance_report_data_row_spec.rb
Updated dates and scope of state for the finance report.
The scope was including all applications, not only those successfully completed
Also the date was not being set to midnight at either end of the day as was expected by the users
=> Finance report update

app/assets/stylesheets/application.scss, app/assets/stylesheets/confirmation_letters.scss, app/assets/stylesheets/evidence_check.scss, app/assets/stylesheets/result_bar.scss, app/assets/stylesheets/utilities.scss, app/helpers/summary_helper.rb, app/models/views/confirmation/result.rb, app/views/applications/process/confirmation.html.slim, app/views/evidence_checks/show.html.slim, config/locales/en.yml, config/locales/letters_en.yml, spec/features/applications/application_form_stories_spec.rb, spec/features/applications/application_savings_and_investments_spec.rb, spec/features/applications/confirmation_is_rendered_spec.rb, spec/features/applications/over_61_applicants_can_complete_form_spec.rb, spec/features/applications/show_result_on_confirmation_spec.rb, spec/features/applications/stray_error_on_confirmation_page_spec.rb, spec/features/benefit_override/no_ni_number_and_undetermined_result_spec.rb, spec/features/evidence-checks/evidence_check_page_displays_letter_to_be_sent_spec.rb, spec/features/evidence/evidence_check_flow_spec.rb, spec/models/views/confirmation/result_spec.rb
[Pivotal](https://www.pivotaltracker.com/story/show/114297385)
Screenshots of progress thus far:
PASSED
===
Before
---
After
---
After with reference number
---
PART PAYMENT
===
Before
---
After
---
After backend updates
---
**Note:** start of letter
EVIDENCE CHECK
===
Before
---
After
---
After backend updates
---
NOT ELIGIBLE
===
Before
---
After
---
=> Make confirmation pages consistent

app/models/online_application.rb, spec/models/online_application_spec.rb
It's an important for on the OnlineApplication model, which is currently
not being able to save records.
The problem is that boolean fields can't be validated using presence
validator, but only using an inclusion validator. Subsequently the spec
then can't use the given shoulda matcher, but only can test for
inability to assign nil value to those fields.
=> Fix validation of boolean fields

app/models/forms/application/applicant.rb, spec/models/forms/application/applicant_spec.rb
Wrongly used constants for mutable data.
This was reverted and refactored.
Added specific tests for the validations to ensure thorough coverage.
=> Removed constants for date_of_birth calculation

app/controllers/online_applications_controller.rb, app/models/online_application.rb, app/policies/online_application_policy.rb, app/views/online_applications/show.html.slim, config/routes.rb, spec/controllers/online_applications_controller_spec.rb, spec/features/online_applications/staff_can_add_details_spec.rb, spec/models/online_application_spec.rb, spec/policies/online_application_policy_spec.rb
The staff can now proceed do the summary page.
The prototype design has slightly different values for some fields (for example `None` instead of `0` for `Number of children`), but it's consistent with the other summary pages. So when we work on making them the same, this will change too.
=> Online applications summary

.rubocop.yml, app/builders/online_application_builder.rb, app/controllers/api/submissions_controller.rb, app/services/hwf_reference_generator.rb, spec/builders/online_application_builder_spec.rb, spec/controllers/api/submissions_controller_spec.rb, spec/factories/public_app_submissions.rb, spec/services/hwf_reference_generator_spec.rb
This is the MVP for receiving data (currently JSON) from the public app.
It will create an online_application, generate (and add) a (HWF-) reference number and save it to the database.
Things that still need work: 
* confirm format of reference!
* test non-generation of whatever format is decided on
* expand return values when errors occur.
=> Create online application

app/controllers/api/submissions_controller.rb, app/models/online_application.rb, db/migrate/20160322151510_add_feedback_opt_in_to_online_application.rb, db/schema.rb, spec/factories/online_applications.rb, spec/models/online_application_spec.rb
This aligns the staff app with the public app and ensures that the new feedback_opt_in field is recorded
=> Add feedback_opt_in to online_applications

app/builders/application_builder.rb, spec/builders/application_builder_spec.rb
We wanted to preserve the original reference, but it was forgotten to be
copied. So this is a bug fix for that feature.
=> Copy reference from OnlineApplication

Gemfile.lock
The Travis CI build pre-installs PhantomJS-1.9.8, but Jasmine was trying to use 2.1.1.0. 
This meant that Travis needed to download and install it each time travis ran... this often failed :-1:
I've locked the Gemfile to use Travis' pre-installed version, it now.just.works. :boom:
=> Lock PhantomJS to 1.9.8

app/assets/stylesheets/errors.scss, app/controllers/home_controller.rb, app/services/dwp_monitor.rb, app/services/health_status.rb, app/views/home/index.html.slim, app/views/shared/dwp/_offline.html.slim, app/views/shared/dwp/_online.html.slim, app/views/shared/dwp/_warning.html.slim, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/services/dwp_monitor_spec.rb, spec/views/home/index.html.slim_spec.rb
Monitor the last 20 requests and return a state based on the number of 400 Bad Requests received
This is then called from the home controller to display the correct banner.
Update the healthcheck page to call the monitor too.
To do
===
=> Monitor dwp

.env.test, Gemfile, Gemfile.lock, config/initializers/rack_redirect.rb, config/settings.yml, spec/features/domain_redirection_spec.rb
This allows us to redirect requests coming to a domain to another domain. Useful for the `trial -> prod` migration.
=> Redirection between environments

app/views/home/index.html.slim, spec/controllers/home_controller_spec.rb, spec/services/dwp_monitor_spec.rb, spec/support/dwp_setup.rb, spec/views/home/index.html.slim_spec.rb
This restores the conditional display of the DWP status banner.
It got removed during the foundation removal.
Tests have been added to ensure that the controller generates the correct state and that the view displays the correct text.
=> Restore dwp banner

app/controllers/home_controller.rb, app/views/home/index.html.slim, app/views/shared/dwp/_maintenance.html.slim, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/views/home/index.html.slim_spec.rb
A temporary banner timed to be displayed on the homepage.
The view spec is a bit hacky, but the view has to be extended to include the `dwp_maintenance?` method, which then can be stubbed.
=> Display DWP maintenance banner for date range

app/views/applications/process/confirmation.html.slim, app/views/evidence/confirmation.html.slim, app/views/guide/process_application.html.slim, config/locales/en.yml, spec/features/applications/remission_confirmation_spec.rb
Also, updated online ref number format example
=> Removed 'remission register' from guidance

app/controllers/home_controller.rb, app/services/application_search.rb, app/views/home/index.html.slim, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/services/application_search_spec.rb
When a member of staff searched for a HWF reference that had already been processed, they would be allowed to continue until they hit complete processing, at which point it would crash.
This PR shows an error if the number has previously been processed.
If it was by the users office, it includes a routed link.
If it was by a different office, it includes the name of the office that processed it, but no link.
This is because of the Pundit policy for accessing applications for different offices.
[Pivotal](https://www.pivotaltracker.com/story/show/118470941)
=> Prevent public HWF reference reuse

app/controllers/online_applications_controller.rb, app/models/forms/online_application.rb, spec/controllers/online_applications_controller_spec.rb, spec/models/forms/online_application_spec.rb
When processing online-applications a users' default jurisdiction
was not being set on the new object and being shown on the view
[Pivotal](https://www.pivotaltracker.com/story/show/118470941)
[finishes #118470941]
=> Enable default jurisdiction

app/builders/application_builder.rb, app/models/online_application.rb, db/migrate/20160509081902_allow_null_income_columns_for_online_application.rb, db/schema.rb, spec/builders/application_builder_spec.rb, spec/models/online_application_spec.rb
This change allows `children` to be set to `nil` for `OnlineApplication`, which is needed for the branching of benefit/income journeys in the public app.
=> Changes for benefit online submission

app/assets/stylesheets/local/errors.scss
[Pivotal](https://www.pivotaltracker.com/story/show/118280569)
The border on the fee box is faked using a wrapping `div` so that it encompasses the currency symbol. This broke badly when the error handling styles were invoked. This works around that with further fakey bordery nonsense.
Before
---
After
---
=> nasty css hacky border rubbish for fee box

app/views/layouts/application.html.slim, app/views/layouts/local-template.html.erb, app/views/shared/_analytics.html.slim, app/views/shared/_tag_manager.html.slim, config/settings.yml
Add Google Analytics and Google Tag Manager to the staff app to enable generation of GDS performance Platform metrics.
Use Tags, Triggers and events to generate completed events upon form submission.
Initially, I have added the google JS code snippets and I will try configuring the recording of events between Google Tags and Google Analytics events.
=> Performance platform integration

app/assets/javascripts/application.js, app/assets/javascripts/equal_height_boxes.js, app/assets/stylesheets/local/panels.scss, app/controllers/applications/process_controller.rb, app/views/applications/process/benefits.html.slim, app/views/benefit_overrides/paper_evidence.html.slim, app/views/home/index.html.slim, config/locales/en.yml, spec/controllers/applications/process_controller_spec.rb, spec/features/applications/benefit_results_are_processed_spec.rb, spec/views/home/index.html.slim_spec.rb
This will update the staff dashboard to highlight the degraded state of the DWP checker by:
=> DWP down update

app/assets/stylesheets/local/panels.scss, app/helpers/processed_views_helper.rb, app/models/views/application_overview.rb, app/models/views/application_result.rb, app/models/views/processed_data.rb, app/views/shared/_remission_type.html.slim, app/views/shared/processed_and_deleted/_show.html.slim, config/locales/en.yml, spec/controllers/deleted_applications_controller_spec.rb, spec/controllers/processed_applications_controller_spec.rb, spec/factories/part_payments.rb, spec/features/processed_applications/list_deleted_applications_spec.rb, spec/models/views/application_overview_spec.rb, spec/models/views/application_result_spec.rb, spec/models/views/processed_data_spec.rb
[Pivotal ticket](https://www.pivotaltracker.com/story/show/120572955) to update the processed application display to
New display of `return`ed applications, includes processing summary:
=> Processed application display

app/controllers/benefit_overrides_controller.rb, app/services/benefit_check_runner.rb, app/views/benefit_overrides/_out_of_time.html.slim, config/locales/en.yml, spec/factories/details.rb, spec/features/benefit_override/out_of_time_refund_application_handled_correctly_spec.rb, spec/services/benefit_check_runner_spec.rb
[Pivotal ticket](https://www.pivotaltracker.com/story/show/116873277)
We cause errors when we ask the DWP for checks longer than 3 months ago, so when a refund is processed from more than three months ago.  Don't even send a check to the DWP and render a pertinent error message to to the user.
=> Handling DWP checks for out of time refunds

app/builders/application_builder.rb, app/models/application.rb, app/models/views/application_overview.rb, app/models/views/application_result.rb, app/models/views/confirmation/result.rb, app/models/views/overview/savings_and_investments.rb, config/locales/en.yml, lib/savings_transformation.rb, spec/builders/application_builder_spec.rb, spec/features/applications/application_form_stories_spec.rb, spec/lib/savings_transformation_spec.rb, spec/models/views/application_overview_spec.rb, spec/models/views/application_result_spec.rb, spec/models/views/confirmation/result_spec.rb
This PR is designed to allow us to add to the `update-savings` branch while allowing a quicker review process...
Fixes to be implemented
===
Features to be implemented
===
Nice to have
===
=> Fixes and extension of Update Savings

Gemfile, Gemfile.lock, README.md
Due to a code injection warning in [CVE-2015-8806](http://www.cvedetails.com/cve/CVE-2015-8806/)
=> Update nokogiri to 1.6.8

app/models/forms/application/savings_investment.rb
By switching to integer from decimal it doesn't add .0 on re-display
[Pivotal bug ticket](https://www.pivotaltracker.com/story/show/122132311)
=> Changed amount datatype

app/models/forms/application/detail.rb, spec/models/forms/application/detail_spec.rb
Remove the maximum 3 month limit in accordance with [pivotal](https://www.pivotaltracker.com/story/show/120940853)
=> Update the refund date validation

app/lib/income_calculation.rb, spec/lib/income_calculation_spec.rb
The proper fix should be that the children field is always 0 or more,
but the public app at the moment sends nil when the user selects 'No'.
So that has to be fixed first.
=> Use 0 for children when nil for income calculation

app/builders/finance_report_builder.rb, app/models/business_entity.rb, spec/builders/finance_report_builder_spec.rb, spec/models/business_entity_spec.rb
[Pivotal ticket](https://www.pivotaltracker.com/story/show/120915287)
The digital and MCTS HQ team needed to be excluded from the Financial MI report
This adds a scope and calls it in the report builder service.
=> Update offices for MI report

config/settings.yml
Hi @novotnyjakub Can you please check the code to exclude "branch runner" jobs from "active_job".
I was not able to set ACTIVE_JOB_ENABLED to "false" in the branch-runner container
=> exclude branch runner builds from active_job

app/assets/stylesheets/local/panels.scss, app/controllers/applications/process_controller.rb, app/models/application.rb, app/models/decision_override.rb, app/models/forms/application/decision_override.rb, app/models/views/application_overview.rb, app/models/views/application_result.rb, app/models/views/confirmation/result.rb, app/models/views/processed_data.rb, app/services/override_decision_service.rb, app/views/applications/process/confirmation.html.slim, app/views/shared/_decision_override.html.slim, app/views/shared/processed_and_deleted/_show.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20160627135552_create_decision_overrides.rb, db/schema.rb, spec/controllers/applications/process_controller_spec.rb, spec/factories/decision_overrides.rb, spec/features/applications/confirmation_is_rendered_spec.rb, spec/models/decision_override_spec.rb, spec/models/forms/application/decision_override_spec.rb, spec/models/views/application_overview_spec.rb, spec/models/views/application_result_spec.rb, spec/models/views/confirmation/result_spec.rb, spec/models/views/processed_data_spec.rb, spec/services/override_decision_service_spec.rb
[Pivotal ticket](#120851949)
Allows users to override an application that has failed via the benefit route.
Still to do 
===
=> Manager override on confirmation page

app/assets/javascripts/application.js, app/assets/javascripts/close_alerts.js
[Pivotal](https://www.pivotaltracker.com/story/show/117545043)
The staff app features alert boxes, or flash messages, that have a close button marked with an 'x' that doesn't do anything. This lets the user close the messages by clicking the 'x'.
=> js close for alert boxes

app/builders/application_builder.rb, app/controllers/api/submissions_controller.rb, app/lib/income_calculation.rb, db/migrate/20160716101626_add_income_thresholds_to_application.rb, db/migrate/20160720072635_add_income_thresholds_to_online_application.rb, db/schema.rb, spec/builders/application_builder_spec.rb, spec/lib/income_calculation_spec.rb
This PR makes an addition to the income calculation, which supports min/max income thresholds as well. There is no change to the behaviour of the staff app itself, it's a preparation for the integration with `hwf-publicapp`.
=> Accept income range

app/views/guide/appeals.html.slim, app/views/guide/part_payments.html.slim, app/views/guide/suspected_fraud.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/120591891)
The headlines in the guide sections were showing the wrong icons.
=> fix staff guide headline icons

app/assets/stylesheets/local/lists.scss, app/helpers/processed_views_helper.rb, app/views/shared/processed_and_deleted/_index.html.slim, app/views/shared/processed_and_deleted/_per_page_display.html.slim, spec/controllers/deleted_applications_controller_spec.rb, spec/controllers/processed_applications_controller_spec.rb
[Pivotal ticket](https://www.pivotaltracker.com/story/show/126793691)
On first load the page defaults to 50 records per-page for processed/deleted application indexes.
This adds a selector for 50/100/500/All to allow users to select their preference, for a single use of the page
=> Variable pagination

Gemfile, Gemfile.lock, config.ru
Memory usage on the production instances has been increasing over time, it was suggested to try refreshing the unicorn workers to free up memory.
Kill unicorn workers when memory and/or processes exceed the thresholds
I found two examples for setting the thresholds [here](http://www.rubydoc.info/gems/unicorn-worker-killer/0.4.4) and [here](https://www.digitalocean.com/community/tutorials/how-to-optimize-unicorn-workers-in-a-ruby-on-rails-app) but either seemed very high or low.  I've split the difference and we can monitor the results and adjust as required.
Another potential culprit is beaver.  If this does not demonstrably reduce the memory usage over time, we should look at something similar for beaver on the sever.
=> Unicorn killer

app/controllers/evidence_controller.rb, app/models/evidence_check_flag.rb, app/services/evidence_check_flagging_service.rb, app/services/evidence_check_selector.rb, db/migrate/20160801095935_create_evidence_check_flag.rb, db/migrate/20160803121730_add_type_to_evidence_check.rb, db/schema.rb, spec/controllers/evidence_controller_spec.rb, spec/factories/evidence_check_flags.rb, spec/models/evidence_check_flag_spec.rb, spec/services/evidence_check_flagging_service_spec.rb, spec/services/evidence_check_selector_spec.rb
[Ticket](https://www.pivotaltracker.com/story/show/126320983)
Flag NI numbers that have had a failed or returned evidence check.  
* Automatically re-check on subsequent applications.  
* Count the number of failed applications for MI purposes.
* Clear a flag on completion of a successful evidence check
=> Flag evidence checks

app/services/application_search.rb, config/locales/en.yml, spec/factories/online_applications.rb, spec/features/search/staff_cannot_process_applications_with_errors_spec.rb, spec/services/application_search_spec.rb
A situation (now rectified) on the public app meant that users could submit applications with incomplete income data.  When a user entered the reference number, edit the application to add fee, date received, etc; but then, when they pushed next, they would get a blank white error screen.
This fix means that now, when a user searches for a reference of an affected application, a message is displayed explaining why they cannot proceed.
=> Prevent errors when processing online applications

app/services/resolver_cost_calculator.rb, db/migrate/20160818114238_update_decision_cost.rb, db/schema.rb, lib/correct_returned_costs.rb, spec/lib/correct_returned_costs_spec.rb, spec/services/resolver_service_spec.rb
When an application is finalised the resolver service is supposed to calculate a final cost to the department.  In some cases this was not completing properly.  In reports, we had applications with a decision of None (no remission, applicant pays full amount) and a decision_cost.
When a feature was added to return part-payments and evidence checks, a new outcome type of `return` was created, this was not checked for in the resolver cost calculator
Check for `none` and `return` in the calculator and set the return value to 0 for both.  Update the test scenarios and add a migration script to change the, currently wrong, entries in the DB.
=> Resolver cost update

app/services/business_entity_generator.rb, app/services/reference_generator.rb, app/services/resolver_service.rb, db/migrate/20160819130824_add_missing_business_entities.rb, db/schema.rb, lib/update_missing_business_entities.rb, spec/lib/update_missing_business_entities_spec.rb, spec/services/business_entity_generator_spec.rb, spec/services/resolver_service_spec.rb
Business entities are not being created for online_applications when they are processed
Originally, when adding a paper form, the system created a business entity and reference at the same time and, so, were encapsulated into a single service class.
Since then, we've added a different type of form (online) and, because they already have a reference generated, this meant that business entities were not being created when processing them.
Split the service class into two and call the business entity one always and the reference one as needed.  Update the test scenarios and add a migration script to change the, currently wrong, entries in the DB.
=> Online business entities fix

app/assets/stylesheets/local/panels.scss, app/models/views/application_result.rb, config/locales/en.yml, spec/features/processed_applications/list_processed_applications_spec.rb, spec/models/views/application_result_spec.rb
[Trello Ticket](https://trello.com/c/1AnbDZWm/12-part-payment-should-say-paid-once-it-is-processed)
When a part payment goes into the list of processed applications it should say "the applicant has paid..."
As a member of staff
I want to see that a part payment has been paid (currently it looks like it is still outstanding)
=> Part payment should say paid once it has been processed

app/controllers/application_controller.rb, app/controllers/applications/process_controller.rb, app/controllers/online_applications_controller.rb, app/models/online_application.rb, spec/controllers/online_applications_controller_spec.rb, spec/models/online_application_spec.rb
After users have clicked through the standard flow, they (regularly) use the browser back button to return to an earlier page and then click continue... as we have cleared the session values at this point it causes 500 errors.
This PR replicates the work done on the paper application flow, to expire the headers (enforcing a page reload) and redirect if the application is complete.
=> Expire online application pages

app/views/applications/partials/_full_fee.html.slim, app/views/applications/process/confirmation.html.slim, app/views/evidence_checks/show.html.slim, app/views/shared/_remission_type.html.slim, config/locales/en.yml
Replace with _html names that are escaped internally
This removes a brakeman XSS warning
=> Remove HTML-safe from I18n

app/models/forms/application/decision_override.rb, spec/features/applications/confirmation_is_rendered_spec.rb, spec/models/forms/application/decision_override_spec.rb
[Trello ticket](https://trello.com/c/L1NWBlRK/10-include-manager-override-question-for-income-applications)
Allow users to override, and grant, applications when they fail income applications too.
Currently override is only allowed on benefit applications.
=> Add override to income

.rubocop.yml, app/builders/application_builder.rb, app/builders/finance_report_builder.rb, app/controllers/application_controller.rb, app/controllers/applications/process_controller.rb, app/controllers/benefit_overrides_controller.rb, app/controllers/evidence_controller.rb, app/controllers/online_applications_controller.rb, app/controllers/part_payments_controller.rb, app/controllers/processed_applications_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users_controller.rb, app/lib/income_calculation.rb, app/models/benefit_check.rb, app/models/forms/application/applicant.rb, app/models/forms/application/decision_override.rb, app/models/forms/application/income.rb, app/models/views/office_business_entity_state.rb, app/models/views/overview/applicant.rb, app/models/views/processed_data.rb, app/models/views/reports/raw_data_export.rb, lib/tasks/jurisdictions.rake, spec/controllers/application_controller_spec.rb, spec/controllers/offices_controller_spec.rb
* Update rubocop to 2.3 parser
* we updated to ruby 2.3 _**5**_ months ago!
* turned off the Style/FrozenStringLiteralComment as it errored on every single page and is due to be implemented in ruby 3
* made code-climate happy
* Removed OUTER from the LEFT JOINS
* Updated the recent SQL refactor to use the new, indenting, HEREDOC format
=> General Refactor

app/services/override_decision_service.rb, db/migrate/20161207104343_complete_decision_cost.rb, db/schema.rb, lib/decision_cost_migration.rb, spec/lib/decision_cost_migration_spec.rb, spec/services/override_decision_service_spec.rb
When a user manually overrides a no decision, the value was not being set
This PR ensures that the decision_cost is set on manual override and backdates the change to pre-existing granted applications
=> Set decision_cost when granting application

app/builders/finance_report_builder.rb, app/models/views/reports/finance_report_data_row.rb, spec/models/views/reports/finance_report_data_row_spec.rb
The monthly finance report was failing because a new, unexpected, data type was being returned.
This now shows applications that failed benefit and income as `granted`
=> Report fix for none rows

app/models/user.rb, spec/models/user_spec.rb
A new email domain has been created and is in use by the HMCTS sustaining team.
This was needed so that we could add their users.
=> Add hmcts net emails

app/models/views/reports/finance_report_data_row.rb, spec/models/jurisdiction_spec.rb, spec/models/office_spec.rb, spec/models/views/reports/finance_report_data_row_spec.rb
When the finance report is generated only the SOP code was shown, now the legacy BE codes are displayed too.
Fixed a couple of validation, race conditions too
=> Ensure both codes are displayed

app/helpers/flash_message_helper.rb, app/views/users/passwords/edit.html.slim, config/locales/en.yml, spec/features/password_reset_message_spec.rb
Validation of password reset token is handled by Devise. 
The error is added as an AR error so we can display it as a flash message.
=> Displaying error message if password reset token is expired.

app/models/online_application.rb, db/migrate/20170331153241_change_probate_to_accept_null.rb, db/schema.rb, spec/models/online_application_spec.rb
Announcement made in the media that changes to probate fees will be scrapped due to the general election (http://www.bbc.co.uk/news/uk-politics-39663204).
This means we will not get a decision on the HwF probate changes until well after the 2017 general election.
=> Revert "Accept online applications without probate"

app/views/layouts/application.html.slim, spec/views/layouts/application.html.slim_spec.rb
When the notifications feature was implemented it was asked to not include any links to the edit page.
It is convenient though to have a link for the admins to use, so we decided to add one.
=> display the Edit banner link on the main menu only for admin users

app/controllers/applications/process/summary_controller.rb, spec/controllers/applications/process/summary_controller_spec.rb
When you manage to re-submit the new application and the applicaiton is in other state then new the resolver will automaticly moves it to next state which in our case was skipping "waiting for payment" state.
=> Fixing state skipping bug

spec/features/no_evidence_check/rst_1111_spec.rb, spec/features/no_evidence_check/rst_985_spec.rb, spec/features/no_evidence_check/rst_987_spec.rb
Added 2 scenarios based on my discussion with Atull to check Benefit applications with Paper evidence failed. 
Also added test for Ticket RST-1111 
And a test to verify that Duplicate NINO is not included in 1 in 2 count for refund application.
=> Adding more test 987 985

app/controllers/application_controller.rb, app/controllers/applications/process/benefits_controller.rb, app/controllers/dwp_warnings_controller.rb, app/controllers/home_controller.rb, app/models/dwp_warning.rb, app/policies/dwp_warning_policy.rb, app/views/dwp_warnings/edit.html.slim, app/views/layouts/application.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20180717100104_create_dwp_warnings.rb, db/schema.rb, spec/factories/dwp_warnings.rb, spec/models/dwp_warning_spec.rb
We can now choose if we want to use default DWP monitor or just say that DWP is down/up.
=> Adding overwrite for DWP message

.rubocop.yml, app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/index.html.slim, config/routes.rb, spec/controllers/users_controller/admin_user_spec.rb, spec/factories/users.rb, spec/policies/user_policy_spec.rb, spec/routing/users_routing_spec.rb, spec/views/users/index.html.slim_spec.rb
This enhancement allows admins to re-invite users who haven't accepted their account invitation or it expired
=> RST-1085 Re-invite users

app/controllers/application_controller.rb, spec/features/manager_out_of_the_box_experience_spec.rb
Managers get confused when they are setting up their accounts for the first time and they change the office name of their assigned office. Therefore, it was decided to remove the office setup from the account setup process. 
Managers will still be able to change the office details from the change office page.
=> Remove office setup from the quick profile setup process for managers

app/services/hwf_reference_generator.rb, spec/services/hwf_reference_generator_spec.rb
There was an issue when the reference generator generated refernce HWF-AHW-HWF. The issue was that the application was invisible because of the way how the search is parsing the string (removing the hwf prefix). So I'm just making sure that there is no duplication again.
=> Making sure that the prefix HWF is unique

app/builders/application_builder.rb, db/migrate/20181114150745_add_medium_to_applications.rb, db/schema.rb, spec/builders/application_builder_spec.rb
Up until now we were using the reference number to distinguish paper applications against digital. This PR introduces the "Medium" column in the applications table to make it easier to query the applications by type.
=> Create Medium field to recognise digital vs paper applications

app/repositories/application_form_repository.rb, spec/features/applications/processing_refund_application_spec.rb, spec/repositories/application_form_repository_spec.rb
When the refund application is processed and the discretion is not applied aka is set to false it will not fill the application type so it stays nil. So when the discretion is not applied it will set the outcome but not the application type. And because that's the end of the process the application type is never filled. I'm making sure that the application type is set when the discretion is not applied.
=> Fixing issue with blank application type

config/locales/en.yml, spec/features/user_profile_spec.rb
The app is using devise's default message when updating the password. 
This PR reflects that to the tests.
=> Fix the update password spec

Gemfile, Gemfile.lock
Chartkick was updated to the latest version 3.0.1 but they drop the support of rails 4.2 since version 3.0.0 so I updated the gem to the latest version that works.
=> Fixing issue with graphs that didn't load

app/views/home/index.html.slim, features/step_definitions/generate_report_steps.rb, features/step_definitions/reports_steps.rb, features/support/page_objects/reports_page.rb
The generate reports link on the homepage will now be redirecting the users to the reports page, where they can choose which report they like to generate.
=> Change the generate reports link

.travis.yml
Travis is failing to build `capybara-webkit` with error message:
```
fatal error: QWebElement: No such file or directory
compilation terminated.
```
Adding the `libqtwebkit-dev` addon, solves the issue.
=> Add libqtwebkit-dev travis addon

app/assets/javascripts/gtm_track_timestamps.js, app/views/layouts/application.html.slim
I had to separate the tracking in two logics because for some reason we are not displaying the header alert when some forms have validation errors.
=> RST-1952 - Adding GM tracking for error messages

Gemfile, Gemfile.lock, app/views/home/index.html.slim, app/views/reports/graphs.html.slim, spec/features/applications/stray_error_on_confirmation_page_spec.rb, spec/rails_helper.rb
This PR sorts out the [CVE-2019-12732](https://nvd.nist.gov/vuln/detail/CVE-2019-12732) issue in chartkick gem.
=> Bump chartkick from 2.3.5 to 3.2.0

app/assets/javascripts/gtm_track_timestamps.js, app/controllers/evidence_checks_controller.rb, app/controllers/home_controller.rb, app/controllers/part_payments_controller.rb, app/views/evidence_checks/index.html.slim, app/views/home/_waiting_applications.html.slim, app/views/home/index.html.slim, app/views/part_payments/index.html.slim, config/locales/en.yml, config/routes.rb, features/dashboard.feature, features/step_definitions/evidence_steps.rb, features/step_definitions/sign_in_steps.rb, features/step_definitions/user_dashboard_steps.rb, features/support/page_objects/dashboard_page.rb, features/support/page_objects/sign_in_page.rb, spec/controllers/evidence_checks_controller_spec.rb, spec/controllers/part_payments_controller_spec.rb, spec/features/evidence-checks/evidence_check_part_payment_flow_spec.rb, spec/features/evidence/applications_awaiting_evidence_are_displayed_on_dashboard_spec.rb, spec/features/no_evidence_check/rst_985_spec.rb, spec/features/online_applications/evidence_check_spec.rb, spec/features/part_payments/applications_awaiting_payment_are_displayed_on_dashboard_spec.rb, spec/features/return_applications/return_evidence_checkable_applications_spec.rb, spec/features/return_applications/return_part_payment_applications_spec.rb
https://tools.hmcts.net/jira/browse/RST-1268
Removing "Waiting for part-payment" and "Waiting for evidence check" lists from the homepage and moving them to their own page. 
```
[] Yes
[x] No
```
=> RST-1268: Removing waiting applications from home page

app/builders/finance_report_builder.rb, spec/builders/finance_report_builder_spec.rb
https://tools.hmcts.net/jira/browse/RST-2192
Updating the Finance report builder to use the distinct method.
The `Relation#uniq` has been [removed](https://github.com/rails/rails/commit/adfab2dcf4003ca564d78d4425566dd2d9cd8b4f) from Rails 5+ and it's suggested to use `Relation#distinct instead.
```
[ ] Yes
[X] No
```
=> Fix the finance report

app/controllers/applications/process/summary_controller.rb, spec/controllers/applications/process/summary_controller_spec.rb
https://tools.hmcts.net/jira/browse/RST-2222
Arbitrary context must be defined in the extra attribute when using `Raven.capture_exception`
```
[ ] Yes
[X] No
```
=> Fix broken sentry event capture

config/locales/letters_en.yml, spec/features/evidence/evidence_check_flow_spec.rb
https://tools.hmcts.net/jira/browse/RST-2149
Improving clarity for the "declined" message based on income.
```
[ ] Yes
[x] No
```
=> RST-2149 - Removing line about maximum incume allowed

app/controllers/evidence/accuracy_failed_reason_controller.rb, app/models/forms/accuracy.rb, app/models/forms/evidence/accuracy.rb, app/views/evidence/accuracy_failed_reason/show.html.slim, config/locales/en.yml, db/migrate/20191121152746_add_staff_error_details_to_evidence_check.rb, db/schema.rb, features/problem_with_evidence.feature, features/step_definitions/problem_with_evidence_steps.rb, features/support/page_objects/evidence_page.rb, features/support/page_objects/problem_with_evidence_page.rb, spec/controllers/evidence/accuracy_failed_reason_controller_spec.rb, spec/models/forms/accuracy_spec.rb, spec/models/forms/evidence/accuracy_spec.rb
https://tools.hmcts.net/jira/browse/RST-2332
Adding staff error details field when the evidence rejection reason is staff error
```
[ ] Yes
[x] No
```
=> RST-2332 - Adding staff error details field

features/step_definitions/confirmation_steps.rb, features/step_definitions/evidence_steps.rb, features/step_definitions/find_application_steps.rb, features/step_definitions/processed_applications_steps.rb, features/step_definitions/return_letter_steps.rb, features/support/generic_helpers.rb, features/support/page_objects/confirmation_page.rb, features/support/page_objects/find_application_page.rb, features/support/page_objects/problem_with_evidence_page.rb, features/support/page_objects/processed_applications_page.rb, features/support/page_objects/reason_for_rejecting_evidence_page.rb
Fixing cucumber test with hardcoded prefix number (based on year).
```
[ ] Yes
[x] No
```
=> Fixing issue with hardcoded ref number in tests

app/views/reports/letters.html.slim
https://tools.hmcts.net/jira/browse/RST-2452
There are two missing variables in the letter templates page, causing errors when visiting the page. 
This PR adds the missing variables.
```
[ ] Yes
[X] No
```
=> Add missing variables in the letter templates page

app/services/evidence_check_selector.rb, db/migrate/20200114155638_rename_ccmcc_check_type_column.rb, db/schema.rb, spec/services/evidence_check_selector_spec.rb
Renaming evidence check column for ccmcc annotations.
```
[ ] Yes
[x] No
```
=> Renaming ccmcc_check_type to ccmcc_annotation

app/assets/stylesheets/local/layout.scss
=> Fixing word break in IE11

app/services/ccmcc_evidence_check_rules.rb, app/services/evidence_check_selector.rb, spec/services/ccmcc_evidence_check_rules_spec.rb, spec/services/evidence_check_selector_spec.rb
When the evidence check is not matching frequency from ccmcc rules the annotation should be empty.
```
[ ] Yes
[x] No
```
=> CCMCC  fix 1

app/services/ccmcc_evidence_check_rules.rb, app/services/evidence_check_selector.rb, spec/services/ccmcc_evidence_check_rules_spec.rb, spec/services/evidence_check_selector_spec.rb
For CCMCC pilot we counting only against CCMCC applications
```
[ ] Yes
[x] No
```
=> Updating the frequency query

config/environments/production.rb
The Staff app accepts only HTTPS requests, however the Public app uses the internal network to submit the applications. These requests are HTTP, causing Staff app to reject them. 
This exclusion will allow Staff app to receive the Public app submissions.
=> Allow HTTP requests on the API submission endpoint

app/controllers/api/submissions_controller.rb, app/models/online_application.rb, db/migrate/20200325104858_add_ho_number_to_online_application.rb, db/migrate/20200325110607_remove_mandatory_flag_for_ni_number_from_online_application.rb, db/schema.rb, features/support/env.rb, spec/models/online_application_spec.rb
https://tools.hmcts.net/jira/browse/RST-2548
Updating API so it accepts Home office number if the NI number is empty.
```
[ ] Yes
[x] No
```
=> RST-2548 API home office number

app/models/user.rb, app/views/layouts/application.html.slim, config/initializers/devise.rb
Expire user sessions after one hour of inactivity.
Timeoutable uses the FlashHash as global storage which causes issues when displaying flash messages. The workaround is to skip non String values. See Github thread for more info https://github.com/heartcombo/devise/issues/1777
https://tools.hmcts.net/jira/browse/RST-2121
Expire user sessions after one hour of inactivity.
```
[ ] Yes
[X] No
```
=> Enable Devise timeoutable module

app/services/benefit_check_service.rb, db/migrate/20200623062753_add_api_response_to_benefit_checker.rb, db/schema.rb, spec/services/benefit_check_service_spec.rb
if the result is undetermined
https://tools.hmcts.net/jira/browse/RST-2729
```
[ ] Yes
[x] No
```
=> Storing whole API response

app/views/guide/index.html.slim, features/staff_guides.feature, features/step_definitions/staff_guides_steps.rb, features/support/page_objects/guide_page.rb
Covid 19 Guidance link has been removed from the page See the guides.
```
[ ] Yes
[X] No
```
=> RST-3801 Removed Covid 19 Guidance in See the guides page.

Gemfile.lock
Name: rexml
Version: 3.3.1
Advisory: CVE-2024-39908
Criticality: Unknown
URL: https://github.com/ruby/rexml/security/advisories/GHSA-4xqq-m2hx-25v8
Title: DoS in REXML
Solution: upgrade to '>= 3.3.2'
=> RST-6785 - update rexml to 3.3.2

app/assets/stylesheets/application.scss, charts/help-with-fees-staffapp/Chart.yaml, package-lock.json, package.json
Reverts hmcts/hwf-staffapp#1981
There is an issue with rendering https://staff.helpwithcourtfees.service.gov.uk/assets/govuk-frontend/dist/govuk/govuk-frontend.min-8b6a07624fe1aea82b59a97aa6fbe426ea82d3c47ec993eeb37118ad7b26885d.js 
this happened before, last time we updated govuk frontend.
=> Revert "RST-7098 Updated GovUK Frontend to 5.8.0"

config/application.rb
https://tools.hmcts.net/jira/browse/RST-7126
https://tools.hmcts.net/jira/browse/RST-7115
Sentry is not reporting correctly the issue because of this I think.
=> RST-7126 Removing middleware use of ApplicationInsights

Gemfile.lock, app/views/shared/savings/_amount.slim
There was duplicate types declared on an input field. Removed the 'text' type and kept the 'number' type.
=> Remove text type on input field and keep number type
